/**
 * The shared lettering cases, run against this package's reader and layout rule.
 *
 * `lettering-cases.json` is generated by `scripts/generate_lettering_cases.py` from the Python
 * rule, which is the reference; `tests/test_lettering_cases.py` runs the same file against it and
 * holds the file to its generator. Here the TypeScript copy has to agree: the same acceptance, the
 * same placements to the millimetre, and the same one reason for every refusal.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  CATALOG_REASONS,
  CHARACTER_SET,
  type CanonicalValue,
  type GlyphCatalog,
  LAYOUT_REASONS,
  LetteringRefusal,
  canonicalBytes,
  glyphPartsMm,
  layoutSign,
  readGlyphCatalog,
} from '../src/core/index.js';

const HERE = fileURLToPath(new URL('.', import.meta.url));

interface Change {
  path: (string | number)[];
  value?: unknown;
  remove?: true;
}
interface CatalogCase {
  name: string;
  catalog: string;
  changes?: Change[];
  text_edits?: [string, string][];
  append?: string;
  reason: string | null;
}
interface LayoutCase {
  name: string;
  catalog: string;
  text: string;
  cap_height_mm: number;
  tracking_mm: number;
  alignment: string;
  box_width_mm: number;
  box_height_mm: number;
  reason: string | null;
  layout?: { placements: [number, string, number, number][]; ink: [number, number, number, number] };
}
interface GlyphCase {
  name: string;
  catalog: string;
  character: string;
  cap_height_mm: number;
  parts: { outer: number[]; holes: number[][] }[];
}
interface Cases {
  catalogs: Record<string, string>;
  catalog_cases: CatalogCase[];
  layout_cases: LayoutCase[];
  glyph_cases: GlyphCase[];
}

const cases = JSON.parse(readFileSync(join(HERE, 'lettering-cases.json'), 'utf8')) as Cases;

const read = new Map<string, GlyphCatalog>();
function catalog(name: string): GlyphCatalog {
  const found = read.get(name);
  if (found !== undefined) return found;
  const parsed = readGlyphCatalog(new Uint8Array(readFileSync(join(HERE, cases.catalogs[name]!))));
  read.set(name, parsed);
  return parsed;
}

function applyChanges(document: unknown, changes: readonly Change[]): unknown {
  const copy = JSON.parse(JSON.stringify(document)) as unknown;
  for (const change of changes) {
    let parent = copy as Record<string | number, unknown>;
    for (const step of change.path.slice(0, -1)) parent = parent[step] as Record<string | number, unknown>;
    const last = change.path.at(-1)!;
    if (change.remove) {
      if (Array.isArray(parent)) parent.splice(last as number, 1);
      else delete parent[last];
    } else {
      parent[last] = change.value;
    }
  }
  return copy;
}

/** The bytes a catalog case hands its reader: the same steps `catalog_bytes` takes in Python. */
function catalogBytes(testCase: CatalogCase): Uint8Array {
  const file = readFileSync(join(HERE, cases.catalogs[testCase.catalog]!));
  let text = file.toString('utf8');
  if (testCase.changes?.length) {
    const changed = applyChanges(JSON.parse(text) as unknown, testCase.changes);
    text = Buffer.from(canonicalBytes(changed as CanonicalValue)).toString('utf8');
  }
  for (const [before, after] of testCase.text_edits ?? []) {
    expect(text.split(before).length - 1, `${testCase.name}: ${before}`).toBe(1);
    text = text.replace(before, after);
  }
  return new Uint8Array(Buffer.from(text + (testCase.append ?? ''), 'utf8'));
}

/** null when `run` accepts, or the reason it refused with. Anything else fails the test. */
function outcome(run: () => unknown): string | null {
  try {
    run();
    return null;
  } catch (error) {
    if (error instanceof LetteringRefusal) return error.reason;
    throw error;
  }
}

describe('the catalog reader', () => {
  for (const testCase of cases.catalog_cases) {
    it(testCase.name, () => {
      const raw = catalogBytes(testCase);
      expect(outcome(() => readGlyphCatalog(raw))).toBe(testCase.reason);
    });
  }

  it('reads the version 1 character set out of every committed catalog', () => {
    for (const name of Object.keys(cases.catalogs)) {
      expect([...catalog(name).glyphs.keys()].join('')).toBe(CHARACTER_SET);
    }
  });
});

describe('the layout rule', () => {
  for (const testCase of cases.layout_cases) {
    it(testCase.name, () => {
      const request = {
        text: testCase.text,
        capHeightMm: testCase.cap_height_mm,
        trackingMm: testCase.tracking_mm,
        alignment: testCase.alignment,
        boxWidthMm: testCase.box_width_mm,
        boxHeightMm: testCase.box_height_mm,
      };
      if (testCase.reason !== null) {
        expect(outcome(() => layoutSign(catalog(testCase.catalog), request))).toBe(testCase.reason);
        return;
      }
      const layout = layoutSign(catalog(testCase.catalog), request);
      expect(
        layout.placements.map((placement) => [
          placement.index,
          placement.character,
          placement.xMm,
          placement.baselineMm,
        ]),
      ).toEqual(testCase.layout!.placements);
      expect([layout.ink.leftMm, layout.ink.bottomMm, layout.ink.rightMm, layout.ink.topMm]).toEqual(
        testCase.layout!.ink,
      );
    });
  }
});

describe('glyph rings in millimetres', () => {
  for (const testCase of cases.glyph_cases) {
    it(testCase.name, () => {
      const parts = glyphPartsMm(catalog(testCase.catalog), testCase.character, testCase.cap_height_mm);
      expect(
        parts.map((part) => ({
          outer: part.outer.flatMap((point) => [...point]),
          holes: part.holes.map((hole) => hole.flatMap((point) => [...point])),
        })),
      ).toEqual(testCase.parts);
    });
  }
});

describe('the cases themselves', () => {
  it('reach every refusal reason both readers can give', () => {
    const catalogReasons = new Set(cases.catalog_cases.map((testCase) => testCase.reason));
    const layoutReasons = new Set(cases.layout_cases.map((testCase) => testCase.reason));
    expect([...catalogReasons].sort()).toEqual([null, ...CATALOG_REASONS].sort());
    expect([...layoutReasons].sort()).toEqual([null, ...LAYOUT_REASONS].sort());
  });
});
