"""The streets generator: a lattice of straight streets, its blocks, curbs, lanes and junctions.

**The layout rule, stage version 2.** Inside the district's rectangle, streets run on two axes.
Streets along x (east-west) lie ``block_depth_mm`` apart and the one through the district's
middle is the high street; streets along y (north-south) lie ``block_length_mm`` apart, placed so
the district's middle falls half way between two of them. A street line is laid out only where its
widest possible cross-section (carriageway, kerb and footway at their declared maxima) stays inside
the district. Streets along x run the district's whole width; streets along y run between the
southernmost and northernmost streets along x and end there in T junctions. Every centreline is one
straight piece between two nodes, so no piece is longer than the district, and a district is at
most 2048 m across.

**Hierarchy and names.** The high street is ``high_street``; every other street is
``local_street``. Each street takes its hierarchy's fewest lanes, half in each direction, the side
of the road the district states deciding which half is which. Names come from the street-name
catalog entries that suit the hierarchy, drawn without repeating.

**Faces.** The streets divide the district into faces: a block between four streets, an open face
where the district's edge closes it, and the two outer faces beyond the first and last streets
along x. Walking a face counter-clockwise gives each curb its follower: a left turn is a corner of
the face's ``corner_radius_mm``, a straight join (where a street ends in a T on the far side) has
radius 0, and the district's edge ends the walk. Every curb of one face shares that face's kerb
height, kerb width, footway width and crossfall, each derived once per face and narrowed to the
ranges of the busiest street hierarchy the face touches, since a footway does not narrow and a kerb
does not change height as a person turns a corner; a block's frontage line is then its kerb lines
moved kerb and footway out, and its ring's corners are its corners' frontage corners exactly.

**Cross-sections.** A carriageway is its lanes and two gutters, centred on the crown line. One
gutter width runs along a whole street, so this version reads ``gutter_width_mm`` bound for the
district or the city and refuses to derive it face by face. Lane width, camber and speed limit are
district values, derived once and narrowed to every hierarchy the district's streets have.
Street dimensions derive on a 50 mm module, so every carriageway is an even number of millimetres
and its crown lies on a whole millimetre. The crown is at the datum; a kerb line lies the camber's
fall below it; a lane's centreline lies on the camber plane.

**Heights.** A kerb line is ``floor(W / 2 * camber / 10**6)`` below the crown, a curb's frontage is
its kerb height and footway rise above its kerb line, and a block's grade is the highest frontage
round it, so no lot lies below the footway it meets.

**Crossings.** Every junction leg carries one, at the near end of its straight kerb run, so it
meets a dropped kerb on both sides and clears the corner arcs. It is ``crossing_width_mm`` wide and
leaves ``dropped_kerb_upstand_mm`` of kerb standing. A leg whose straight run holds only one
crossing carries the one nearer its start node. Every crossing is a zebra: a signalised one names a
plan in traffic's catalog, which the city grammar does not read.

**Not generated by this version,** and each says why: road markings, which no published texture set
dresses; signals, whose plan catalog the city does not read; lane connections and parking. Lane
markings are ``none``, since no paint is generated.

**Junctions.** Every approach states the tightest turn it must admit: the widest turning radius the
lane-use catalog states for the uses of that segment's lanes. The catalog takes those from traffic's
vehicle classes and names that catalog by digest; this stage reads the city's catalog only.

A node where three or four segments meet is a junction. A junction on the high
street gives its high street legs priority and its other legs a stop; any other junction gives the
street that continues through it priority and the street that ends there a stop. Its extent is the
fill the corner rule states (:func:`~exulanica.grammar.grammars.city.corners.junction_fill_box`).
"""

from __future__ import annotations

import dataclasses
from collections import Counter
from collections.abc import Iterator, Mapping, Sequence
from dataclasses import dataclass, field
from itertools import combinations
from typing import Final

from exulanica.grammar.contract import StageContext
from exulanica.grammar.errors import InvalidParameterError, InvalidRecordError
from exulanica.grammar.geometry import Extent, polyline_run_length, ring_centroid
from exulanica.grammar.grammars.city import districts, roads, streets, terrain
from exulanica.grammar.grammars.city.common import MILLIONTHS, SIDE_CODES
from exulanica.grammar.grammars.city.corners import (
    corner_box,
    footway_rise_mm,
    junction_fill_box,
    strip_box,
)
from exulanica.grammar.grammars.city.descriptor import CITY_SURFACE
from exulanica.grammar.grammars.city.generation.stage import (
    GeneratorStage,
    catalog,
    covering,
    derived,
    draw,
    entry,
    prior_records,
)
from exulanica.grammar.grammars.city.generation.terrain import DATUM_MM

__all__ = [
    "DIMENSION_MODULE_MM",
    "STAGE",
    "narrowest_reach",
    "street_hierarchies",
    "street_name_demand",
    "street_name_shortfall",
    "street_names_by_hierarchy",
    "widest_reach",
]

#: The module every street dimension this stage derives is a multiple of.
DIMENSION_MODULE_MM: Final = 50
_HIGH: Final = "high_street"
_LOCAL: Final = "local_street"
_DISTRICT: Final = 0
_EAST: Final = (1, 0)
_NORTH: Final = (0, 1)


def _modular(context: StageContext, name: str, ordinal: int, low: int, high: int) -> int:
    """A dimension on the stage's module: derived in module steps within ``[low, high]``."""
    spec = CITY_SURFACE.parameters.get(name)
    low = max(low, spec.minimum)
    high = min(high, spec.maximum)
    first = low + (-low) % DIMENSION_MODULE_MM
    if first > high:
        raise InvalidParameterError(
            f"{name}: no {DIMENSION_MODULE_MM} mm step lies in [{low}, {high}]"
        )
    bound = context.parameters.get(name)
    if bound is not None:
        value = derived(context, name, ordinal, minimum=low, maximum=high)
        if value % DIMENSION_MODULE_MM:  # type: ignore[operator]
            raise InvalidParameterError(
                f"{name} is bound to {value}, off the {DIMENSION_MODULE_MM} mm module"
            )
        return value  # type: ignore[return-value]
    steps = (high - first) // DIMENSION_MODULE_MM
    return first + DIMENSION_MODULE_MM * draw(context, name, ordinal, 0, steps)


def _room_for_footways(face: _Face) -> int | None:
    """The widest footway a block face can carry and still hold its lots, or None when it is open.

    A closed face is a block: two rows of lots between its north and south frontages, each row at
    least one lot wide along its street. Every millimetre of footway is taken from both sides of
    both spans, so a footway the busiest street admits can be wider than the block behind it has
    to give. This is what the face may spare; the caller narrows the draw to it, and refuses when
    even the narrowest footway does not fit rather than taking the lots.
    """
    if not face.closed:
        return None
    spans: dict[str, list[int]] = {"x": [], "y": []}
    for segment, _side in face.edges:
        street = segment.street
        axis = "y" if street.axis == _EAST else "x"
        spans[axis].append(street.position)
        spans[axis].append(street.carriageway_mm)
    depth_spec = CITY_SURFACE.parameters.get("lot_depth_mm")
    frontage_spec = CITY_SURFACE.parameters.get("lot_frontage_mm")
    room = []
    for axis, needed in (("y", 2 * depth_spec.minimum), ("x", frontage_spec.minimum)):
        positions = sorted(spans[axis][0::2])
        carriageways = spans[axis][1::2]
        span = positions[-1] - positions[0] - sum(carriageways[:2]) // 2
        room.append((span - needed - 2 * face.kerb_width_mm) // 2)
    return min(room)


def _busiest(hierarchies: Sequence[str]) -> str:
    """The busiest street a face touches, by the hierarchy catalog's rank (0 is busiest).

    A block's footway and kerb are one width the whole way round it, and it is the busiest street
    that decides them: a footway does not narrow as a person turns the corner off a high street,
    and a kerb that changed height at a corner would be a trip. Intersecting the ranges instead
    would let the quietest street cap the busiest one, which is how a high street ended up with a
    3.05 m footway when its own hierarchy admits 6 m.
    """
    return min(hierarchies, key=lambda key: entry("street-hierarchy", key)["rank"])


def _ranges(hierarchies: Sequence[str], low_key: str, high_key: str) -> tuple[int, int]:
    low = max(entry("street-hierarchy", key)[low_key] for key in hierarchies)
    high = min(entry("street-hierarchy", key)[high_key] for key in hierarchies)
    if low > high:
        raise InvalidParameterError(
            f"the hierarchies {sorted(set(hierarchies))} share no {low_key} to {high_key} range"
        )
    return low, high


def _section(hierarchy: str, lane_width_mm: int, gutter_width_mm: int) -> tuple[int, int, int]:
    """Lanes, carriageway width, and the room a line of this hierarchy needs clear of the edge.

    ONE STATEMENT OF THE FORMULA. The layout reads it with the widths this city derived, and the
    two reaches below read it with the narrowest and widest the declared ranges admit.
    """
    fields = entry("street-hierarchy", hierarchy)
    lanes = fields["lanes_minimum"]
    carriageway = lanes * lane_width_mm + 2 * gutter_width_mm
    reach = (
        carriageway // 2
        + CITY_SURFACE.parameters.get("kerb_width_mm").maximum
        + fields["footway_width_maximum_mm"]
    )
    return lanes, carriageway, reach


def _lane_width(hierarchy: str, widest: bool) -> int:
    """The narrowest or widest lane this hierarchy can be given, on the even module a lane needs."""
    declared = CITY_SURFACE.parameters.get("lane_width_mm")
    fields = entry("street-hierarchy", hierarchy)
    if widest:
        width = min(declared.maximum, fields["lane_width_maximum_mm"])
        return width - width % 2
    width = max(declared.minimum, fields["lane_width_minimum_mm"])
    return width + width % 2


def narrowest_reach(hierarchy: str) -> int:
    """The least room a line of this hierarchy can need, over the declared ranges.

    THE LEAST ROOM LAYS THE MOST STREETS, so this is the reach a vocabulary must be able to name.
    """
    _lanes, _carriageway, reach = _section(
        hierarchy,
        _lane_width(hierarchy, widest=False),
        CITY_SURFACE.parameters.get("gutter_width_mm").minimum,
    )
    return reach


def widest_reach(hierarchy: str) -> int:
    """The most room a line of this hierarchy can need, over the declared ranges.

    THE MOST ROOM LAYS THE FEWEST STREETS, so this is the reach a caller refusing before
    generation must assume: refusing on any other would refuse a city a narrower street builds.
    """
    _lanes, _carriageway, reach = _section(
        hierarchy,
        _lane_width(hierarchy, widest=True),
        CITY_SURFACE.parameters.get("gutter_width_mm").maximum,
    )
    return reach


def street_hierarchies(
    along_positions: Sequence[int], across_positions: Sequence[int], middle_y: int
) -> list[str]:
    """Every street's hierarchy, in the order this stage numbers streets.

    THE ONE STATEMENT of which street is which: the high street is the line along x through the
    district's middle and every other street is local. The layout below builds its streets from
    this and the vocabulary check counts it, so a version that assigns hierarchies differently
    moves both rather than leaving a check measuring a rule nobody follows any more.
    """
    along = [_HIGH if position == middle_y else _LOCAL for position in along_positions]
    return along + [_LOCAL] * len(across_positions)


def street_name_demand(
    span_x_mm: int, span_y_mm: int, block_length_mm: int, block_depth_mm: int, reach_mm: int
) -> Mapping[str, int]:
    """How many streets of each hierarchy a district of this shape lays out.

    A district's offset does not move how many lines fit inside it, so a span is enough and a
    caller need not know where it starts. ``reach_mm`` decides the rest: pass
    :func:`narrowest_reach` for the most streets the shape can lay and :func:`widest_reach` for
    the fewest.
    """
    middle_x, middle_y = span_x_mm // 2, span_y_mm // 2
    along = _lay_out(0, span_y_mm, middle_y, block_depth_mm, reach_mm, centred=True)
    across = _lay_out(0, span_x_mm, middle_x, block_length_mm, reach_mm, centred=False)
    return Counter(street_hierarchies(along, across, middle_y))


def street_names_by_hierarchy() -> Mapping[str, frozenset[str]]:
    """Every street-name key that suits each street hierarchy, read from the two catalogs."""
    entries = catalog("street-name").entries
    hierarchies = catalog("street-hierarchy").keys()
    return {
        hierarchy: frozenset(
            item.key
            for item in entries
            if hierarchy in entry("street-name", item.key)["hierarchies"]
        )
        for hierarchy in hierarchies
    }


def _shortfall(
    wanted: Mapping[str, int], span_x_mm: int, span_y_mm: int, length: int, depth: int
) -> str | None:
    """Why no naming of these streets could exist, or ``None`` when one can.

    HALL'S CONDITION, over the sets of street hierarchies: streets can be given distinct names
    exactly when, for every set of hierarchies, the streets wanting one of them are no more
    numerous than the names suiting one of them. Holding each hierarchy to its own supply alone
    is not enough, because a name suiting two hierarchies is spent on whichever draws it first,
    and it is also too strict in the other direction for the same reason.

    IT ANSWERS ONLY "COULD THIS EVER WORK". A layout it admits can still run the catalog dry
    while drawing, because the draw takes names in street order rather than solving the matching.

    ONLY THE ONE-HIERARCHY CASE CAN FIRE ON A LAYOUT THIS STAGE VERSION LAYS, since it lays one
    high street and makes every other street local, so the larger subsets are a property of this
    function rather than of any world it can be handed. They are here because the demand is
    public and a caller passes its own, and because a version that lays an avenue would reach
    them with nothing to say so. `tests/test_street_name_vocabulary.py` puts the question to the
    function directly for that reason.
    """
    names = street_names_by_hierarchy()
    vocabulary = catalog("street-name")
    present = sorted(wanted)
    for size in range(1, len(present) + 1):
        for subset in combinations(present, size):
            demand = sum(wanted[hierarchy] for hierarchy in subset)
            supply = len(frozenset().union(*(names[hierarchy] for hierarchy in subset)))
            if demand <= supply:
                continue
            return (
                f"city_extent_x_mm and city_extent_y_mm give a district {span_x_mm} by "
                f"{span_y_mm} mm, and with block_length_mm {length} and block_depth_mm {depth} "
                f"it lays {demand} streets needing {' or '.join(subset)} names, above the "
                f"{supply} that {vocabulary.catalog_id} v{vocabulary.catalog_version} holds"
            )
    return None


def _declared(name: str, value: int) -> int:
    """``value``, or a refusal naming the parameter whose declared range it falls outside.

    :func:`street_name_shortfall` is public and pure, so it is reachable with values no cascade
    ever admitted, and `_lay_out` DOES NOT TERMINATE on a spacing of zero: its two candidate
    positions stop moving and one of them stays inside the district for ever. So the guard is
    not tidiness. A caller that resolved the cascade first can never trip it.
    """
    spec = CITY_SURFACE.parameters.get(name)
    if not spec.minimum <= value <= spec.maximum:
        raise InvalidParameterError(
            f"{name} is {value}, outside the {spec.minimum} to {spec.maximum} it declares"
        )
    return value


def street_name_shortfall(
    *, span_x_mm: int, span_y_mm: int, block_length_mm: int, block_depth_mm: int
) -> str | None:
    """``None`` when a distinct name for every street could exist, else the sentence saying why not.

    PURE: no seed, no context, no records, so a caller can ask before it generates anything and
    before it charges for anything. The sentence it returns IS the refusal, written once here,
    in the module that knows the rule, so a caller need not compose one of its own.

    IT ASSUMES THE WIDEST STREET THE DECLARED RANGES ADMIT, which lays the FEWEST streets, so a
    caller passing values a city might take can never be refused a city that would have been
    built. A caller with a derived block length or depth should pass the declared MAXIMUM for the
    same reason: both lay fewer streets as they grow.

    A ``None`` MEANS NO NAMING PROBLEM, NOT A WORLD. This stage refuses a district too small to
    hold a block between four streets, and that refusal is not this one's to make.

    Each value is held to the range its parameter declares and refused by name outside it: the
    spans against ``city_extent_x_mm`` and ``city_extent_y_mm``, which are what decide a
    district's size in this version.
    """
    _declared("city_extent_x_mm", span_x_mm)
    _declared("city_extent_y_mm", span_y_mm)
    _declared("block_length_mm", block_length_mm)
    _declared("block_depth_mm", block_depth_mm)
    reach = widest_reach(_LOCAL)
    wanted = street_name_demand(span_x_mm, span_y_mm, block_length_mm, block_depth_mm, reach)
    return _shortfall(wanted, span_x_mm, span_y_mm, block_length_mm, block_depth_mm)


@dataclass(slots=True)
class _Street:
    ordinal: int
    axis: tuple[int, int]
    position: int
    hierarchy: str
    carriageway_mm: int = 0
    lanes: int = 0
    nodes: list[int] = field(default_factory=list)
    identity: str = ""
    name: str = ""


@dataclass(slots=True)
class _Segment:
    ordinal: int
    street: _Street
    start: int
    end: int
    identity: str = ""


@dataclass(slots=True)
class _Face:
    ordinal: int
    edges: list[tuple[_Segment, str]]
    closed: bool
    block_ordinal: int | None
    kerb_height_mm: int = 0
    kerb_width_mm: int = 0
    footway_width_mm: int = 0
    crossfall_millionths: int = 0
    radius_mm: int = 0


def _point(street: _Street, along: int, lateral: int) -> tuple[int, int]:
    """A point at ``along`` on the street's axis, ``lateral`` to the left of its direction."""
    if street.axis == _EAST:
        return along, street.position + lateral
    return street.position - lateral, along


def _node_point(street: _Street, along: int) -> tuple[int, int]:
    return _point(street, along, 0)


def _lay_out(
    low: int, high: int, middle: int, spacing: int, reach: int, centred: bool
) -> list[int]:
    """Street positions ``spacing`` apart about ``middle``, each ``reach`` clear of the edges."""
    offset = 0 if centred else spacing // 2
    positions = []
    step = 0
    while True:
        below = middle - offset - step * spacing
        above = middle + (spacing - offset if not centred else 0) + step * spacing
        placed = False
        for position in {below, above}:
            if low + reach <= position <= high - reach:
                positions.append(position)
                placed = True
        if not placed and below - reach < low and above + reach > high:
            break
        step += 1
    return sorted(set(positions))


def _faces(
    along: list[_Street], across: list[_Street], segments: dict[tuple[int, int], _Segment]
) -> list[_Face]:
    """Every face of the lattice, each with its edges in counter-clockwise walk order."""

    def segment(street: _Street, start: int) -> _Segment:
        return segments[(street.ordinal, start)]

    faces: list[_Face] = []
    south, north = along[0], along[-1]
    faces.append(
        _Face(
            len(faces),
            [(segment(south, start), "right") for start in reversed(south.nodes[:-1])],
            closed=False,
            block_ordinal=None,
        )
    )
    faces.append(
        _Face(
            len(faces),
            [(segment(north, start), "left") for start in north.nodes[:-1]],
            closed=False,
            block_ordinal=None,
        )
    )
    blocks = 0
    for row in range(len(along) - 1):
        low, high = along[row], along[row + 1]
        columns = [None, *across, None]
        for column in range(len(columns) - 1):
            west, east = columns[column], columns[column + 1]
            x_low = west.position if west is not None else low.nodes[0]
            edges: list[tuple[_Segment, str]] = [(segment(low, x_low), "left")]
            if east is not None:
                edges.append((segment(east, low.position), "left"))
            edges.append((segment(high, x_low), "right"))
            if west is not None:
                edges.append((segment(west, low.position), "right"))
            closed = west is not None and east is not None
            block = None
            if closed:
                block = blocks
                blocks += 1
            elif east is None:
                # Open to the east, the walk starts on the north street, where the district's
                # edge is behind it, and ends on the south street at the edge.
                edges = [edges[1], edges[2], edges[0]]
            faces.append(_Face(len(faces), edges, closed, block))
    return faces


def _generate(context: StageContext) -> Iterator[object]:
    [district] = prior_records(context, districts.STAGE_ID, districts.DistrictRecord)
    patches = prior_records(context, terrain.STAGE_ID, terrain.TerrainRecord)
    if any(set(patch.height_mm) != {DATUM_MM} for patch in patches):
        raise InvalidRecordError("this streets stage version lays streets on level ground only")
    ring = district.boundary_mm
    min_x, min_y = min(x for x, _y in ring), min(y for _x, y in ring)
    max_x, max_y = max(x for x, _y in ring), max(y for _x, y in ring)
    if len(ring) != 4 or {(min_x, min_y), (max_x, min_y), (max_x, max_y), (min_x, max_y)} != set(
        ring
    ):
        raise InvalidRecordError("this streets stage version lays out a rectangular district only")

    length = derived(context, "block_length_mm", _DISTRICT)
    depth = derived(context, "block_depth_mm", _DISTRICT)
    if "gutter_width_mm" not in context.parameters:
        raise InvalidParameterError(
            "gutter_width_mm is block level, and one gutter width runs along a whole street; this "
            "streets stage version reads it bound for the district or the city"
        )
    gutter = _modular(context, "gutter_width_mm", _DISTRICT, 0, 1_000_000)
    lane_low, lane_high = _ranges((_HIGH, _LOCAL), "lane_width_minimum_mm", "lane_width_maximum_mm")
    lane_width = _modular(context, "lane_width_mm", _DISTRICT, lane_low, lane_high)
    if lane_width % 2:
        raise InvalidParameterError(
            "a lane width is even, so a lane's centre is a whole millimetre"
        )
    camber = derived(context, "camber_millionths", _DISTRICT)
    speed_low, speed_high = _ranges(
        (_HIGH, _LOCAL), "speed_limit_minimum_mm_s", "speed_limit_maximum_mm_s"
    )
    speed = derived(context, "speed_limit_mm_s", _DISTRICT, minimum=speed_low, maximum=speed_high)

    def section(hierarchy: str) -> tuple[int, int, int]:
        return _section(hierarchy, lane_width, gutter)

    middle_x, middle_y = (min_x + max_x) // 2, (min_y + max_y) // 2
    _lanes, _width, local_reach = section(_LOCAL)
    along_positions = _lay_out(min_y, max_y, middle_y, depth, local_reach, centred=True)  # type: ignore[arg-type]
    if middle_y not in along_positions:
        raise InvalidRecordError("the high street through the district's middle does not fit it")
    across_positions = _lay_out(min_x, max_x, middle_x, length, local_reach, centred=False)  # type: ignore[arg-type]
    if len(along_positions) < 2 or not across_positions:
        raise InvalidRecordError("the district is too small for a block between four streets")

    hierarchies = street_hierarchies(along_positions, across_positions, middle_y)
    # BEFORE ANY RECORD EXISTS, and on the hierarchies this layout actually lays rather than on
    # the widest-street estimate `street_name_shortfall` gives a caller, so it refuses exactly
    # the cities no naming could serve.
    shortfall = _shortfall(Counter(hierarchies), max_x - min_x, max_y - min_y, length, depth)
    if shortfall is not None:
        raise InvalidParameterError(shortfall)
    along = [
        _Street(index, _EAST, position, hierarchies[index])
        for index, position in enumerate(along_positions)
    ]
    across = [
        _Street(len(along) + index, _NORTH, position, hierarchies[len(along) + index])
        for index, position in enumerate(across_positions)
    ]
    for street in along:
        street.nodes = [min_x, *across_positions, max_x]
    for street in across:
        street.nodes = list(along_positions)
    every_street = [*along, *across]
    names_left: dict[str, list[str]] = {}
    for street in every_street:
        street.lanes, street.carriageway_mm, _reach = section(street.hierarchy)
        street.identity = context.identity("street", context.subject_identity, street.ordinal)
        options = names_left.setdefault(
            street.hierarchy,
            sorted(
                item.key
                for item in catalog("street-name").entries
                if street.hierarchy in entry("street-name", item.key)["hierarchies"]
            ),
        )
        taken = {other.name for other in every_street if other.name}
        options = [name for name in options if name not in taken]
        if not options:
            # The refusal above says no naming could exist; this one says the draw did not find
            # the one that does, because it takes names in street order rather than solving the
            # matching. It names the same parameters, so a caller meets something to act on.
            vocabulary = catalog("street-name")
            raise InvalidParameterError(
                f"street {street.ordinal} of {len(every_street)} needs a {street.hierarchy} "
                f"name and every one {vocabulary.catalog_id} v{vocabulary.catalog_version} "
                f"holds is taken; block_length_mm {length} and block_depth_mm {depth} over a "
                f"{max_x - min_x} by {max_y - min_y} mm district lay "
                f"{sum(1 for other in every_street if other.hierarchy == street.hierarchy)} "
                f"streets needing one"
            )
        street.name = options[draw(context, "street_name", street.ordinal, 0, len(options) - 1)]

    node_ids: dict[tuple[int, int], str] = {}
    node_records = []
    for y in along_positions:
        for x in [min_x, *across_positions, max_x]:
            ordinal = len(node_records)
            identity = context.identity("street_node", context.subject_identity, ordinal)
            node_ids[(x, y)] = identity
            node_records.append(
                streets.StreetNodeRecord(
                    identity, ordinal, x, y, DATUM_MM, Extent(x, y, DATUM_MM, x, y, DATUM_MM)
                )
            )

    segments: dict[tuple[int, int], _Segment] = {}
    for street in every_street:
        for start, end in zip(street.nodes, street.nodes[1:], strict=False):
            item = _Segment(len(segments), street, start, end)
            item.identity = context.identity(
                "street_segment", context.subject_identity, item.ordinal
            )
            segments[(street.ordinal, start)] = item

    faces = _faces(along, across, segments)
    for face in faces:
        hierarchies = sorted({segment.street.hierarchy for segment, _side in face.edges})
        ordinal = face.ordinal
        busiest = entry("street-hierarchy", _busiest(hierarchies))
        kerb_low = busiest["kerb_height_minimum_mm"]
        kerb_high = busiest["kerb_height_maximum_mm"]
        face.kerb_height_mm = derived(
            context, "kerb_height_mm", ordinal, minimum=kerb_low, maximum=kerb_high
        )  # type: ignore[assignment]
        face.kerb_width_mm = _modular(context, "kerb_width_mm", ordinal, 0, 1_000_000)
        foot_low = busiest["footway_width_minimum_mm"]
        foot_high = busiest["footway_width_maximum_mm"]
        spare = _room_for_footways(face)
        if spare is not None:
            if spare < foot_low:
                raise InvalidParameterError(
                    f"face {ordinal} has {spare} mm to spare for a footway and its streets ask "
                    f"for at least {foot_low} mm; the block is too shallow for its streets"
                )
            foot_high = min(foot_high, spare)
        face.footway_width_mm = _modular(context, "footway_width_mm", ordinal, foot_low, foot_high)
        face.crossfall_millionths = derived(context, "footway_crossfall_millionths", ordinal)  # type: ignore[assignment]
        face.radius_mm = _modular(
            context, "corner_radius_mm", ordinal, face.kerb_width_mm + 1, 1_000_000
        )

    fall = {
        street.ordinal: (street.carriageway_mm // 2) * camber // MILLIONTHS
        for street in every_street
    }  # type: ignore[operator]

    curb_ids: dict[tuple[int, str], str] = {}
    for item in segments.values():
        for side in ("left", "right"):
            curb_ids[(item.ordinal, side)] = context.identity(
                "curb_edge", item.identity, SIDE_CODES[side]
            )

    # Walk each face: a follower, and whether the join is a corner or a straight join.
    follower: dict[tuple[int, str], tuple[tuple[_Segment, str], bool] | None] = {}
    predecessor: dict[tuple[int, str], tuple[tuple[_Segment, str], bool] | None] = {}
    face_of: dict[tuple[int, str], _Face] = {}
    for face in faces:
        count = len(face.edges)
        for index, (item, side) in enumerate(face.edges):
            key = (item.ordinal, side)
            face_of[key] = face
            if index + 1 < count or face.closed:
                nxt = face.edges[(index + 1) % count]
                turns = nxt[0].street.axis != item.street.axis
                follower[key] = (nxt, turns)
                predecessor[(nxt[0].ordinal, nxt[1])] = ((item, side), turns)
            else:
                follower[key] = None
            predecessor.setdefault(key, None)

    def trim(edge: tuple[tuple[_Segment, str], bool] | None, radius: int) -> int:
        if edge is None or not edge[1]:
            return 0
        return edge[0][0].street.carriageway_mm // 2 + radius

    curbs: dict[tuple[int, str], streets.CurbEdgeRecord] = {}
    for key, face in face_of.items():
        item = next(segment for segment in segments.values() if segment.ordinal == key[0])
        side = key[1]
        street = item.street
        at_walk_end = trim(follower[key], face.radius_mm)
        at_walk_start = trim(predecessor[key], face.radius_mm)
        start_trim, end_trim = (
            (at_walk_start, at_walk_end) if side == "left" else (at_walk_end, at_walk_start)
        )
        lateral = street.carriageway_mm // 2 if side == "left" else -(street.carriageway_mm // 2)
        z = DATUM_MM - fall[street.ordinal]
        first = _point(street, item.start + start_trim, lateral)
        last = _point(street, item.end - end_trim, lateral)
        if item.end - end_trim <= item.start + start_trim:
            raise InvalidRecordError(f"a kerb line of segment {item.ordinal} has no length left")
        block_identity: tuple[str, ...] = ()
        if face.block_ordinal is not None:
            block_identity = (
                context.identity("block", context.subject_identity, face.block_ordinal),
            )
        nxt = follower[key]
        curbs[key] = streets.CurbEdgeRecord(
            identity=curb_ids[key],
            segment_identity=item.identity,
            side=side,
            block_identity=block_identity,
            kerb_line_mm=((*first, z), (*last, z)),
            kerb_height_mm=face.kerb_height_mm,
            kerb_width_mm=face.kerb_width_mm,
            gutter_width_mm=gutter,
            footway_width_mm=face.footway_width_mm,
            footway_crossfall_millionths=face.crossfall_millionths,
            next_curb_identity=() if nxt is None else (curb_ids[(nxt[0][0].ordinal, nxt[0][1])],),
            corner_radius_mm=face.radius_mm if nxt is not None and nxt[1] else 0,
            extent=Extent(0, 0, 0, 0, 0, 0),
        )
    for key, curb in list(curbs.items()):
        extent = strip_box(curb)
        for next_identity in curb.next_curb_identity:
            other = next(record for record in curbs.values() if record.identity == next_identity)
            box = corner_box(curb, other)
            if box is not None:
                extent = covering(extent, box)
        curbs[key] = dataclasses.replace(curb, extent=extent)

    blocks = []
    for face in faces:
        if face.block_ordinal is None:
            continue
        reach = face.kerb_width_mm + face.footway_width_mm
        (south, _), (east, _), (north, _), (west, _) = face.edges
        west_x = west.street.position + west.street.carriageway_mm // 2 + reach
        east_x = east.street.position - east.street.carriageway_mm // 2 - reach
        south_y = south.street.position + south.street.carriageway_mm // 2 + reach
        north_y = north.street.position - north.street.carriageway_mm // 2 - reach
        block_ring = ((west_x, south_y), (east_x, south_y), (east_x, north_y), (west_x, north_y))
        grade = max(
            DATUM_MM
            - fall[segment.street.ordinal]
            + face.kerb_height_mm
            + footway_rise_mm(curbs[(segment.ordinal, side)])
            for segment, side in face.edges
        )
        blocks.append(
            streets.BlockRecord(
                identity=context.identity("block", context.subject_identity, face.block_ordinal),
                block_ordinal=face.block_ordinal,
                district_identity=district.identity,
                boundary_mm=block_ring,
                centroid_x_mm=ring_centroid(block_ring)[0],
                centroid_y_mm=ring_centroid(block_ring)[1],
                grade_elevation_mm=grade,
                extent=Extent(west_x, south_y, grade, east_x, north_y, grade),
            )
        )

    lane_records = []
    segment_records = {}
    driving = district.driving_side
    for item in sorted(segments.values(), key=lambda value: value.ordinal):
        street = item.street
        left, right = curbs[(item.ordinal, "left")], curbs[(item.ordinal, "right")]
        axis_index = 0 if street.axis == _EAST else 1
        starts = [left.kerb_line_mm[0][axis_index], right.kerb_line_mm[0][axis_index]]
        ends = [left.kerb_line_mm[-1][axis_index], right.kerb_line_mm[-1][axis_index]]
        strip_start, strip_end = max(starts), min(ends)
        half = street.lanes // 2
        lanes = []
        for index in range(street.lanes):
            lateral = street.carriageway_mm // 2 - gutter - lane_width // 2 - index * lane_width
            z = DATUM_MM - abs(lateral) * camber // MILLIONTHS  # type: ignore[operator]
            forward = (index >= half) == (driving == "right")
            begin, finish = _point(street, strip_start, lateral), _point(street, strip_end, lateral)
            line = ((*begin, z), (*finish, z)) if forward else ((*finish, z), (*begin, z))
            end_node = item.end if forward else item.start
            turns = _turns(street, end_node, forward, along, across, min_x, max_x)
            offsets = (strip_start - item.start, strip_end - item.start)
            low_lateral, high_lateral = lateral - lane_width // 2, lateral + lane_width // 2
            corners = [
                _point(street, strip_start, low_lateral),
                _point(street, strip_end, high_lateral),
            ]
            lanes.append(
                roads.LaneRecord(
                    identity=context.identity("lane", item.identity, index),
                    segment_identity=item.identity,
                    lane_index=index,
                    lane_use="general",
                    direction="forward" if forward else "backward",
                    width_mm=lane_width,
                    centreline_mm=line,
                    start_offset_mm=offsets[0] if forward else offsets[1],
                    end_offset_mm=offsets[1] if forward else offsets[0],
                    turns=turns,
                    left_marking="none",
                    right_marking="none",
                    extent=Extent(
                        min(point[0] for point in corners),
                        min(point[1] for point in corners),
                        z,
                        max(point[0] for point in corners),
                        max(point[1] for point in corners),
                        z,
                    ),
                )
            )
        lane_records += lanes
        start_point, end_point = _node_point(street, item.start), _node_point(street, item.end)
        centreline = ((*start_point, DATUM_MM), (*end_point, DATUM_MM))
        segment_records[item.ordinal] = streets.StreetSegmentRecord(
            identity=item.identity,
            segment_ordinal=item.ordinal,
            street_identity=street.identity,
            district_identity=district.identity,
            start_node_identity=node_ids[start_point],
            end_node_identity=node_ids[end_point],
            centreline_mm=centreline,
            length_mm=polyline_run_length(centreline),
            hierarchy=street.hierarchy,
            carriageway_width_mm=street.carriageway_mm,
            camber_millionths=camber,  # type: ignore[arg-type]
            speed_limit_mm_s=speed,  # type: ignore[arg-type]
            extent=covering(
                Extent(*start_point, DATUM_MM, *end_point, DATUM_MM)
                if start_point <= end_point
                else Extent(*end_point, DATUM_MM, *start_point, DATUM_MM),
                left.extent,
                right.extent,
                *(lane.extent for lane in lanes),
            ),
        )

    street_records = []
    for street in every_street:
        members = [
            segment_records[item.ordinal] for item in segments.values() if item.street is street
        ]
        street_records.append(
            streets.StreetRecord(
                identity=street.identity,
                street_ordinal=street.ordinal,
                name=street.name,
                name_text=entry("street-name", street.name)["text"],
                segment_identities=tuple(record.identity for record in members),
                extent=covering(*(record.extent for record in members)),
            )
        )

    junctions, approaches = _junctions(
        context,
        node_records,
        list(segment_records.values()),
        curbs,
        along,
        every_street,
        segments,
        lane_records,
    )
    crossings = _crossings(
        context,
        node_records,
        list(segment_records.values()),
        curbs,
        segments,
        _modular(context, "crossing_width_mm", _DISTRICT, 0, 1_000_000),
        derived(context, "dropped_kerb_upstand_mm", _DISTRICT),  # type: ignore[arg-type]
        camber,  # type: ignore[arg-type]
    )

    yield from node_records
    yield from street_records
    yield from (segment_records[ordinal] for ordinal in sorted(segment_records))
    yield from blocks
    yield from curbs.values()
    yield from crossings
    yield from lane_records
    yield from junctions
    yield from approaches


def _turns(
    street: _Street,
    node: int,
    forward: bool,
    along: list[_Street],
    across: list[_Street],
    min_x: int,
    max_x: int,
) -> tuple[str, ...]:
    """The movements a lane may make where it ends: the legs present at its end node.

    At the district's edge the street runs on beyond what was generated, so its lanes carry
    straight on.
    """
    if street.axis == _EAST:
        if node in (min_x, max_x):
            return ("straight",)
        crossing = next(item for item in across if item.position == node)
        straight = True
        north_leg = street.position < crossing.nodes[-1]
        south_leg = street.position > crossing.nodes[0]
        heading_east = forward
        left, right = (north_leg, south_leg) if heading_east else (south_leg, north_leg)
    else:
        heading_north = forward
        at_edge = node in (along[0].position, along[-1].position)
        straight = not at_edge
        west_leg = east_leg = True
        left, right = (west_leg, east_leg) if heading_north else (east_leg, west_leg)
    movements = []
    if left:
        movements.append("left")
    if straight:
        movements.append("straight")
    if right:
        movements.append("right")
    return tuple(movements)


def _quadrant(record: streets.StreetSegmentRecord, node: streets.StreetNodeRecord) -> int:
    """A leg's place counter-clockwise from +x, by its first piece away from the node."""
    line = record.centreline_mm
    far = line[1] if record.start_node_identity == node.identity else line[-2]
    dx, dy = far[0] - node.x_mm, far[1] - node.y_mm
    return {(1, 0): 0, (0, 1): 1, (-1, 0): 2, (0, -1): 3}[
        ((dx > 0) - (dx < 0), (dy > 0) - (dy < 0))
    ]


def _crossings(
    context: StageContext,
    nodes: list[streets.StreetNodeRecord],
    segment_records: list[streets.StreetSegmentRecord],
    curbs: dict[tuple[int, str], streets.CurbEdgeRecord],
    segments: dict[tuple[int, int], _Segment],
    width: int,
    upstand: int,
    camber: int,
) -> list[streets.CrossingRecord]:
    """A crossing on every leg of every junction, at the near end of its straight kerb run.

    A crossing meets a dropped kerb on both sides, so it stands where the kerb is straight, clear
    of the corner arcs: its outer edge is where the straight run begins. A leg whose straight run
    is shorter than two crossings carries one, at the end nearer its start node, rather than two
    that overlap. Every junction leg has one, so a person walking this city can always cross.

    The type is ``zebra``: dropped kerbs, zebra marking, no signal. A signalised crossing names a
    plan in traffic's catalog, which the city grammar does not read, so no crossing here is
    signalised.
    """
    by_ordinal = {item.identity: item for item in segments.values()}
    curbs_by_segment: dict[str, dict[str, streets.CurbEdgeRecord]] = {}
    for curb in curbs.values():
        curbs_by_segment.setdefault(curb.segment_identity, {})[curb.side] = curb
    junction_nodes = {
        node.identity
        for node in nodes
        if sum(
            node.identity in (record.start_node_identity, record.end_node_identity)
            for record in segment_records
        )
        >= 3
    }
    records = []
    for record in segment_records:
        item = by_ordinal[record.identity]
        street = item.street
        sides = curbs_by_segment.get(record.identity)
        if sides is None or len(sides) != 2:
            continue
        axis_index = 0 if street.axis == _EAST else 1
        left, right = sides["left"], sides["right"]
        strip_start = max(left.kerb_line_mm[0][axis_index], right.kerb_line_mm[0][axis_index])
        strip_end = min(left.kerb_line_mm[-1][axis_index], right.kerb_line_mm[-1][axis_index])
        run = strip_end - strip_start
        if run < width:
            continue
        wanted = []
        if record.start_node_identity in junction_nodes:
            wanted.append(strip_start + width // 2)
        if record.end_node_identity in junction_nodes and (run >= 2 * width or not wanted):
            wanted.append(strip_end - width // 2)
        half = street.carriageway_mm // 2
        fall = half * camber // MILLIONTHS
        for ordinal, along in enumerate(sorted(wanted)):
            near = _point(street, along, half)
            far = _point(street, along, -half)
            z = DATUM_MM - fall
            xs = [near[0], far[0]]
            ys = [near[1], far[1]]
            # The band's thickness runs along the street; its length runs across it.
            if street.axis == _EAST:
                xs = [x - width // 2 for x in xs] + [x + width // 2 for x in xs]
            else:
                ys = [y - width // 2 for y in ys] + [y + width // 2 for y in ys]
            records.append(
                streets.CrossingRecord(
                    identity=context.identity("crossing", record.identity, ordinal),
                    segment_identity=record.identity,
                    crossing_ordinal=ordinal,
                    crossing_type="zebra",
                    offset_mm=abs(along - item.start),
                    width_mm=width,
                    line_mm=((*near, z), (*far, z)),
                    kerb_upstand_mm=upstand,
                    signal_identity=(),
                    extent=Extent(min(xs), min(ys), z, max(xs), max(ys), DATUM_MM),
                )
            )
    return records


def _junctions(
    context: StageContext,
    nodes: list[streets.StreetNodeRecord],
    segment_records: list[streets.StreetSegmentRecord],
    curbs: dict[tuple[int, str], streets.CurbEdgeRecord],
    along: list[_Street],
    every_street: list[_Street],
    segments: dict[tuple[int, int], _Segment],
    lanes: list[roads.LaneRecord],
) -> tuple[list[roads.JunctionRecord], list[roads.JunctionApproachRecord]]:
    street_of = {item.identity: item.street for item in segments.values()}
    curbs_by_segment: dict[str, dict[str, streets.CurbEdgeRecord]] = {}
    for curb in curbs.values():
        curbs_by_segment.setdefault(curb.segment_identity, {})[curb.side] = curb
    carried = {curb.identity: curb for curb in curbs.values()}
    high = next(street for street in along if street.hierarchy == _HIGH)
    junctions, approaches = [], []
    for node in nodes:
        legs = [
            record
            for record in segment_records
            if node.identity in (record.start_node_identity, record.end_node_identity)
        ]
        if len(legs) < 3:
            continue

        legs.sort(key=lambda record, node=node: _quadrant(record, node))
        identity = context.identity("junction", node.identity, 0)
        box = junction_fill_box(node, legs, lambda segment: curbs_by_segment[segment], carried.get)
        if box is None:
            raise InvalidRecordError(
                f"junction at node {node.node_ordinal} has a leg without curbs"
            )
        junctions.append(
            roads.JunctionRecord(
                identity=identity,
                node_identity=node.identity,
                control="priority_two_way_stop",
                segment_identities=tuple(record.identity for record in legs),
                signal_identity=(),
                extent=box,
            )
        )
        streets_here = {
            street_of[record.identity].ordinal: street_of[record.identity] for record in legs
        }
        on_high = high.ordinal in streets_here
        for ordinal, record in enumerate(legs):
            street = street_of[record.identity]
            count = sum(1 for leg in legs if street_of[leg.identity] is street)
            major = street is high if on_high else count == 2
            approaches.append(
                roads.JunctionApproachRecord(
                    identity=context.identity("junction_approach", identity, ordinal),
                    junction_identity=identity,
                    segment_identity=record.identity,
                    approach_ordinal=ordinal,
                    control="priority" if major else "stop",
                    priority_rank=0 if major else 1,
                    turning_radius_mm=max(
                        entry("lane-use", use)["turning_radius_mm"]
                        for use in sorted(
                            {
                                lane.lane_use
                                for lane in lanes
                                if lane.segment_identity == record.identity
                            }
                        )
                    ),
                )
            )
    return junctions, approaches


STAGE: Final = GeneratorStage(
    streets.STAGE_ID,
    streets.STAGE_VERSION,
    (
        streets.NODE_SHAPE,
        streets.STREET_SHAPE,
        streets.SEGMENT_SHAPE,
        streets.BLOCK_SHAPE,
        streets.CURB_SHAPE,
        streets.CROSSING_SHAPE,
        *roads.SHAPES,
    ),
    _generate,
)
