"""Deterministic compiler for the bounded Flatiron owned-world district."""

from __future__ import annotations

import hashlib
import json
import math
import uuid
from dataclasses import dataclass
from decimal import ROUND_HALF_EVEN, Decimal
from pathlib import Path
from typing import Any, Final
from urllib.parse import urlencode
from urllib.request import Request, urlopen

from exulanica.canonical import canonical_json

PROFILE: Final = "exulanica.owned-district/v1"
GENERATOR: Final = "flatiron-district-compiler/1"
PLACE_ID: Final = "d08f61bb-ef6d-4f5d-8bd8-a596da51f971"
ADMISSION_NAMESPACE: Final = uuid.UUID("7e79ce7d-8efc-478b-95c3-bdfc7bb4592d")
COORDINATE_SCALE: Final = 100
BOUNDS: Final = (-73.994, 40.739, -73.986, 40.745)
ORIGIN: Final = (-73.99, 40.742)
BUILDING_DATASET: Final = "5zhs-2jue"
SIDEWALK_DATASET: Final = "52n9-sdep"
TERMS_URL: Final = "https://cityofnewyork.github.io/opendatatsm/publicpolicies.html"
ATTRIBUTION: Final = "NYC Open Data, Office of Technology and Innovation (OTI)"
MODIFICATION_NOTICE: Final = (
    "Coordinates transformed to a local metric frame. Building massing, facade completion, "
    "materials, roads, lighting, fantasy additions, and inhabitants are generated by Exulanica."
)
RIGHTS: Final = {
    "display": True,
    "extract": True,
    "index": True,
    "persist": True,
    "modify": True,
    "compose": True,
    "export": True,
    "model_processing": True,
}

_BUILDING_FIELDS = (
    "the_geom,name,bin,doitt_id,base_bbl,construction_year,feature_code,geom_source,"
    "ground_elevation,height_roof,last_edited_date,last_status_type"
)
_SIDEWALK_FIELDS = "the_geom,source_id,sub_code,feat_code,status"


@dataclass(frozen=True, slots=True)
class DownloadedLayer:
    dataset_id: str
    data: bytes
    source_url: str
    provider_revision: str


@dataclass(frozen=True, slots=True)
class CompiledDistrict:
    data: bytes
    manifest: bytes
    admission_plan: bytes
    buildings: int
    sidewalks: int


def _query(dataset_id: str, fields: str, order: str) -> str:
    west, south, east, north = BOUNDS
    parameters = (
        ("$select", fields),
        ("$where", f"within_box(the_geom,{north},{west},{south},{east})"),
        ("$order", order),
        ("$limit", "1000"),
    )
    return f"https://data.cityofnewyork.us/resource/{dataset_id}.geojson?{urlencode(parameters)}"


def download_layer(dataset_id: str, *, timeout_seconds: int = 45) -> DownloadedLayer:
    """Download one public bounded source without credentials."""
    if dataset_id == BUILDING_DATASET:
        url = _query(dataset_id, _BUILDING_FIELDS, "doitt_id")
    elif dataset_id == SIDEWALK_DATASET:
        url = _query(dataset_id, _SIDEWALK_FIELDS, "source_id")
    else:
        raise ValueError("unsupported owned-district dataset")
    request = Request(
        url,
        headers={"Accept": "application/vnd.geo+json", "User-Agent": f"{GENERATOR}"},
    )
    with urlopen(request, timeout=timeout_seconds) as response:
        data = response.read(16 * 1024 * 1024)
        revision = response.headers.get("x-soda2-truth-last-modified", "")
    if not revision:
        metadata_url = f"https://data.cityofnewyork.us/api/views/{dataset_id}"
        metadata_request = Request(metadata_url, headers={"User-Agent": GENERATOR})
        with urlopen(metadata_request, timeout=timeout_seconds) as response:
            metadata = json.load(response)
        revision = str(metadata.get("rowsUpdatedAt", "unknown"))
    return DownloadedLayer(dataset_id, data, url, revision)


def _document(data: bytes) -> dict[str, Any]:
    value = json.loads(data, parse_float=Decimal, parse_int=Decimal)
    if (
        not isinstance(value, dict)
        or value.get("type") != "FeatureCollection"
        or not isinstance(value.get("features"), list)
        or len(value["features"]) > 1000
    ):
        raise ValueError("source must be a bounded GeoJSON FeatureCollection")
    return value


def _local_point(point: list[Any]) -> list[int]:
    if len(point) < 2:
        raise ValueError("source coordinate must contain longitude and latitude")
    longitude = Decimal(point[0])
    latitude = Decimal(point[1])
    metres_per_lon = Decimal(str(111_320 * math.cos(math.radians(ORIGIN[1]))))
    metres_per_lat = Decimal("110540")
    x = (longitude - Decimal(str(ORIGIN[0]))) * metres_per_lon
    z = (Decimal(str(ORIGIN[1])) - latitude) * metres_per_lat
    return [
        int((x * COORDINATE_SCALE).quantize(Decimal(1), rounding=ROUND_HALF_EVEN)),
        int((z * COORDINATE_SCALE).quantize(Decimal(1), rounding=ROUND_HALF_EVEN)),
    ]


def _polygons(geometry: dict[str, Any]) -> list[list[list[list[int]]]]:
    kind = geometry.get("type")
    coordinates = geometry.get("coordinates")
    if kind == "Polygon":
        source = [coordinates]
    elif kind == "MultiPolygon":
        source = coordinates
    else:
        raise ValueError("owned district accepts Polygon and MultiPolygon only")
    result: list[list[list[list[int]]]] = []
    for polygon in source:
        rings: list[list[list[int]]] = []
        for ring in polygon:
            points = [_local_point(point) for point in ring]
            if len(points) < 4 or points[0] != points[-1]:
                raise ValueError("source polygon rings must be explicitly closed")
            rings.append(points)
        result.append(rings)
    return result


def _height_cm(value: Any) -> int:
    if value in (None, ""):
        return 900
    feet = Decimal(str(value))
    if feet <= 0:
        return 450
    return max(300, min(24_000, int((feet * Decimal("30.48")).quantize(Decimal(1)))))


def _bbox(polygons: list[list[list[list[int]]]]) -> list[int]:
    points = [point for polygon in polygons for ring in polygon for point in ring]
    return [
        min(point[0] for point in points),
        min(point[1] for point in points),
        max(point[0] for point in points),
        max(point[1] for point in points),
    ]


def _buildings(document: dict[str, Any]) -> list[dict[str, Any]]:
    result = []
    seen: set[str] = set()
    for feature in document["features"]:
        properties = feature.get("properties")
        if not isinstance(properties, dict):
            raise ValueError("building properties are required")
        identity = str(properties.get("doitt_id", ""))
        if not identity.isdigit() or int(identity) <= 0 or identity in seen:
            raise ValueError("DOITT_ID must be a unique positive integer")
        seen.add(identity)
        polygons = _polygons(feature["geometry"])
        result.append(
            {
                "id": f"doitt_id:{identity}",
                "bin": properties.get("bin"),
                "name": properties.get("name"),
                "construction_year": properties.get("construction_year"),
                "height_cm": _height_cm(properties.get("height_roof")),
                "polygons": polygons,
                "bbox_cm": _bbox(polygons),
                "material": int(identity) % 7,
            }
        )
    ordered = sorted(result, key=lambda item: item["id"])
    return [{**item, "render_batch_id": index} for index, item in enumerate(ordered)]


def _sidewalks(document: dict[str, Any]) -> list[dict[str, Any]]:
    result = []
    seen: set[str] = set()
    for feature in document["features"]:
        properties = feature.get("properties", {})
        polygons = _polygons(feature["geometry"])
        identity = hashlib.sha256(canonical_json(polygons)).hexdigest()
        if identity in seen:
            raise ValueError("duplicate canonical sidewalk geometry")
        seen.add(identity)
        result.append(
            {
                "id": f"sidewalk_geometry_sha256:{identity}",
                "source_id": properties.get("source_id"),
                "status": properties.get("status"),
                "polygons": polygons,
                "bbox_cm": _bbox(polygons),
            }
        )
    return sorted(result, key=lambda item: item["id"])


def compile_district(
    building: DownloadedLayer,
    sidewalk: DownloadedLayer,
    *,
    seed: int = 24051902,
) -> CompiledDistrict:
    """Compile exact source bytes into one engine-neutral canonical artifact."""
    if building.dataset_id != BUILDING_DATASET or sidewalk.dataset_id != SIDEWALK_DATASET:
        raise ValueError("district layers use the wrong dataset identity")
    buildings = _buildings(_document(building.data))
    sidewalks = _sidewalks(_document(sidewalk.data))
    source_records = [
        {
            "dataset_id": layer.dataset_id,
            "provider_revision": layer.provider_revision,
            "source_url": (
                _query(BUILDING_DATASET, _BUILDING_FIELDS, "doitt_id")
                if layer.dataset_id == BUILDING_DATASET
                else _query(SIDEWALK_DATASET, _SIDEWALK_FIELDS, "source_id")
            ),
            "sha256": hashlib.sha256(layer.data).hexdigest(),
            "byte_size": len(layer.data),
            "attribution": ATTRIBUTION,
            "terms_url": TERMS_URL,
            "operation_rights": RIGHTS,
        }
        for layer in (building, sidewalk)
    ]
    document = {
        "profile": PROFILE,
        "district_id": "nyc-flatiron-owned-v1",
        "name": "Flatiron and Madison Square",
        "seed": seed,
        "generator": GENERATOR,
        "source_records": source_records,
        "derivation": {
            "input_sha256": [record["sha256"] for record in source_records],
            "method": GENERATOR,
            "modification_notice": MODIFICATION_NOTICE,
        },
        "frame": {
            "name": "flatiron-local",
            "origin_crs84_e7": [int(ORIGIN[0] * 10_000_000), int(ORIGIN[1] * 10_000_000)],
            "axis_order": ["east", "south"],
            "horizontal_unit": "centimetre",
            "coordinate_scale": COORDINATE_SCALE,
            "altitude_reference": "authored-flat-ground",
        },
        "bounds_crs84_e7": [int(value * 10_000_000) for value in BOUNDS],
        "bounds_cm": [-33_800, -33_200, 33_800, 33_200],
        "ground": {
            "kind": "authored-visible-plane",
            "height_cm": 0,
            "generated": True,
            "safe_stop_margin_cm": 150,
        },
        "road_completion": {
            "kind": "generated-ground-minus-source-sidewalks-and-buildings",
            "generated": True,
        },
        "materials": [
            {"name": "limestone", "base": "#b9af9e", "roughness_milli": 760, "metalness_milli": 20},
            {
                "name": "warm-brick",
                "base": "#8b5544",
                "roughness_milli": 820,
                "metalness_milli": 10,
            },
            {
                "name": "cast-iron",
                "base": "#424b4b",
                "roughness_milli": 500,
                "metalness_milli": 350,
            },
            {"name": "sandstone", "base": "#c79f75", "roughness_milli": 780, "metalness_milli": 10},
            {
                "name": "copper-patina",
                "base": "#4c8178",
                "roughness_milli": 600,
                "metalness_milli": 300,
            },
            {"name": "granite", "base": "#777477", "roughness_milli": 660, "metalness_milli": 50},
            {
                "name": "night-glass",
                "base": "#33404d",
                "roughness_milli": 220,
                "metalness_milli": 120,
            },
        ],
        "buildings": buildings,
        "sidewalks": sidewalks,
        "navigation": {
            "surface": "ground",
            "collision": "building-exterior-rings",
            "eye_height_cm": 162,
            "capsule_radius_cm": 34,
        },
    }
    data = canonical_json(document) + b"\n"
    manifest = {
        "profile": "exulanica.owned-district-manifest/v1",
        "artifact": {
            "path": "flatiron-owned-district.json",
            "sha256": hashlib.sha256(data).hexdigest(),
            "byte_size": len(data),
        },
        "source_records": source_records,
        "counts": {"buildings": len(buildings), "sidewalks": len(sidewalks)},
    }
    admissions = {
        "profile": "exulanica.owned-district-admission-plan/v1",
        "place_id": PLACE_ID,
        "status": "ready_to_admit",
        "sources": [
            {
                "admission_id": str(
                    uuid.uuid5(
                        ADMISSION_NAMESPACE,
                        f"{record['dataset_id']}:{record['provider_revision']}:{record['sha256']}",
                    )
                ),
                "place_id": PLACE_ID,
                "provider_key": "nyc-open-data",
                "provider_original_id": record["dataset_id"],
                "provider_revision": record["provider_revision"],
                "expected_sha256": record["sha256"],
                "expected_byte_size": record["byte_size"],
                "source_path": record["source_url"],
                "local_path": (
                    "source/buildings.geojson"
                    if record["dataset_id"] == BUILDING_DATASET
                    else "source/sidewalks.geojson"
                ),
                "media_type": "application/geo+json",
                "geographic_frame": {
                    "name": "crs84",
                    "crs": "OGC:CRS84",
                    "axis_order": ["longitude", "latitude"],
                    "horizontal_unit": "degree",
                    "vertical_unit": "metre",
                    "orientation": "east-north-up",
                    "altitude_reference": "not_supplied",
                },
                "geographic_bounds": {
                    "kind": "bbox",
                    "frame_name": "crs84",
                    "coordinate_scale": 10_000_000,
                    "coordinates": [int(value * 10_000_000) for value in BOUNDS],
                },
                "operation_rights": RIGHTS,
                "attribution": ATTRIBUTION,
                "modification_notice": MODIFICATION_NOTICE,
            }
            for record in source_records
        ],
    }
    return CompiledDistrict(
        data=data,
        manifest=canonical_json(manifest) + b"\n",
        admission_plan=canonical_json(admissions) + b"\n",
        buildings=len(buildings),
        sidewalks=len(sidewalks),
    )


def write_bundle(
    destination: Path,
    building: DownloadedLayer,
    sidewalk: DownloadedLayer,
    compiled: CompiledDistrict,
) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    source = destination / "source"
    source.mkdir(exist_ok=True)
    (source / "buildings.geojson").write_bytes(building.data)
    (source / "sidewalks.geojson").write_bytes(sidewalk.data)
    (destination / "flatiron-owned-district.json").write_bytes(compiled.data)
    (destination / "manifest.json").write_bytes(compiled.manifest)
    (destination / "admission-plan.json").write_bytes(compiled.admission_plan)
