"""The world kinds the product ships: kind documents under ``assets/catalogs/world-kinds/library``.

Each file is named ``<kind>.v<version>.json`` and is either

* a **world kind** (``exulanica.world-kind/v1``) the site grammar generates, read and held to
  stage A as every kind is (:func:`~exulanica.world.kinds.document.read_kind`); a test holds every
  shipped kind to stage B as well, so the library never offers a kind whose worlds people could not
  live in; or
* an **adapter** (``exulanica.world-kind-adapter/v1``) for a generator that is not the site grammar:
  the town, generated by the city grammar from the world specification's presets and values. The
  adapter names the specification schema and the preset catalog by the SHA-256 of their files and
  copies neither, so the town's values, ranges and presets have one source, and a changed file
  refuses the adapter by name until it is revised; it lists the town's parts in the same words and
  look roles every kind uses, so the interface, the Companion and the style packs read one
  vocabulary. Making a town from the adapter is making it from its preset, through the same gate and
  composer, so no town's receipt or digest depends on the adapter.
"""

from __future__ import annotations

import functools
import hashlib
import json
import re
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final

from exulanica.grammar.documents import read_json
from exulanica.grammar.errors import CatalogError
from exulanica.world.kinds.catalogs import CATALOG_DIRECTORY
from exulanica.world.kinds.document import KindDocument, read_kind

__all__ = [
    "ADAPTER_PROFILE",
    "LIBRARY_DIRECTORY",
    "TownAdapter",
    "shipped_kinds",
    "town_adapter",
]

LIBRARY_DIRECTORY: Final = CATALOG_DIRECTORY / "library"
ADAPTER_PROFILE: Final = "exulanica.world-kind-adapter/v1"
_NAME: Final = re.compile(r"([a-z][a-z0-9_]{0,31})\.v([1-9][0-9]{0,3})\.json")
_RECIPES: Final = Path(__file__).resolve().parents[3] / "assets" / "catalogs" / "world-recipes"


@dataclass(frozen=True, slots=True)
class TownAdapter:
    """The town as a world kind: the city grammar's generator over the world specification."""

    document: Mapping[str, Any]
    sha256: str

    @property
    def kind(self) -> str:
        return str(self.document["kind"])

    @property
    def version(self) -> int:
        return int(self.document["version"])


def _file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _read_adapter(path: Path) -> TownAdapter:
    document = read_json(path)
    if not isinstance(document, dict) or document.get("profile") != ADAPTER_PROFILE:
        raise CatalogError(f"{path.name} is not a world kind adapter")
    for field, stated in (
        ("specification", document["specification"]),
        ("presets", document["presets"]),
    ):
        source = _RECIPES / f"{stated['name']}.json"
        if not source.is_file() or _file_sha256(source) != stated["sha256"]:
            raise CatalogError(
                f"{path.name} names {field} {stated['name']} by a digest its file no longer has; "
                "revise the adapter with the file"
            )
    if (document["generator"]["key"], document["kind"]) != ("city-grammar-town", "town"):
        raise CatalogError(f"{path.name}: the one adapter is the town's")
    canonical = json.dumps(document, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return TownAdapter(document, hashlib.sha256(canonical.encode("utf-8")).hexdigest())


@functools.cache
def _library() -> tuple[tuple[KindDocument, ...], TownAdapter | None]:
    kinds: list[KindDocument] = []
    town: TownAdapter | None = None
    for path in sorted(LIBRARY_DIRECTORY.glob("*.json")):
        named = _NAME.fullmatch(path.name)
        if named is None:
            raise CatalogError(f"{path.name} is not named <kind>.v<version>.json")
        raw = read_json(path)
        if isinstance(raw, dict) and raw.get("profile") == ADAPTER_PROFILE:
            town = _read_adapter(path)
            stated = (town.kind, town.version)
        else:
            kind = read_kind(raw)
            kinds.append(kind)
            stated = (kind.kind, kind.version)
        if stated != (named.group(1), int(named.group(2))):
            raise CatalogError(f"{path.name} states kind {stated[0]} version {stated[1]}")
    return tuple(kinds), town


def shipped_kinds() -> tuple[KindDocument, ...]:
    """Every world kind the product ships, read once, in file order."""
    return _library()[0]


def town_adapter() -> TownAdapter:
    """The town's adapter, refused by name when the library holds none."""
    town = _library()[1]
    if town is None:
        raise CatalogError("the world kind library holds no town adapter")
    return town
