"""The API surface is a reviewed contract: its routes and schema are held to committed snapshots.

``tests/snapshots/api-routes.json`` has one line per mounted route: method, path, endpoint
function, OpenAPI operation id, declared status, response model, request body, the database role
the route is given and its permission rule. ``tests/snapshots/api-openapi.json`` is the document
``/openapi.json`` serves. Both are generated by :mod:`exulanica.api.surface` from the application
itself and written by ``scripts/snapshot_api_surface.py``; nothing here restates a route.

A change that moves any of that fails the first test below until the snapshots are rewritten and
committed with it, so the change reaches review as a diff of the public surface rather than as a
side effect nobody saw. Every check runs without a database.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import MappingProxyType, ModuleType

from exulanica.api import permissions
from exulanica.api.permissions import ROUTE_RULES, Permission, Requires
from exulanica.api.routes import routable_paths
from exulanica.api.surface import render_route_table, route_table, routing_only_application

ROOT = Path(__file__).resolve().parents[1]


def _snapshot_script() -> ModuleType:
    path = ROOT / "scripts" / "snapshot_api_surface.py"
    spec = importlib.util.spec_from_file_location("snapshot_api_surface", path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


SNAPSHOT = _snapshot_script()
APP = routing_only_application()
ROWS = route_table(APP)


def test_the_committed_snapshots_match_the_application():
    found = SNAPSHOT.differences(SNAPSHOT.expected_files())
    assert not found, (
        "The public API surface differs from its committed snapshot. If the change is intended, "
        f"run `{SNAPSHOT.COMMAND}` and commit the rewritten files with it:\n\n" + "\n\n".join(found)
    )


def test_the_table_sees_the_whole_surface_and_names_it():
    """The guard on the guard: a table over nothing, or over the documentation pages, agrees with
    any snapshot of nothing. It must hold every declared route once, and known rows exactly."""
    keys = [(row["method"], row["path"]) for row in ROWS]
    assert len(keys) == len(set(keys))
    assert set(keys) == set(routable_paths(APP)) == set(ROUTE_RULES)
    by_key = dict(zip(keys, ROWS, strict=True))
    assert by_key[("POST", "/world/versions/{version_id}/objects")] == {
        "database_role": "runtime",
        "endpoint": "add_authored_object",
        "method": "POST",
        "operation_id": "add_authored_object_world_versions__version_id__objects_post",
        "path": "/world/versions/{version_id}/objects",
        "permission": {"requires": ["world.write"]},
        "request_body": "AddObjectBody",
        "response_model": "AlternateVersionView",
        "status_code": 201,
    }
    assert by_key[("GET", "/graph")]["database_role"] == "read-only"
    assert by_key[("GET", "/healthz")]["permission"] == {
        "public": ROUTE_RULES[("GET", "/healthz")].reason  # type: ignore[union-attr]
    }


def test_the_table_and_the_schema_describe_the_same_operations_in_the_same_order():
    """The rows are walked from the router and the schema is FastAPI's own walk. Agreeing on every
    operation id and on path order is what shows the walk above is the order routes match in."""
    document = APP.openapi()
    operations = {
        (method.upper(), path): operation["operationId"]
        for path, item in document["paths"].items()
        for method, operation in item.items()
    }
    listed = {
        (row["method"], row["path"]): row["operation_id"]
        for row in ROWS
        if row["operation_id"] is not None
    }
    assert listed == operations
    assert len(set(operations.values())) == len(operations)
    first_seen = list(dict.fromkeys(row["path"] for row in ROWS if row["operation_id"] is not None))
    assert first_seen == list(document["paths"])


def test_a_moved_permission_is_one_changed_line_naming_it(monkeypatch):
    """Positive control: the comparison sees a declaration change, and only that route moves."""
    key = ("GET", "/world/versions")
    monkeypatch.setattr(
        permissions,
        "ROUTE_RULES",
        MappingProxyType({**ROUTE_RULES, key: Requires(frozenset({Permission.LIBRARY_READ}))}),
    )
    committed = SNAPSHOT.ROUTE_TABLE.read_text(encoding="utf-8").splitlines()
    moved = render_route_table(route_table(APP)).splitlines()
    changed = [(old, new) for old, new in zip(committed, moved, strict=True) if old != new]
    assert len(changed) == 1, changed
    assert '"path": "/world/versions"' in changed[0][1]
    assert '"requires": ["library.read"]' in changed[0][1]
