"""The World Write route: what it files, and the two things it refuses.

The tier's own guarantees are ``tests/test_generated_tier.py``. What is checked here is the HTTP
surface: that a generation naming the wrong conditioning is refused rather than stored with a note,
that a malformed or oversized receipt is refused before anything is written, and that a caller who
cannot read a scene learns nothing from trying to write to it.
"""

from __future__ import annotations

import hashlib
import uuid

from exulanica.graph import read_snapshot

from test_api import deployment as deployment
from test_world_read_route import _scene_in

_SEAM = "The shelf continues past the last photograph; everything beyond it is imagined."


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def _body(bundle_sha256: str, **overrides) -> dict:
    body = {
        "model": {"provider": "example-labs", "model_id": "worldgen", "model_version": "2026.09"},
        "prompt_sha256": _sha("continue the shelf"),
        "conditioning": [{"role": "world-read-bundle", "sha256": bundle_sha256}],
        "container": "sog/1",
        "content_sha256": _sha("the generated bytes"),
        "byte_size": 4096,
        "seam": _SEAM,
    }
    body.update(overrides)
    return body


def _recorded(deployment, scene_id) -> str:
    read = deployment.as_owner("GET", f"/world-read/scenes/{scene_id}")
    assert read.status_code == 200, read.text
    return read.json()["bundle"]["recorded_sha256"]


def test_a_generation_is_filed_and_appears_in_the_graph(deployment, repository, tmp_path):
    scene_id = _scene_in(deployment, repository, tmp_path)
    recorded = _recorded(deployment, scene_id)

    response = deployment.as_owner(
        "POST", f"/world-write/scenes/{scene_id}/generated", json=_body(recorded)
    )
    assert response.status_code == 201, response.text
    filed = response.json()
    assert filed["tier"] == "generated"
    assert filed["already_recorded"] is False
    assert filed["world_read_bundle_sha256"] == recorded

    snapshot = read_snapshot(repository.connection, repository.workspace_id, deployment.store)
    scene = next(s for s in snapshot.reconstruction_scenes if str(s.scene_id) == str(scene_id))
    assert [str(entry.artifact_id) for entry in scene.generated_geometry] == [filed["artifact_id"]]
    assert scene.generated_geometry[0].seam == _SEAM
    # And the recorded world is untouched: filing a generation promotes nothing.
    assert scene.recorded_rung == 3


def test_filing_the_identical_receipt_twice_answers_200_and_writes_once(
    deployment, repository, tmp_path
):
    scene_id = _scene_in(deployment, repository, tmp_path)
    body = _body(_recorded(deployment, scene_id))
    first = deployment.as_owner("POST", f"/world-write/scenes/{scene_id}/generated", json=body)
    second = deployment.as_owner("POST", f"/world-write/scenes/{scene_id}/generated", json=body)
    assert first.status_code == 201 and second.status_code == 200
    assert second.json()["already_recorded"] is True
    assert first.json()["artifact_id"] == second.json()["artifact_id"]

    snapshot = read_snapshot(repository.connection, repository.workspace_id, deployment.store)
    scene = next(s for s in snapshot.reconstruction_scenes if str(s.scene_id) == str(scene_id))
    assert len(scene.generated_geometry) == 1


def test_a_generation_naming_the_wrong_conditioning_is_refused(deployment, repository, tmp_path):
    """The one refusal that makes "conditioned on the real place" checkable."""
    scene_id = _scene_in(deployment, repository, tmp_path)
    invented = _sha("a bundle nobody ever produced")
    assert invented != _recorded(deployment, scene_id)

    response = deployment.as_owner(
        "POST", f"/world-write/scenes/{scene_id}/generated", json=_body(invented)
    )
    assert response.status_code == 409, response.text
    assert response.json()["code"] == "conditioning_does_not_verify"

    snapshot = read_snapshot(repository.connection, repository.workspace_id, deployment.store)
    scene = next(s for s in snapshot.reconstruction_scenes if str(s.scene_id) == str(scene_id))
    assert scene.generated_geometry == []


def test_a_receipt_without_a_seam_is_refused_before_anything_is_written(
    deployment, repository, tmp_path
):
    scene_id = _scene_in(deployment, repository, tmp_path)
    recorded = _recorded(deployment, scene_id)
    response = deployment.as_owner(
        "POST",
        f"/world-write/scenes/{scene_id}/generated",
        json=_body(recorded, seam="looks fine"),
    )
    assert response.status_code == 422, response.text
    assert response.json()["code"] == "invalid_generation"

    snapshot = read_snapshot(repository.connection, repository.workspace_id, deployment.store)
    scene = next(s for s in snapshot.reconstruction_scenes if str(s.scene_id) == str(scene_id))
    assert scene.generated_geometry == []


def test_an_oversized_receipt_is_refused_by_the_body_schema(deployment, repository, tmp_path):
    """A receipt is re-parsed on every later read, so its size is a permanent cost."""
    scene_id = _scene_in(deployment, repository, tmp_path)
    recorded = _recorded(deployment, scene_id)

    long_seam = deployment.as_owner(
        "POST",
        f"/world-write/scenes/{scene_id}/generated",
        json=_body(recorded, seam="x" * 5_000),
    )
    assert long_seam.status_code == 422

    many_digests = deployment.as_owner(
        "POST",
        f"/world-write/scenes/{scene_id}/generated",
        json=_body(
            recorded,
            conditioning=[{"role": "world-read-bundle", "sha256": recorded}]
            + [{"role": "point_map", "sha256": _sha(str(index))} for index in range(600)],
        ),
    )
    assert many_digests.status_code == 422


def test_a_stranger_cannot_write_and_learns_nothing_from_trying(deployment, repository, tmp_path):
    """Same 404 the read gives, for the same reason: the surface is not an existence oracle."""
    scene_id = _scene_in(deployment, repository, tmp_path)
    recorded = _recorded(deployment, scene_id)

    real = deployment.as_stranger(
        "POST", f"/world-write/scenes/{scene_id}/generated", json=_body(recorded)
    )
    invented = deployment.as_stranger(
        "POST", f"/world-write/scenes/{uuid.uuid4()}/generated", json=_body(recorded)
    )
    assert real.status_code == 404
    assert real.json() == invented.json()

    snapshot = read_snapshot(repository.connection, repository.workspace_id, deployment.store)
    scene = next(s for s in snapshot.reconstruction_scenes if str(s.scene_id) == str(scene_id))
    assert scene.generated_geometry == []
