"""The generated tier: what it records, and the four things it can never do.

The claim this file defends is narrow and total. Content a world model imagined may be stored,
labelled, and read back with its full provenance, and it may never become evidence, satisfy a
reconstruction gate, promote a rung, or reach a consumer that did not ask for it by name.
"""

from __future__ import annotations

import hashlib
import json
import typing
import uuid

import pytest
from exulanica.errors import EpistemicViolation
from exulanica.graph import read_snapshot
from exulanica.graph.world_read import world_read_bundle
from exulanica.ingest.generated_scene import record_generated_scene
from exulanica.ingest.stages import STAGES, stage
from exulanica.reconstruction.generated import (
    GENERATED_SCENE_KIND,
    GENERATED_SCENE_STAGE,
    ConditioningDigest,
    GeneratedSceneReceipt,
    GenerationModel,
    generation_input_digest,
)
from exulanica.reconstruction.scene_gate import (
    SceneGateInputs,
    SceneReceipt,
    validate_scene_gate_decision,
)

from test_world_read_bundle import _published_scene

_SEAM = "The counter continues past the last photograph; everything beyond it is imagined."


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def _receipt(bundle_sha256: str, **overrides) -> GeneratedSceneReceipt:
    fields = {
        "model": GenerationModel(
            provider="example-labs", model_id="worldgen", model_version="2026.09"
        ),
        "prompt_sha256": _sha("continue the counter"),
        "conditioning": (ConditioningDigest(role="world-read-bundle", sha256=bundle_sha256),),
        "container": "sog/1",
        "content_sha256": _sha("the generated bytes"),
        "byte_size": 4096,
        "seam": _SEAM,
    }
    fields.update(overrides)
    return GeneratedSceneReceipt(**fields)  # type: ignore[arg-type]


@pytest.fixture
def generated(repository, tmp_path):
    """One real scene, and one generation recorded against its current bundle."""
    store, _captures, scene_id = _published_scene(repository, tmp_path, registered=3, spacing=5)
    envelope = world_read_bundle(repository.connection, repository.workspace_id, scene_id, store)
    assert envelope is not None
    receipt = _receipt(envelope["bundle"]["recorded_sha256"])
    record = record_generated_scene(
        repository,
        store,
        scene_id=scene_id,
        receipt=receipt,
        expected_recorded_sha256=envelope["bundle"]["recorded_sha256"],
    )
    assert record.inserted
    return store, scene_id, receipt, record


# -- the stage itself ---------------------------------------------------------------------


def test_the_stage_is_registered_and_declares_itself_non_deterministic():
    spec = stage(GENERATED_SCENE_STAGE)
    assert spec.output_kind == GENERATED_SCENE_KIND
    assert spec.deterministic is False
    assert spec.params["tier"] == "generated"
    assert spec.params["citable"] is False
    assert spec.params["promotes_rung"] is False


def test_the_stage_carries_no_model_role():
    """Deliberate, and pinned so it is not "fixed" later.

    A role names a slot the platform routes through its own reviewed model manifest. The model
    here is supplied per generation. Setting a role would also change the set of model-bearing
    stages that the digest-bound record docs/evaluation/2026-09-05-unblocked-goal-d.json is
    asserted against, and amending a retained record so a new field fits is backwards.
    """
    assert stage(GENERATED_SCENE_STAGE).model_role is None
    roles = sorted(key for key, spec in STAGES.items() if spec.model_role is not None)
    assert roles == ["depth", "vision"]


def test_a_model_swap_produces_a_different_artifact_identity():
    """The scene-subject equivalent of the binding digest, and the reason it exists."""
    bundle = _sha("bundle")
    first = _receipt(bundle)
    same = _receipt(bundle)
    newer = _receipt(
        bundle,
        model=GenerationModel(
            provider="example-labs", model_id="worldgen", model_version="2026.10"
        ),
    )
    other_prompt = _receipt(bundle, prompt_sha256=_sha("a different instruction"))
    other_bundle = _receipt(_sha("a different bundle"))

    assert generation_input_digest(first) == generation_input_digest(same)
    assert generation_input_digest(first) != generation_input_digest(newer)
    assert generation_input_digest(first) != generation_input_digest(other_prompt)
    assert generation_input_digest(first) != generation_input_digest(other_bundle)


def test_a_generation_that_names_no_conditioning_is_refused():
    with pytest.raises(ValueError, match="conditioned on"):
        _receipt(_sha("bundle"), conditioning=())


def test_a_generation_that_names_no_world_read_bundle_is_refused():
    with pytest.raises(ValueError, match="exactly one world-read-bundle"):
        _receipt(
            _sha("bundle"),
            conditioning=(ConditioningDigest(role="point_map", sha256=_sha("a map")),),
        )


def test_a_generation_without_a_seam_is_refused():
    """A generated surface a viewer cannot tell from a photographed one is the whole failure."""
    with pytest.raises(ValueError, match="seam"):
        _receipt(_sha("bundle"), seam="looks fine")


def test_a_container_the_renderer_cannot_validate_is_refused():
    with pytest.raises(ValueError, match="container"):
        _receipt(_sha("bundle"), container="mystery/1")


# -- the write path -----------------------------------------------------------------------


def test_a_generation_naming_the_wrong_bundle_is_refused(repository, tmp_path):
    """The one refusal that makes the conditioning claim checkable rather than asserted."""
    store, _captures, scene_id = _published_scene(repository, tmp_path, registered=3, spacing=5)
    envelope = world_read_bundle(repository.connection, repository.workspace_id, scene_id, store)
    assert envelope is not None
    invented = _sha("a bundle nobody ever produced")
    assert invented != envelope["bundle"]["recorded_sha256"]
    with pytest.raises(EpistemicViolation, match="not this scene's recorded world"):
        record_generated_scene(
            repository,
            store,
            scene_id=scene_id,
            receipt=_receipt(invented),
            expected_recorded_sha256=envelope["bundle"]["recorded_sha256"],
        )


def test_recording_the_same_generation_twice_is_idempotent(repository, tmp_path, generated):
    store, scene_id, receipt, record = generated
    envelope = world_read_bundle(repository.connection, repository.workspace_id, scene_id, store)
    assert envelope is not None
    again = record_generated_scene(
        repository,
        store,
        scene_id=scene_id,
        receipt=receipt,
        expected_recorded_sha256=envelope["bundle"]["recorded_sha256"],
    )
    assert again.artifact_id == record.artifact_id
    assert again.inserted is False


def test_the_stored_receipt_is_its_own_canonical_bytes(repository, generated):
    store, _scene_id, receipt, record = generated
    from exulanica.evidence.blob import BlobId

    payload = store.get(BlobId.from_hex(record.receipt_sha256))
    assert hashlib.sha256(payload).hexdigest() == record.receipt_sha256
    document = json.loads(payload)
    assert document["tier"] == "generated"
    assert document["seam"] == receipt.seam
    # Spelled out rather than read back from the document, which is what the first version did and
    # which made the assertion true of any statement at all, including an empty one.
    assert document["epistemics"]["citable"] is False
    assert document["epistemics"]["promotes_rung"] is False
    assert document["epistemics"]["is_evidence"] is False
    statement = document["epistemics"]["statement"]
    assert "produced by a model" in statement
    assert "supports no claim" in statement
    assert "carries no rung" in statement


# -- the four things it can never do ------------------------------------------------------


def test_a_generation_cannot_satisfy_any_reconstruction_gate():
    """Structural, at both ends of the gate, and neither end is a conditional.

    Going in, ``SceneGateInputs`` has one named slot per receipt kind and every slot checks the
    kind it holds, so there is nowhere a generated receipt could be placed. Coming out,
    ``validate_scene_gate_decision`` re-derives the decision from the receipt bytes and refuses an
    unsupported kind outright, so a hand-written gate envelope naming the generated tier is not a
    gate that awards a lower rung: it is not a gate at all.
    """
    inputs_fields = typing.get_type_hints(SceneGateInputs)
    assert GENERATED_SCENE_KIND not in inputs_fields
    assert set(inputs_fields) == {
        "pose",
        "placement",
        "registered_member_count",
        "member_count",
        "scale",
        "coverage",
        "corridor",
        "splat",
    }

    permitted = set(typing.get_args(typing.get_type_hints(SceneReceipt)["kind"]))
    assert permitted == {"pose", "placement", "scale", "coverage", "corridor", "splat"}
    assert GENERATED_SCENE_KIND not in permitted

    # A well-formed envelope, correctly digested, whose only defect is that it claims rung 1 on a
    # generated receipt. Everything cheaper than the kind check therefore passes, and the refusal
    # this asserts is the kind check itself rather than a malformed-input rejection standing in
    # for it.
    decision = {
        "profile": "exulanica.reconstruction-scene-gate/v1",
        "rung": 1,
        "member_count": 3,
        "registered_member_count": 3,
        "reasons": [],
        "receipts": [
            {
                "kind": GENERATED_SCENE_KIND,
                "sha256": "0" * 64,
                "accepted": True,
                "reasons": [],
                "measurements": [],
            }
        ],
    }
    canonical = json.dumps(decision, sort_keys=True, separators=(",", ":")).encode()
    envelope = {
        "profile": "exulanica.reconstruction-scene-gate-envelope/v1",
        "decision": decision,
        "decision_sha256": hashlib.sha256(canonical).hexdigest(),
    }
    with pytest.raises(ValueError, match="receipt kind is unsupported"):
        validate_scene_gate_decision(json.dumps(envelope).encode())


def test_a_generated_receipt_cannot_be_placed_in_a_gate_input():
    """Every optional slot checks that what it holds is the kind it is named for."""
    with pytest.raises(ValueError, match="wrong kind"):
        SceneGateInputs(
            pose=SceneReceipt(kind="pose", sha256="1" * 64, accepted=True),
            placement=SceneReceipt(kind="placement", sha256="2" * 64, accepted=True),
            registered_member_count=3,
            member_count=3,
            splat=SceneReceipt(kind="coverage", sha256="3" * 64, accepted=True),
        )


def test_recording_a_generation_does_not_move_the_recorded_rung(repository, tmp_path):
    store, _captures, scene_id = _published_scene(repository, tmp_path, registered=3, spacing=5)
    before = read_snapshot(repository.connection, repository.workspace_id, store)
    scene_before = next(s for s in before.reconstruction_scenes if s.scene_id == scene_id)

    envelope = world_read_bundle(repository.connection, repository.workspace_id, scene_id, store)
    assert envelope is not None
    record_generated_scene(
        repository,
        store,
        scene_id=scene_id,
        receipt=_receipt(envelope["bundle"]["recorded_sha256"]),
        expected_recorded_sha256=envelope["bundle"]["recorded_sha256"],
    )

    after = read_snapshot(repository.connection, repository.workspace_id, store)
    scene_after = next(s for s in after.reconstruction_scenes if s.scene_id == scene_id)
    assert scene_after.recorded_rung == scene_before.recorded_rung
    assert scene_after.displayed_rung == scene_before.displayed_rung
    assert scene_after.recorded_reasons == scene_before.recorded_reasons
    assert scene_after.rendering_substrate == scene_before.rendering_substrate
    assert scene_after.generated_geometry, "the generation is present, it just changes nothing"


def test_a_generation_cannot_become_an_assertion_support_span(repository, generated):
    """Invariant 2 from the writing side.

    ``evidence_span`` references ``blob``. A generated artifact has no source blob at all, so
    there is no span that could name it; this asserts the absence rather than assuming it.
    """
    _store, _scene_id, _receipt, record = generated
    row = repository.connection.execute(
        "select source_blob_sha256, scene_id from artifact "
        "where workspace_id=%s and artifact_id=%s",
        (repository.workspace_id, record.artifact_id),
    ).fetchone()
    assert row["source_blob_sha256"] is None
    assert row["scene_id"] is not None
    spans = repository.connection.execute(
        "select count(*) as n from evidence_span where workspace_id=%s and blob_sha256=%s",
        (repository.workspace_id, bytes.fromhex(record.receipt_sha256)),
    ).fetchone()
    assert spans["n"] == 0


def test_the_graph_keeps_generated_geometry_out_of_trained_geometry(repository, generated):
    store, scene_id, receipt, record = generated
    snapshot = read_snapshot(repository.connection, repository.workspace_id, store)
    scene = next(s for s in snapshot.reconstruction_scenes if s.scene_id == scene_id)

    assert len(scene.generated_geometry) == 1
    entry = scene.generated_geometry[0]
    assert entry.tier == "generated"
    assert entry.state == "available"
    assert entry.artifact_id == record.artifact_id
    assert entry.model is not None and entry.model.model_version == "2026.09"
    assert entry.world_read_bundle_sha256 == receipt.bundle_sha256
    assert entry.seam == _SEAM

    # And the recorded side is untouched. A client reading only trained_geometry sees exactly the
    # world that was photographed.
    if scene.trained_geometry is not None:
        assert scene.trained_geometry.artifact_id != record.artifact_id


def test_the_read_bundle_keeps_generated_out_of_the_recorded_geometry_list(repository, generated):
    store, scene_id, _receipt, record = generated
    envelope = world_read_bundle(repository.connection, repository.workspace_id, scene_id, store)
    assert envelope is not None
    bundle = envelope["bundle"]

    assert all(entry["tier"] == "recorded" for entry in bundle["geometry"])
    assert all(entry["artifact_id"] != str(record.artifact_id) for entry in bundle["geometry"])

    assert len(bundle["generated"]) == 1
    generated_entry = bundle["generated"][0]
    assert generated_entry["tier"] == "generated"
    assert generated_entry["epistemics"] == {
        "citable": False,
        "promotes_rung": False,
        "is_evidence": False,
    }
    assert generated_entry["seam"] == _SEAM


def test_a_corrupt_generation_receipt_is_reported_rather_than_dropped(repository, generated):
    """A dropped generation is indistinguishable from no generation, which is the worse failure."""
    store, scene_id, _receipt, record = generated
    from exulanica.evidence.blob import BlobId

    # Stored objects are written read-only, which is a real guarantee: the store does not let a
    # process overwrite content-addressed bytes in place. Corrupting them here therefore takes a
    # deliberate chmod, and that is what a damaged disk or a restored-from-elsewhere object looks
    # like to the reader.
    path = store.root / store.key_for(BlobId.from_hex(record.receipt_sha256))
    path.chmod(0o644)
    path.write_bytes(b'{"profile":"exulanica.generated-scene/v1","tier":"generated"}')

    snapshot = read_snapshot(repository.connection, repository.workspace_id, store)
    scene = next(s for s in snapshot.reconstruction_scenes if s.scene_id == scene_id)
    assert len(scene.generated_geometry) == 1
    entry = scene.generated_geometry[0]
    assert entry.state == "invalid"
    assert entry.state_reason is not None
    assert entry.seam is None


def test_withdrawing_a_member_removes_the_generation_from_the_graph(repository, generated):
    """Deletion reaches the generated tier through the guards every artifact already passes."""
    store, scene_id, _receipt, _record = generated
    member = repository.connection.execute(
        "select capture_id from reconstruction_scene_member "
        "where workspace_id=%s and scene_id=%s order by ordinal limit 1",
        (repository.workspace_id, scene_id),
    ).fetchone()
    repository.insert_tombstone(
        scope="capture",
        capture_id=member["capture_id"],
        requested_by=uuid.uuid4(),
        reason="generated tier withdrawal test",
    )
    snapshot = read_snapshot(repository.connection, repository.workspace_id, store)
    assert all(scene.scene_id != scene_id for scene in snapshot.reconstruction_scenes)


def test_filing_a_generation_leaves_the_recorded_digest_untouched(repository, tmp_path):
    """The property the idempotency failure taught, pinned so it cannot regress.

    A generation cites ``recorded_sha256``. If filing one changed that digest, the same generation
    could never be filed twice and two models could never both say they read the same observed
    world. ``bundle_sha256`` does change, because the response genuinely now contains something it
    did not before.
    """
    store, _captures, scene_id = _published_scene(repository, tmp_path, registered=3, spacing=5)
    before = world_read_bundle(repository.connection, repository.workspace_id, scene_id, store)
    assert before is not None
    recorded = before["bundle"]["recorded_sha256"]

    record_generated_scene(
        repository,
        store,
        scene_id=scene_id,
        receipt=_receipt(recorded),
        expected_recorded_sha256=recorded,
    )

    after = world_read_bundle(repository.connection, repository.workspace_id, scene_id, store)
    assert after is not None
    assert after["bundle"]["recorded_sha256"] == recorded
    assert after["bundle_sha256"] != before["bundle_sha256"]


def test_two_generations_for_one_scene_are_both_visible(repository, tmp_path):
    """Two runs of one model are two artifacts, and the graph must show both.

    Two defects met here, and neither test in the first version could see either. The artifact key
    hashed only the generation's provenance, so a second run of the same model on the same prompt
    and bundle collided with the first, was silently discarded, and the caller was handed a digest
    naming bytes nobody stored. And the read went through ``artifact_current``, whose distinct-on
    key every generation for one scene shares, so even two genuinely distinct artifacts would have
    come back as one row.
    """
    store, _captures, scene_id = _published_scene(repository, tmp_path, registered=3, spacing=5)
    envelope = world_read_bundle(repository.connection, repository.workspace_id, scene_id, store)
    assert envelope is not None
    recorded = envelope["bundle"]["recorded_sha256"]

    first = record_generated_scene(
        repository,
        store,
        scene_id=scene_id,
        receipt=_receipt(recorded, seam=_SEAM),
        expected_recorded_sha256=recorded,
    )
    # Same model, same prompt, same bundle, different sampled output. Under ADR-0017 these are two
    # artifacts, because re-running a sampled generation does not reproduce its bytes.
    second = record_generated_scene(
        repository,
        store,
        scene_id=scene_id,
        receipt=_receipt(recorded, content_sha256=_sha("a different sampling")),
        expected_recorded_sha256=recorded,
    )
    assert first.inserted and second.inserted
    assert first.artifact_id != second.artifact_id
    assert first.receipt_sha256 != second.receipt_sha256

    # Both sets of bytes are actually in the store, which is what the discarded-write defect broke.
    from exulanica.evidence.blob import BlobId

    for record in (first, second):
        stored = store.get(BlobId.from_hex(record.receipt_sha256))
        assert hashlib.sha256(stored).hexdigest() == record.receipt_sha256

    snapshot = read_snapshot(repository.connection, repository.workspace_id, store)
    scene = next(s for s in snapshot.reconstruction_scenes if s.scene_id == scene_id)
    visible = {str(entry.artifact_id) for entry in scene.generated_geometry}
    assert visible == {str(first.artifact_id), str(second.artifact_id)}
    assert all(entry.state == "available" for entry in scene.generated_geometry)
