"""A stand-in for the served world specification document, for the drafter's tests.

Shaped as ``GET /worlds/specification`` serves it (profile ``exulanica.world-specification/v1``):
every value with its words, kind, unit, whether it is adjustable and its range or fixed value,
and the presets with the values each sets. The drafter reads only the fields ``specification_view``
in :mod:`exulanica.selection.world_drafting` reads, so a test built on this stand-in exercises the
same reading the served document gets. Its values are the town lane's schema: four adjustable,
the rest fixed.
"""

from __future__ import annotations

import copy
from typing import Any


def _integer(key: str, label: str, unit: str, low: int, high: int, step: int) -> dict[str, Any]:
    value: dict[str, Any] = {
        "key": key,
        "label": label,
        "kind": "integer",
        "unit": unit,
        "adjustable": low < high,
        "minimum": low,
        "maximum": high,
        "step": step,
        "reason": f"stand-in reason for {key}",
    }
    value["requires"] = []
    if low == high:
        value["value"] = low
    return value


def _choice(key: str, label: str, choices: list[str]) -> dict[str, Any]:
    value: dict[str, Any] = {
        "key": key,
        "label": label,
        "kind": "choice",
        "unit": "key",
        "adjustable": len(choices) > 1,
        "choices": choices,
        "requires": [],
        "reason": f"stand-in reason for {key}",
    }
    if len(choices) == 1:
        value["value"] = choices[0]
    return value


_BLOCKS = _integer("block_length_mm", "Distance between cross streets", "mm", 90000, 140000, 10000)
_BLOCKS["requires"] = [
    {
        "when": "city_extent_x_mm",
        "from": 384000,
        "to": 384000,
        "minimum": 130000,
        "maximum": 140000,
        "reason": "stand-in: three tiles generate only with long blocks",
    },
    {
        "when": "city_extent_x_mm",
        "from": 256000,
        "to": 256000,
        "minimum": 90000,
        "maximum": 120000,
        "reason": "stand-in: two tiles bake only with shorter blocks",
    },
]

_DOCUMENT: dict[str, Any] = {
    "profile": "exulanica.world-specification/v1",
    "schema": {"catalog_id": "world-specification", "catalog_version": 1, "sha256": "0" * 64},
    "presets_catalog": {"catalog_id": "world-recipe", "catalog_version": 2},
    "grammar": {"grammar_id": "city", "grammar_version": 4},
    "values": [
        _choice("grammar_id", "The grammar a town is generated by", ["city"]),
        _integer("grammar_version", "The version of that grammar", "count", 4, 4, 1),
        _integer(
            "city_extent_x_mm", "Length of the town, west to east", "mm", 256000, 384000, 128000
        ),
        _integer(
            "city_extent_y_mm", "Depth of the town, south to north", "mm", 128000, 128000, 128000
        ),
        _BLOCKS,
        _integer("block_depth_mm", "Depth of a block", "mm", 56000, 56000, 1000),
        _integer("storey_band_low", "Fewest storeys a building has", "count", 2, 3, 1),
        _integer("storey_band_high", "Most storeys a building has", "count", 4, 5, 1),
        _choice("driving_side", "The side of the road traffic keeps to", ["right"]),
        _integer("terrain_relief_mm", "Rise and fall of the ground", "mm", 0, 0, 1),
    ],
    "presets": [
        {
            "key": "small_town",
            "label": "A small town",
            "values": {
                "city_extent_x_mm": 256000,
                "block_length_mm": 90000,
                "storey_band_low": 2,
                "storey_band_high": 4,
            },
            "tiles": 2,
        },
        {
            "key": "market_town",
            "label": "A market town",
            "values": {
                "city_extent_x_mm": 384000,
                "block_length_mm": 140000,
                "storey_band_low": 2,
                "storey_band_high": 4,
            },
            "tiles": 3,
        },
    ],
    "bounds": {"tiles_maximum": 4, "people": [], "generated_worlds_per_workspace": 3},
    "refusals": [],
}


def specification_document() -> dict[str, Any]:
    """A fresh copy of the stand-in document, which a test may change."""
    return copy.deepcopy(_DOCUMENT)
