/**
 * Embed the backend society engine table in the app package, byte for byte, with its engine union.
 *
 * `exulanica/world/society-engines.v4.json` is the one statement of which society engines exist
 * and what each can do: whether a society may still be created with it, whether it reads inputs,
 * whether playback may play it, whether it takes directed actions or model decisions, whether the
 * world's owner may choose a model for one of its people, which state shape it writes and how many
 * people it holds (no maximum where it states none), which engine a new society over each kind of ground is created with, and which
 * one a saved world holding a thing its author placed takes on a host that offers societies of things.
 * The browser needs that vocabulary synchronously at module load, and the file sits outside the
 * web workspace, so this script copies its exact text into a generated module, together with the
 * union of engine profiles read from it, instead of anybody restating either by hand.
 *
 * The app test `society-engines.test.ts` and the backend test `tests/test_society_engine_table.py`
 * both fail when the generated module and the file differ.
 *
 *   pnpm run society-engines:sync
 */
import { readFileSync, writeFileSync } from 'node:fs';

const SOURCE = new URL('../../exulanica/world/society-engines.v4.json', import.meta.url);
const TARGET = new URL('../packages/app/src/society-engines.generated.ts', import.meta.url);

const text = readFileSync(SOURCE, 'utf8');
// String.raw keeps every byte except these three, so refuse rather than escape: an escaped copy
// would no longer be comparable to the file with a plain string equality.
if (text.includes('`') || text.includes('${') || text.includes('\\')) {
  throw new Error('the engine table contains text a raw template literal cannot carry verbatim');
}
const table = JSON.parse(text) as { engines: readonly { engine: string }[] };
const union = table.engines.map((row) => `'${row.engine}'`).join(' | ');

writeFileSync(TARGET, [
  '// GENERATED by `pnpm run society-engines:sync` from exulanica/world/society-engines.v4.json.',
  '// Do not edit. Edit the backend table and run the script; two tests compare these bytes.',
  '',
  `export const SOCIETY_ENGINES_V4_JSON = String.raw\`${text}\`;`,
  '',
  `export type SocietyEngineProfile = ${union};`,
  '',
].join('\n'));
