/**
 * Embed the backend world-style registry in the presentation package, byte for byte.
 *
 * `exulanica/world/style-registry.v1.json` is the one authored source for which world profiles
 * exist, who may use them, which reviewed modules they run and which controls they expose. The
 * browser needs that vocabulary synchronously at module load, and the file sits outside the web
 * workspace where neither `tsc` nor the dev server will read it, so this script copies its exact
 * text into a generated module instead of anybody restating it by hand.
 *
 * Nothing is parsed or reformatted here: the embedded string is the file. The presentation test
 * `world-style-registry.test.ts` and the backend test `tests/test_world_style_contract.py` both fail
 * when the two differ, so an edit to the JSON that is not followed by this script cannot land.
 *
 *   pnpm run world-style:sync
 */
import { readFileSync, writeFileSync } from 'node:fs';

const SOURCE = new URL('../../exulanica/world/style-registry.v1.json', import.meta.url);
const TARGET = new URL(
  '../packages/presentation/src/world-style-registry-v1.generated.ts',
  import.meta.url,
);

const text = readFileSync(SOURCE, 'utf8');
// String.raw keeps every byte except these three, so refuse rather than escape: an escaped copy
// would no longer be comparable to the file with a plain string equality.
if (text.includes('`') || text.includes('${') || text.includes('\\')) {
  throw new Error('the backend registry contains text a raw template literal cannot carry verbatim');
}
JSON.parse(text);

writeFileSync(TARGET, [
  '// GENERATED by `pnpm run world-style:sync` from exulanica/world/style-registry.v1.json.',
  '// Do not edit. Edit the backend registry and run the script; two tests compare these bytes.',
  '',
  `export const WORLD_STYLE_REGISTRY_V1_JSON = String.raw\`${text}\`;`,
  '',
].join('\n'));
