"""The generation queue's format: its layout in the bucket and its strict records.

The format is :mod:`exulanica_pieces.queue`, shared with the product's generation worker so both
read one definition; it is named here for the session and the operator's tooling.
"""

from __future__ import annotations

from exulanica_pieces.queue import (
    BEAT_PROFILE,
    CLAIM_PROFILE,
    DONE_PROFILE,
    DONE_PROFILE_V1,
    ENTRY_PROFILE,
    IDLE_SECONDS_DEFAULT,
    MAX_FILE_BYTES,
    MAX_REQUESTS,
    SESSION_MANIFEST_PROFILE,
    SESSION_PROFILE,
    SESSION_ROUTES,
    STOP_SECONDS_MAXIMUM,
    WITHDRAWN_PROFILE,
    build_claim,
    build_done,
    build_ready,
    build_session,
    build_session_manifest,
    build_withdrawn,
    charges_from_done,
    entry_files,
    instant,
    is_entry_id,
    read_claim,
    read_done,
    read_entry,
    read_ready,
    read_session,
    read_session_manifest,
    read_withdrawn,
    uncached_requests,
)

__all__ = [
    "BEAT_PROFILE",
    "CLAIM_PROFILE",
    "DONE_PROFILE",
    "DONE_PROFILE_V1",
    "ENTRY_PROFILE",
    "IDLE_SECONDS_DEFAULT",
    "MAX_FILE_BYTES",
    "MAX_REQUESTS",
    "SESSION_MANIFEST_PROFILE",
    "SESSION_PROFILE",
    "SESSION_ROUTES",
    "STOP_SECONDS_MAXIMUM",
    "WITHDRAWN_PROFILE",
    "build_claim",
    "build_done",
    "build_ready",
    "build_session",
    "build_session_manifest",
    "build_withdrawn",
    "charges_from_done",
    "entry_files",
    "instant",
    "is_entry_id",
    "read_claim",
    "read_done",
    "read_entry",
    "read_ready",
    "read_session",
    "read_session_manifest",
    "read_withdrawn",
    "uncached_requests",
]
