/**
 * The proof lens: colour a region by what produced what you are looking at.
 *
 * Roadmap Phase 10. The rung ladder is already displayed as a sentence in the status panel, and a
 * sentence is something a visitor reads once. The lens is the same fact as a property of the
 * picture: turn it on and every surface in view says whether a camera saw it, whether it was
 * reconstructed from photographs, or whether a model imagined it.
 *
 * Three decisions worth stating, because each has an obvious wrong alternative.
 *
 * **The tier is not the rung.** Rungs 1 through 3 are all reconstruction, differing in how much
 * was earned; rung 4 is the photograph itself, shown as a photograph. So the ladder's four values
 * collapse to two tiers here, and a third tier exists that has no rung at all. Colouring by rung
 * would give four colours that answer a question nobody asked at this moment, which is "how good
 * is this reconstruction" rather than "is this real".
 *
 * **The decision lives here, not in the renderer.** `atlas-react` may not choose a colour: the
 * dependency-cruiser rule `engine-specific-code-stays-behind-the-binding` and the binding's own
 * header both say so. What crosses into the renderer is a resolved RGB triple.
 *
 * **A region that is not drawing its scene gets its own tier.** `unavailable` is not a shade of
 * reconstructed. A region whose geometry failed to load, or whose scene is not the one its area
 * displays, is showing the visitor nothing about the world, and colouring it as though it were
 * showing reconstruction would be the lens telling the exact lie it exists to prevent.
 */

import type { PresentationTheme } from './system.js';
import { unitRgb } from './system.js';

/** What produced the surface a visitor is looking at. */
export type ProofTier =
  /** A photograph, shown as a photograph. Rung 4, source-first. */
  | 'photographed'
  /** Geometry derived from photographs by a reviewed stage. Rungs 1 to 3. */
  | 'reconstructed'
  /** Content a world model imagined. Below every recorded rung; supports no claim. */
  | 'generated'
  /** Nothing about the world is being shown here, and that is a fact, not a shade of the others. */
  | 'unavailable';

export const PROOF_TIERS: readonly ProofTier[] = Object.freeze([
  'photographed',
  'reconstructed',
  'generated',
  'unavailable',
]);

/**
 * The legend, and it is not optional.
 *
 * A colour without a name is a claim a visitor cannot check, which would make the lens decorative
 * rather than evidential. `proofTierDisclosure` in the app's status panel renders these strings
 * verbatim rather than rewording them, so the colour and the words cannot drift apart.
 */
export const PROOF_TIER_LABELS: Readonly<Record<ProofTier, string>> = Object.freeze({
  photographed: 'Photographed',
  reconstructed: 'Reconstructed from photographs',
  generated: 'Generated by a model',
  unavailable: 'Not shown',
});

export const PROOF_TIER_SENTENCES: Readonly<Record<ProofTier, string>> = Object.freeze({
  photographed: 'A camera recorded this. The original bytes are the evidence behind it.',
  reconstructed:
    'Derived from photographs by a reviewed stage. It visualises what was observed and is not itself evidence.',
  generated:
    'A model produced this. No camera observed it, it supports no claim, and it carries no reconstruction rung.',
  unavailable: 'Nothing about the world is being drawn here.',
});

/**
 * Colours, drawn from the theme's existing provenance palette rather than invented.
 *
 * `capture` and `inference` already mean "recorded" and "derived" everywhere else in this product,
 * so reusing them keeps one vocabulary. `generated` takes the theme's warning colour, which is the
 * one slot whose whole job is to say look at this, and `unavailable` takes `muted`, because an
 * absence should recede rather than compete with the two tiers that are saying something.
 */
export function proofTierColor(theme: PresentationTheme, tier: ProofTier): string {
  switch (tier) {
    case 'photographed':
      return theme.provenance.capture;
    case 'reconstructed':
      return theme.provenance.inference;
    case 'generated':
      return theme.warning;
    case 'unavailable':
      return theme.muted;
  }
}

/**
 * How far the lens pushes a tier colour away from its own grey before it reaches the world.
 *
 * MEASURED, NOT PICKED. The theme's provenance colours are chips: small, quiet, and read against
 * type, so `inference` is `#57686d` in Dawn, whose channels sit within 0.09 of its own luminance.
 * A wash that keeps a surface's brightness and takes only that colour's hue is then almost exactly
 * grey, and on the real bowl on 2026-09-06 the lens was visible as a slight desaturation and not
 * as a colour. A lens a visitor cannot see is a legend nobody can check.
 *
 * 3.5 is where the four tiers separate as hues in Dawn, which is the darker-on-light case and
 * therefore the hard one: `photographed` becomes a clear green, `reconstructed` a clear blue,
 * `generated` an orange and `unavailable` a muted green. It saturates around the colour's own
 * luminance rather than brightening it, so no tier becomes louder than another by accident, and
 * the result is clamped per channel, which is why this belongs here rather than in a shader: a
 * clamp is a decision about what colour to show when the arithmetic leaves the display.
 */
const LENS_CHROMA = 3.5;

const LUMA = Object.freeze([0.2126, 0.7152, 0.0722]);

/** One tier's lens colour: the theme's provenance chip, saturated enough to read as a wash. */
function lensRgb(theme: PresentationTheme, tier: ProofTier): readonly [number, number, number] {
  const rgb = unitRgb(proofTierColor(theme, tier));
  const luma = rgb[0] * LUMA[0]! + rgb[1] * LUMA[1]! + rgb[2] * LUMA[2]!;
  const push = (value: number): number =>
    Math.min(1, Math.max(0, luma + (value - luma) * LENS_CHROMA));
  return [push(rgb[0]), push(rgb[1]), push(rgb[2])];
}

/**
 * The lens palette as the renderer wants it: four RGBA rows, indexed by `PROOF_TIERS`.
 *
 * The fourth channel is emphasis rather than opacity: how strongly the lens tints its tier when
 * active. `generated` is highest because the one thing a viewer must never fail to notice is that
 * a surface was imagined; `unavailable` is lowest for the same reason it uses `muted`.
 */
export function proofLensPalette(theme: PresentationTheme): Float32Array {
  const emphasis: Readonly<Record<ProofTier, number>> = {
    photographed: 0.55,
    reconstructed: 0.5,
    generated: 0.9,
    unavailable: 0.25,
  };
  const out = new Float32Array(PROOF_TIERS.length * 4);
  PROOF_TIERS.forEach((tier, index) => {
    const [r, g, b] = lensRgb(theme, tier);
    out.set([r, g, b, emphasis[tier]], index * 4);
  });
  return out;
}

/**
 * The legend swatch, which must be the colour the world is actually wearing.
 *
 * The same row `proofLensPalette` hands the renderer, as CSS. Not `proofTierColor`: that is the
 * chip colour the lens saturates on its way out, so a legend painted from it would be a key to a
 * picture drawn in slightly different colours, which is the one thing a key may not be.
 */
export function proofLensSwatch(theme: PresentationTheme, tier: ProofTier): string {
  const byte = (value: number): number => Math.round(value * 255);
  const [r, g, b] = lensRgb(theme, tier);
  return `rgb(${String(byte(r))} ${String(byte(g))} ${String(byte(b))})`;
}

/** Everything the lens needs to know about one region, and nothing it does not. */
export interface ProofLensInput {
  /** What the region is actually drawing right now, from the scene's rendering substrate. */
  readonly substrate:
    'posed_point_maps' | 'unposed_point_maps' | 'gaussian_splats' | 'source_photographs' | null;
  /**
   * Whether this region is drawing its scene at all. False for a region whose area displays a
   * different, more complete scene over the same photographs, and for one whose bytes failed.
   */
  readonly drawn: boolean;
  /** Whether the region is showing content a model generated rather than recorded geometry. */
  readonly showingGenerated: boolean;
}

/**
 * The tier one region is currently showing.
 *
 * Order matters and is deliberate. `drawn` is checked first, because a region that is not drawing
 * is showing nothing regardless of what it could show. `showingGenerated` is checked before the
 * substrate, because a generated surface drawn over recorded geometry is generated at the point
 * the visitor is looking, and the more alarming of two true answers is the one to give.
 */
export function proofTierOf(input: ProofLensInput): ProofTier {
  if (!input.drawn || input.substrate === null) return 'unavailable';
  if (input.showingGenerated) return 'generated';
  if (input.substrate === 'source_photographs') return 'photographed';
  // Posed or not, a point map is derived from a photograph by a reviewed depth stage. What an
  // unposed one lacks is a measured position, and the status line says that; the surface itself
  // is reconstructed.
  return 'reconstructed';
}

/** The palette row index for a tier, which is what the renderer indexes its uniform by. */
export function proofTierIndex(tier: ProofTier): number {
  return PROOF_TIERS.indexOf(tier);
}
