/**
 * The dedication every set carries, stored as its own blob and referenced by digest, the way
 * `exulanica/world/assets.py` references the dedication for its meshes.
 *
 * The sets are generated from source in this repository by this package, from hashed integers and
 * nothing else: no photograph, scan, sample library or model output goes into them. That is what
 * makes CC0 a claim this project is in a position to make. The text is short on purpose; it is the
 * statement that applies to these sets, with a pointer to the canonical legal code.
 */
export const LICENCE_ID = 'CC0-1.0';

export const LICENCE_TEXT = [
  'CC0 1.0 Universal Public Domain Dedication',
  '',
  'The texture data in this asset was generated by the Exulanica repository, from source in that',
  'repository, and is dedicated to the public domain. To the extent possible under law, the',
  'authors have waived all copyright and related or neighboring rights to it. The work is',
  'published from the repository that generates it and may be copied, modified and distributed,',
  'including for commercial purposes, without asking permission.',
  '',
  'The full text of the dedication is at https://creativecommons.org/publicdomain/zero/1.0/',
  '',
].join('\n');

export function licenceBytes(): Uint8Array {
  return new TextEncoder().encode(LICENCE_TEXT);
}
