"""The site grammar: a world of any kind laid out from its kind's plan.

Every world kind other than the town (a farm, a building site, a cafe, a harbour, kinds nobody
listed) is generated by this grammar under the generic contract: a descriptor
(``site.v1.json``), one stage that lays the site out (:mod:`.layout`), records declared as shapes
(:mod:`.records`), a seed and the one subject identity rule, and a receipt. What it lays out is a
:class:`~.plan.SitePlan`, the kind with a person's values resolved, which the stage holds; so a
site grammar is built for each plan (:func:`site_grammar`) and is registered nowhere. The registry
holds the grammars a specification alone runs; a site needs its kind.

The layer contracts hold here as for every grammar: nothing in this package can name evidence,
open a database or reach a photograph, and every figure is an integer.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final

from exulanica.grammar.contract import Generation, Grammar, StageContext, StageEmission, generate
from exulanica.grammar.errors import InvalidRecordError
from exulanica.grammar.grammars.site.layout import lay_out
from exulanica.grammar.grammars.site.plan import SitePlan
from exulanica.grammar.grammars.site.records import (
    RECORD_SHAPES,
    SiteExtentRecord,
    SiteFixtureRecord,
    SiteStructureRecord,
    validate_site_record,
)
from exulanica.grammar.shapes import check_identities, check_references, index_records

__all__ = [
    "LAYOUT_STAGE_VERSION",
    "SITE_DESCRIPTOR_PATH",
    "SITE_GRAMMAR_ID",
    "SITE_GRAMMAR_VERSION",
    "check_site_records",
    "generate_site",
    "site_grammar",
    "site_records",
]

SITE_GRAMMAR_ID: Final = "site"
SITE_GRAMMAR_VERSION: Final = 1
LAYOUT_STAGE_VERSION: Final = 1
SITE_DESCRIPTOR_PATH: Final = Path(__file__).with_name("site.v1.json")
_SHAPES: Final = {shape.record_type: shape for shape in RECORD_SHAPES}


@dataclass(frozen=True, slots=True)
class _LayoutStage:
    """The one stage: the whole layout of one plan."""

    plan: SitePlan = field(repr=False)
    stage_id: str = "layout"
    stage_version: int = LAYOUT_STAGE_VERSION

    def emit(self, context: StageContext) -> StageEmission:
        return StageEmission(
            stage_id=self.stage_id,
            stage_version=self.stage_version,
            status="emitted",
            reason="",
            records=lay_out(self.plan, context),
        )

    def validate(self, record: object) -> None:
        validate_site_record(record)


def site_grammar(plan: SitePlan) -> Grammar:
    """The site grammar for one plan: the descriptor's identity, semantics and cascade with the
    plan's layout stage."""
    return Grammar.from_descriptor(SITE_DESCRIPTOR_PATH, (_LayoutStage(plan),))


def generate_site(plan: SitePlan, *, seed: str, subject_identity: str) -> Generation:
    """Generate one site: every record of the plan's layout for this seed and subject, each held
    to its shape, and then all of them to each other (:func:`check_site_records`)."""
    generation = generate(site_grammar(plan), seed=seed, subject_identity=subject_identity)
    check_site_records(site_records(generation), root_identity=subject_identity)
    return generation


def site_records(generation: Generation) -> tuple[object, ...]:
    """Every record a site generation emitted, in emission order."""
    return tuple(record for emission in generation.emissions for record in emission.records)


def _inside(record: object, extent: SiteExtentRecord) -> bool:
    if isinstance(record, SiteFixtureRecord):
        half = max(record.width_mm, record.depth_mm) // 2
        return (
            half <= record.x_mm <= extent.width_mm - half
            and half <= record.y_mm <= extent.depth_mm - half
        )
    if hasattr(record, "max_x_mm"):
        return record.max_x_mm <= extent.width_mm and record.max_y_mm <= extent.depth_mm  # type: ignore[attr-defined]
    if hasattr(record, "end_x_mm"):
        return record.end_x_mm <= extent.width_mm and record.end_y_mm <= extent.depth_mm  # type: ignore[attr-defined]
    return True


def check_site_records(records: Sequence[object], *, root_identity: str) -> None:
    """Hold a site's records to each other: one extent, every identity its rule's derivation, every
    reference resolved, everything inside the extent, and no two structures overlapping."""
    extents = [record for record in records if isinstance(record, SiteExtentRecord)]
    if len(extents) != 1:
        raise InvalidRecordError("a site states one extent")
    for record in records:
        validate_site_record(record)
    index = index_records(records, _SHAPES)
    check_references(records, _SHAPES, index)
    check_identities(records, _SHAPES, grammar_id=SITE_GRAMMAR_ID, root_identity=root_identity)
    extent = extents[0]
    outside = [record for record in records if not _inside(record, extent)]
    if outside:
        raise InvalidRecordError(f"{type(outside[0]).__name__} lies outside the site")
    structures = [record for record in records if isinstance(record, SiteStructureRecord)]
    for position, first in enumerate(structures):
        for second in structures[position + 1 :]:
            if (
                first.min_x_mm < second.max_x_mm
                and second.min_x_mm < first.max_x_mm
                and first.min_y_mm < second.max_y_mm
                and second.min_y_mm < first.max_y_mm
            ):
                raise InvalidRecordError(
                    f"structures {first.identity} and {second.identity} overlap"
                )
