/**
 * A document as `GET /worlds/specification` serves it, cut to what the page's tests read; the
 * server's own is held whole by tests/test_town_specification.py.
 */
import { SPECIFICATION_PROFILE } from '../src/world-specification.js';

export function servedSpecification(): Record<string, unknown> {
  return {
    profile: SPECIFICATION_PROFILE,
    schema: { catalog_id: 'world-specification', catalog_version: 1, sha256: 'a'.repeat(64) },
    presets_catalog: { catalog_id: 'world-recipe', catalog_version: 2 },
    grammar: { grammar_id: 'city', grammar_version: 4 },
    values: [
      { key: 'grammar_id', label: 'The grammar a town is generated by', kind: 'choice', unit: 'key', adjustable: false, choices: ['city'], value: 'city', requires: [], reason: 'Authored: the city grammar states streets.' },
      { key: 'city_extent_x_mm', label: 'Length of the town, west to east', kind: 'integer', unit: 'mm', adjustable: true, minimum: 256000, maximum: 384000, step: 128000, requires: [], reason: 'Measured: whole tiles, two or three.' },
      { key: 'block_length_mm', label: 'Distance between cross streets', kind: 'integer', unit: 'mm', adjustable: true, minimum: 90000, maximum: 140000, step: 10000,
        requires: [
          { when: 'city_extent_x_mm', from: 256000, to: 256000, minimum: 90000, maximum: 120000, reason: 'Measured: two tiles need short blocks.' },
          { when: 'city_extent_x_mm', from: 384000, to: 384000, minimum: 130000, maximum: 140000, reason: 'Measured: three tiles need long blocks.' },
        ],
        reason: 'Measured: 90 to 140 m in 10 m steps.' },
      { key: 'block_depth_mm', label: 'Depth of a block', kind: 'integer', unit: 'mm', adjustable: false, minimum: 56000, maximum: 56000, step: 1000, value: 56000, requires: [], reason: 'Measured: 56 m, so traffic compiles.' },
      { key: 'driving_side', label: 'The side of the road traffic keeps to', kind: 'choice', unit: 'key', adjustable: false, choices: ['right'], value: 'right', requires: [], reason: 'Authored: the traffic drives on the right.' },
    ],
    presets: [
      { key: 'small_town', label: 'A small town', values: { city_extent_x_mm: 256000, block_length_mm: 90000 }, tiles: 2 },
      { key: 'market_town', label: 'A market town', values: { city_extent_x_mm: 384000, block_length_mm: 140000 }, tiles: 3 },
    ],
    bounds: { tiles_maximum: 4, people: [{ ground: 'generated_town', composer: 'city-grammar-town', most: 128 }], generated_worlds_per_workspace: 3 },
    refusals: [
      { code: 'specification_value_unknown', status: 422, meaning: 'The schema states no adjustable value with this key.' },
      { code: 'specification_value_out_of_range', status: 422, meaning: 'The value is outside its range.' },
    ],
  };
}
