"""Generate the complete documentation inventory, so the index cannot drift from the tree.

MEASURED 2026-09-09: `docs/README.md` carried a hand-maintained table of 45 rows against 111
markdown files, and never mentioned `docs/briefs/` at all. A hand-maintained index of a growing tree
does not stay complete; it decays to whatever somebody last remembered to add. So the navigational
part of the index stays hand-written and short, and the exhaustive part is generated here.

`tests/test_documentation_links.py` regenerates this in memory and fails if the committed file
differs, which is what makes the guarantee real rather than aspirational.

    uv run python scripts/generate_docs_index.py          # rewrite docs/all-documents.md
    uv run python scripts/generate_docs_index.py --check   # exit 1 if it is out of date
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "docs" / "all-documents.md"

#: Directory, heading, and what belongs there. The order is the order a reader should meet them.
SECTIONS: tuple[tuple[str, str, str], ...] = (
    ("", "Living contracts and reference", "How the system works now. Edited as the system changes."),
    ("capabilities", "Capability guides", "Written for somebody choosing to use it, not build it."),
    ("adr", "Decision records", "Numbered, and the number is the identifier. Never renumbered."),
    ("briefs", "Briefs", "What was intended, written before the work."),
    ("records", "Dated records", "Closed accounts of what happened on a date. Never edited after."),
    ("patches", "Patches", "Integration patches referenced by records."),
)

_STATUS = re.compile(r"^\s*(?:\*\*)?Status(?:\*\*)?\s*[:.]\s*(.+?)\s*$", re.I)


def summarise(path: Path) -> str:
    """One line for the index: the document's own status if it states one, else its opening line."""
    status = None
    opening = ""
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines()[:40]:
        line = raw.strip()
        if not line or line.startswith(("#", "---", "|", "<!--")):
            continue
        matched = _STATUS.match(line)
        if matched and status is None:
            status = matched.group(1)
            continue
        if not opening:
            opening = line
        if status and opening:
            break
    text = status or opening or "no summary line"
    text = re.sub(r"[*`_\[\]]", "", text)
    text = re.sub(r"\((?:https?://|[a-z0-9./-]+\.md)[^)]*\)", "", text)
    text = re.sub(r"\s+", " ", text).strip(" .,;")
    return (text[:137] + "...") if len(text) > 140 else text


def documents(directory: str) -> list[Path]:
    base = ROOT / "docs" / directory if directory else ROOT / "docs"
    if not base.is_dir():
        return []
    if directory:
        return sorted(p for p in base.rglob("*") if p.suffix in {".md", ".patch"} and p.is_file())
    return sorted(
        p for p in base.glob("*")
        if p.is_file() and p.suffix in {".md", ".patch"} and p.name not in {"README.md", TARGET.name}
    )


def render() -> str:
    known = {d for d, _, _ in SECTIONS if d}
    lines = [
        "# Every document, generated",
        "",
        "Generated by `scripts/generate_docs_index.py`. Do not edit by hand: a test regenerates it",
        "and fails if this file disagrees with the tree, which is what keeps it complete.",
        "",
        "`docs/evaluation/` is deliberately absent. It holds machine-written, digest-bound evidence",
        "rather than documents, it is immutable, and `tests/test_retained_evaluation_records.py`",
        "already inventories it. Start from [README.md](README.md) for the reading paths and the",
        "rule about where a new document goes.",
        "",
    ]
    total = 0
    for directory, heading, purpose in SECTIONS:
        found = documents(directory)
        if not found:
            continue
        total += len(found)
        lines += [f"## {heading}", "", f"{purpose}", "", f"{len(found)} documents.", ""]
        for path in found:
            rel = path.relative_to(ROOT / "docs").as_posix()
            label = path.stem if path.suffix == ".md" else path.name
            lines.append(f"- [{label}]({rel}) : {summarise(path)}")
        lines.append("")
    stray = [
        p.relative_to(ROOT / "docs").as_posix()
        for p in (ROOT / "docs").rglob("*.md")
        if p.parent != ROOT / "docs"
        and p.parts[len(ROOT.parts) + 1] not in known | {"evaluation"}
    ]
    if stray:
        lines += ["## Filed nowhere the index knows about", "",
                  "These are in a directory this generator has no section for, which means either the",
                  "section is missing or the document is misfiled.", ""]
        lines += [f"- `{s}`" for s in sorted(stray)] + [""]
    # The count belongs after the whole preamble, immediately before the first section.
    where = next(i for i, line in enumerate(lines) if line.startswith("## "))
    lines[where:where] = [f"**{total} documents**, excluding `docs/evaluation/`.", ""]
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the file is out of date")
    arguments = parser.parse_args()
    rendered = render()
    if arguments.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print(f"{TARGET.relative_to(ROOT)} is out of date; run scripts/generate_docs_index.py")
            return 1
        print(f"{TARGET.relative_to(ROOT)} is current")
        return 0
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}, {len(rendered.splitlines())} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
