"""Generate the public catalog from the tracked documentation and its ownership map.

    uv run python scripts/generate_docs_index.py
    uv run python scripts/generate_docs_index.py --check

The map supplies classification and responsibility, never a second capability-status inventory.
Discovery uses git so ignored working notes cannot enter a published catalog.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "docs" / "all-documents.md"
NAVIGATION = ROOT / "docs" / "navigation.json"
ROLES = frozenset({"overview", "guide", "contract", "reference", "standard", "archive"})
RETAINED = frozenset({"evaluation", "briefs", "records", "patches", "artifacts"})
INDEXES = frozenset({"docs/README.md", "docs/all-documents.md"})


def tracked_documents() -> list[str]:
    """Return repository-held Markdown paths, independent of ignored local files."""
    listed = subprocess.run(
        ["git", "ls-files", "-z", "--", "docs"], cwd=ROOT, check=True, capture_output=True
    ).stdout.decode()
    return sorted(rel for rel in listed.split("\0") if rel.endswith(".md"))


def public_documents(tracked: list[str]) -> set[str]:
    """Separate the maintained reading surface from decisions and retained evidence."""
    return {
        rel for rel in tracked if rel not in INDEXES and rel.split("/")[1] not in RETAINED | {"adr"}
    }


def validate_navigation(navigation: dict, tracked: list[str]) -> list[dict]:
    """Refuse missing, duplicated or unclassified documents before rendering a catalog."""
    if set(navigation) != {"version", "groups"} or navigation["version"] != 1:
        raise ValueError("navigation requires version 1 and groups")
    groups = navigation["groups"]
    if not isinstance(groups, list) or not groups:
        raise ValueError("navigation groups must be a nonempty list")
    ids: set[str] = set()
    registered: set[str] = set()
    for group in groups:
        if not isinstance(group, dict) or set(group) != {"id", "title", "purpose", "documents"}:
            raise ValueError("each group requires id, title, purpose and documents")
        identifier = group["id"]
        if not isinstance(identifier, str) or not re.fullmatch(r"[a-z]+(?:-[a-z]+)*", identifier):
            raise ValueError("group ids must be lowercase hyphenated names")
        if identifier in ids:
            raise ValueError(f"duplicate group: {identifier}")
        ids.add(identifier)
        for field in ("title", "purpose"):
            if not isinstance(group[field], str) or not group[field].strip():
                raise ValueError(f"group {identifier} needs {field}")
        if not isinstance(group["documents"], list) or not group["documents"]:
            raise ValueError(f"group {identifier} needs documents")
        for document in group["documents"]:
            if not isinstance(document, dict) or set(document) != {"path", "role", "owns"}:
                raise ValueError("each document requires path, role and owns")
            path = document["path"]
            if (
                not isinstance(path, str)
                or not re.fullmatch(r"[a-z0-9][a-z0-9./_-]*\.md", path)
                or any(part in {".", "..", ""} for part in path.split("/"))
            ):
                raise ValueError(f"invalid document path: {path}")
            rel = f"docs/{path}"
            if rel in registered:
                raise ValueError(f"document has multiple homes: {rel}")
            registered.add(rel)
            if document["role"] not in ROLES:
                raise ValueError(f"unknown role for {rel}: {document['role']}")
            if not isinstance(document["owns"], str) or not document["owns"].strip():
                raise ValueError(f"document needs a responsibility: {rel}")
    expected = public_documents(tracked)
    if registered != expected:
        raise ValueError(
            f"unclassified documents: {sorted(expected - registered)}; "
            f"untracked or excluded entries: {sorted(registered - expected)}"
        )
    return groups


def title(path: Path) -> str:
    """Use the document's title, never a truncated status sentence."""
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip().replace("|", "\\|")
    raise ValueError(f"document has no title: {path.relative_to(ROOT)}")


def render() -> str:
    tracked = tracked_documents()
    groups = validate_navigation(json.loads(NAVIGATION.read_text(encoding="utf-8")), tracked)
    decisions = [rel for rel in tracked if rel.startswith("docs/adr/")]
    total = sum(len(group["documents"]) for group in groups) + len(decisions)
    lines = [
        "# Documentation catalog",
        "",
        "Generated by `scripts/generate_docs_index.py` from [navigation.json](navigation.json).",
        "Edit the ownership map and source documents, then regenerate. Do not edit this file by hand.",
        "",
        "Start from the [documentation hub](README.md). Each document has one subject home and",
        "an explicit responsibility. A role describes how to use a document, not whether a feature",
        "is implemented. Contracts and scoped evidence establish capability claims.",
        "",
        f"**{total} documents** in the public catalog.",
        "",
    ]
    for group in groups:
        lines += [f"- [{group['title']}](#{group['id']})"]
    lines += ["- [Decision records](#decisions)", ""]
    for group in groups:
        lines += [
            f'<a id="{group["id"]}"></a>',
            "",
            f"## {group['title']}",
            "",
            group["purpose"],
            "",
            "| Document | Role | Owns |",
            "| --- | --- | --- |",
        ]
        for document in group["documents"]:
            path = document["path"]
            responsibility = document["owns"].replace("|", "\\|")
            lines.append(
                f"| [{title(ROOT / 'docs' / path)}]({path}) | {document['role']} | {responsibility} |"
            )
        lines.append("")
    lines += [
        '<a id="decisions"></a>',
        "",
        "## Decision records",
        "",
        "Decisions retain alternatives and rationale. Read the relevant living contract first;",
        "a record's original status is not proof of the implementation's present capability.",
        "",
        "| Record | Decision |",
        "| --- | --- |",
    ]
    for rel in decisions:
        path = Path(rel)
        lines.append(f"| [{path.stem}]({path.relative_to('docs')}) | {title(ROOT / rel)} |")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the catalog is out of date")
    arguments = parser.parse_args()
    try:
        rendered = render()
    except (ValueError, OSError) as error:
        print(f"documentation catalog: {error}")
        return 1
    if arguments.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print(f"{TARGET.relative_to(ROOT)} is out of date; run scripts/generate_docs_index.py")
            return 1
        print(f"{TARGET.relative_to(ROOT)} is current")
        return 0
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
