#!/usr/bin/env python3
"""Measure how much concurrent work one API process accepts, and what it answers past that.

    .exulanica/bin/quiet-slot .venv/bin/python scripts/measure_runtime_capacity.py run \
        --workload scripts/runtime_capacity_workload.json --phases knee,supported,overload \
        --out RECORD.json
    .venv/bin/python scripts/measure_runtime_capacity.py run \
        --workload scripts/runtime_capacity_workload.json --phases chaos --out RECORD.json

**The product runs as it is deployed.** A private PostgreSQL 18 made for the run and removed after
(``scripts/test_postgres.py``), provisioned by ``exulanica-db``'s own ``provision``; the API as the
image starts it, ``uvicorn --factory exulanica.api.app:create_app``, from this tree (the module path
is asserted before anything is measured), connecting as the non-owner runtime role with the
read-only executor role configured; ``EXULANICA_DERIVATIVE_WORKER=off`` and a dedicated derivative
worker process, as ``compose.yaml`` runs them. Every setting the workload names reaches the API
through its environment.

**One thing is scripted, and it is labelled.** The dedicated worker is the production
``DerivativeWorker`` (claims, leases, retries, ledger) with a vision model that sleeps a declared
time and returns a fixed observation, so a derivative job costs what a model call would cost in
time and nothing in money. It also records the synthetic screening each capture needs before the
vision stage runs; every photograph here is generated by this script. No request leaves the
machine.

**The workload** is a JSON file (``scripts/runtime_capacity_workload.json``) naming the ports, the
workspaces, the capacity settings and the phases. A record names the source tree and its digest,
the machine, the settings, the load and every observation, so another run on another tree is
comparable line by line. Phases:

*   ``knee``: small reads by closed loops at rising concurrency, for latency against concurrency.
*   ``supported``, ``overload``, ``sharing``: open-loop small reads, held progress streams, uploads
    whose progress is watched to its end, and (``sharing``) inhabited worlds played by the host.
*   ``chaos``: a client killed while it holds streams, requests cancelled mid-body, a stalled
    upload body, a held table lock, the derivative worker killed and paused past its lease, and the
    API restarted mid-stream. Each checks that slots come back, that every watched batch reaches one
    terminal outcome, that no event id arrives twice on one subscription, and that no workspace sees
    another's batch.

Server-side samples every half second: PostgreSQL client backends by role, the API process's
threads, resident memory and CPU, the derivative queue by state, and the admission counts
``/readyz`` reports. The machine's idle CPU share is read before and after (``top``, ten seconds)
and every five seconds during a run. Timing phases belong inside ``.exulanica/bin/quiet-slot``;
an overload phase needs root's saturation exception first.
"""

from __future__ import annotations

import argparse
import asyncio
import contextlib
import datetime as dt
import hashlib
import io
import itertools
import json
import math
import os
import platform
import random
import signal
import socket
import statistics
import subprocess
import sys
import tempfile
import threading
import time
import uuid
from collections import Counter, defaultdict
from collections.abc import Iterator
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

ROOT = Path.cwd()
PROFILE = "exulanica.runtime-capacity-record/v1"
WORKLOAD_PROFILE = "exulanica.runtime-capacity-workload/v1"
#: The synthetic photographs' generator, recorded with every screening this script makes.
GENERATOR = {"profile": "exulanica.runtime-capacity-photographs/v1", "notice": "SYNTHETIC"}
IDLE_SAMPLE_SECONDS = 10
SAMPLE_SECONDS = 0.5
#: Every photograph of a run is new bytes: a repeat would be deduplicated into work already done.
_PHOTO_SEEDS = itertools.count(1)


# -- where the code comes from ----------------------------------------------------------------


def _assert_tree() -> dict[str, Any]:
    """Refuse to measure anything but this tree, then name it: commit and uncommitted digest."""
    import exulanica

    resolved = Path(exulanica.__file__).resolve()
    if not resolved.is_relative_to(ROOT.resolve()):
        raise SystemExit(f"exulanica imports from {resolved}, not from {ROOT}; run from the tree")
    head = _git("rev-parse", "HEAD")
    diff = subprocess.run(
        ["git", "--no-optional-locks", "diff", "HEAD", "--binary"],
        capture_output=True,
        check=True,
        cwd=ROOT,
    ).stdout
    untracked = _git("ls-files", "--others", "--exclude-standard").split()
    digest = hashlib.sha256(diff)
    for name in sorted(untracked):
        digest.update(name.encode() + b"\0" + (ROOT / name).read_bytes())
    # What ran: the package and this harness, byte for byte, whatever happens to docs and tests.
    runtime = hashlib.sha256()
    for path in sorted(
        [
            *(ROOT / "exulanica").rglob("*.py"),
            *(ROOT / "exulanica").rglob("*.sql"),
            ROOT / "scripts/measure_runtime_capacity.py",
            ROOT / "pyproject.toml",
            ROOT / "uv.lock",
        ]
    ):
        runtime.update(str(path.relative_to(ROOT)).encode() + b"\0" + path.read_bytes())
    return {
        "head": head,
        "uncommitted_sha256": digest.hexdigest(),
        "runtime_sha256": runtime.hexdigest(),
        "changed_paths": sorted(set(_git("diff", "HEAD", "--name-only").split()) | set(untracked)),
    }


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", "--no-optional-locks", *args], capture_output=True, text=True, check=True, cwd=ROOT
    ).stdout.strip()


def _machine() -> dict[str, Any]:
    import importlib.metadata as metadata

    def sysctl(name: str) -> str:
        return subprocess.run(["sysctl", "-n", name], capture_output=True, text=True).stdout.strip()

    return {
        "system": platform.system(),
        "release": platform.release(),
        "cpu": sysctl("machdep.cpu.brand_string") if platform.system() == "Darwin" else None,
        "logical_cpus": os.cpu_count(),
        "memory_bytes": int(sysctl("hw.memsize") or 0) if platform.system() == "Darwin" else None,
        "python": platform.python_version(),
        "packages": {
            name: metadata.version(name)
            for name in ("fastapi", "starlette", "uvicorn", "anyio", "psycopg", "h11", "httpx")
        },
    }


def idle_share(seconds: int = IDLE_SAMPLE_SECONDS) -> float | None:
    """The CPU idle percentage over the next ``seconds``, from ``top``, or None off macOS."""
    if platform.system() != "Darwin":
        return None
    out = subprocess.run(
        ["top", "-l", "2", "-s", str(seconds), "-n", "0"], capture_output=True, text=True
    ).stdout
    lines = [line for line in out.splitlines() if line.startswith("CPU usage")]
    return float(lines[-1].split(",")[2].split("%")[0].strip()) if lines else None


def load_average() -> list[float]:
    return [round(value, 2) for value in os.getloadavg()]


def other_heavy_processes(limit: int = 8) -> list[dict[str, Any]]:
    """The busiest processes on the machine now, with their command's first word, for the record."""
    out = subprocess.run(
        ["ps", "-Ao", "pcpu=,pid=,comm="], capture_output=True, text=True
    ).stdout.splitlines()
    rows = []
    for line in out:
        parts = line.split(None, 2)
        if len(parts) == 3:
            with contextlib.suppress(ValueError):
                rows.append(
                    {"cpu": float(parts[0]), "pid": int(parts[1]), "command": Path(parts[2]).name}
                )
    return sorted(rows, key=lambda row: row["cpu"], reverse=True)[:limit]


# -- the stack --------------------------------------------------------------------------------


@dataclass
class Grant:
    workspace: uuid.UUID
    actor: uuid.UUID
    token: str


@dataclass
class Stack:
    """The database, the API process and the worker process, and how to reach each."""

    workload: dict[str, Any]
    run_dir: Path
    grants: list[Grant]
    owner_url: str = ""
    runtime_url: str = ""
    readonly_url: str = ""
    api: subprocess.Popen | None = None
    worker: subprocess.Popen | None = None
    extra_workers: list[subprocess.Popen] = field(default_factory=list)
    server: Any = None
    api_environment: dict[str, str] = field(default_factory=dict)

    @property
    def base_url(self) -> str:
        return f"http://127.0.0.1:{self.workload['ports']['api']}"

    def tokens(self) -> str:
        from exulanica.api.permissions import Permission

        return json.dumps(
            {
                grant.token: {
                    "workspace_id": str(grant.workspace),
                    "actor": str(grant.actor),
                    "permissions": [str(permission) for permission in Permission],
                }
                for grant in self.grants
            }
        )

    # database

    def start_database(self) -> None:
        sys.path.insert(0, str(ROOT / "scripts"))
        import test_postgres

        from exulanica.db.cli import provision
        from exulanica.db.migrate import provision_workspace
        from exulanica.db.roles import EXECUTOR_ROLE, RUNTIME_ROLE

        # Durable, as a deployment's server is: the harness default turns fsync off, which would
        # make every commit here cheaper than it is anywhere a person's data lives.
        test_postgres.SETTINGS.update(
            {"fsync": "on", "full_page_writes": "on", "max_connections": "100"}
        )
        test_postgres.sweep()
        server = test_postgres.Server(
            test_postgres.base_directory() / f"runtime-capacity-{os.getpid()}"
        )
        server.root.mkdir(parents=True)
        (server.root / "owner.pid").write_text(str(os.getpid()))
        self.server = server
        server.initialise()
        server.start(port=int(self.workload["ports"]["database"]))
        test_postgres.create_runtime_roles(server)
        self.owner_url = server.create_database("exulanica_runtime_capacity_test")
        previous = os.environ.get("EXULANICA_DATABASE_URL")
        os.environ["EXULANICA_DATABASE_URL"] = self.owner_url
        try:
            provision(io.StringIO())
        finally:
            if previous is None:
                os.environ.pop("EXULANICA_DATABASE_URL", None)
            else:
                os.environ["EXULANICA_DATABASE_URL"] = previous
        database = self.owner_url.rsplit("/", 1)[1]
        self.runtime_url = server.url(database, RUNTIME_ROLE)
        self.readonly_url = server.url(database, EXECUTOR_ROLE)
        import psycopg

        with psycopg.connect(self.owner_url, autocommit=True) as owner:
            for grant in self.grants:
                provision_workspace(owner, grant.workspace)

    # processes

    def environment(self, **extra: str) -> dict[str, str]:
        env = {
            key: value
            for key, value in os.environ.items()
            if not key.startswith("EXULANICA_") and key not in ("NEBIUS_API_KEY",)
        }
        env.update(
            {
                "EXULANICA_DATABASE_URL": self.runtime_url,
                "EXULANICA_READONLY_DATABASE_URL": self.readonly_url,
                "EXULANICA_DATA_DIR": str(self.run_dir / "data"),
                "EXULANICA_DERIVATIVE_WORKER": "off",
                "EXULANICA_API_TOKENS": self.tokens(),
                **{key: str(value) for key, value in self.workload.get("settings", {}).items()},
                **extra,
            }
        )
        return env

    def start_api(self, **extra: str) -> None:
        self.api_environment = self.environment(**extra)
        with open(self.run_dir / "api.log", "ab") as log:
            self.api = subprocess.Popen(
                [
                    str(ROOT / ".venv/bin/python"),
                    "-m",
                    "uvicorn",
                    "--factory",
                    "exulanica.api.app:create_app",
                    "--host",
                    "127.0.0.1",
                    "--port",
                    str(self.workload["ports"]["api"]),
                    "--no-access-log",
                    *self.workload.get("uvicorn_arguments", []),
                ],
                cwd=ROOT,
                env=self.api_environment,
                stdout=log,
                stderr=subprocess.STDOUT,
                start_new_session=True,
            )
        self.wait_ready()

    def wait_ready(self, timeout: float = 120.0) -> None:
        import httpx

        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if self.api is not None and self.api.poll() is not None:
                raise SystemExit(f"the API exited with {self.api.returncode}; see api.log")
            with contextlib.suppress(httpx.HTTPError):
                if httpx.get(self.base_url + "/readyz", timeout=5).json().get("ready"):
                    return
            time.sleep(0.5)
        raise SystemExit("the API did not become ready")

    def start_worker(self, name: str = "capacity-worker") -> subprocess.Popen:
        worker = self.workload["derivative_worker"]
        env = self.environment(
            EXULANICA_WORKSPACE_IDS=",".join(str(grant.workspace) for grant in self.grants)
        )
        with open(self.run_dir / f"{name}.log", "ab") as log:
            process = subprocess.Popen(
                [
                    str(ROOT / ".venv/bin/python"),
                    str(ROOT / "scripts/measure_runtime_capacity.py"),
                    "worker",
                    "--name",
                    name,
                    "--vision-seconds",
                    str(worker["vision_seconds"]),
                    "--poll-seconds",
                    str(worker["poll_seconds"]),
                ],
                cwd=ROOT,
                env=env,
                stdout=log,
                stderr=subprocess.STDOUT,
                start_new_session=True,
            )
        if self.worker is None:
            self.worker = process
        else:
            self.extra_workers.append(process)
        return process

    def stop_api(self, sig: int = signal.SIGTERM, timeout: float = 30.0) -> float:
        started = time.monotonic()
        if self.api is not None and self.api.poll() is None:
            self.api.send_signal(sig)
            try:
                self.api.wait(timeout)
            except subprocess.TimeoutExpired:
                self.api.kill()
                self.api.wait()
        return time.monotonic() - started

    def close(self) -> None:
        for process in [self.api, self.worker, *self.extra_workers]:
            if process is not None and process.poll() is None:
                with contextlib.suppress(ProcessLookupError):
                    os.kill(process.pid, signal.SIGCONT)
                process.terminate()
                try:
                    process.wait(20)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait()
        if self.server is not None:
            sys.path.insert(0, str(ROOT / "scripts"))
            import test_postgres

            test_postgres.remove_test_server(self.server)


@contextlib.contextmanager
def stack(workload: dict[str, Any], run_dir: Path) -> Iterator[Stack]:
    for port in workload["ports"].values():
        with socket.socket() as probe:
            if probe.connect_ex(("127.0.0.1", int(port))) == 0:
                raise SystemExit(f"port {port} is already in use; the run needs slot 1 free")
    grants = [
        Grant(uuid.uuid4(), uuid.uuid4(), f"capacity-{index}-{uuid.uuid4().hex}")
        for index in range(int(workload["workspaces"]))
    ]
    built = Stack(workload=workload, run_dir=run_dir, grants=grants)
    try:
        built.start_database()
        built.start_api()
        built.start_worker()
        yield built
    finally:
        built.close()


# -- the scripted worker ----------------------------------------------------------------------


def worker_main(argv: list[str]) -> int:
    """The production derivative worker with a vision model that sleeps and answers the same."""
    parser = argparse.ArgumentParser(prog="measure_runtime_capacity.py worker")
    parser.add_argument("--name", default="capacity-worker")
    parser.add_argument("--vision-seconds", type=float, default=1.0)
    parser.add_argument("--poll-seconds", type=float, default=1.0)
    args = parser.parse_args(argv)

    from exulanica.db.session import Database
    from exulanica.env import resolve_data_dir
    from exulanica.ingest.privacy import authorize_synthetic_capture, record_synthetic_exemption
    from exulanica.ingest.vision import VisionObservation, VisionResult
    from exulanica.ingest.worker import MINIMUM_LEASE_SECONDS, DerivativeWorker
    from exulanica.ingest.worker_command import parse_workspaces
    from exulanica.store.local import LocalContentAddressedStore

    observation = {
        "scene_description": "A generated test pattern of coloured blocks.",
        "objects": [{"label": "block", "salience": "primary", "confidence": "high", "box": None}],
        "legible_text": [],
        "proposed_place": None,
    }

    class ScriptedVision:
        """Answers after ``--vision-seconds``, as a model would, and never leaves the machine."""

        model_id = "MiniMaxAI/MiniMax-M3"

        def observe(self, *, image_bytes: bytes, media_type: str) -> VisionResult:
            time.sleep(args.vision_seconds)
            return VisionResult(
                observation=VisionObservation.model_validate(observation),
                payload=dict(observation),
                model_id=self.model_id,
                model_ref={"provider": "scripted", "model_id": self.model_id, "endpoint": "none"},
                cost={"input_tokens": 0, "output_tokens": 0, "usd_estimate": "0"},
                attempts=1,
                tried=(self.model_id,),
                latency_ms=int(args.vision_seconds * 1000),
            )

    class ScreeningWorker(DerivativeWorker):
        """Records each capture's synthetic screening before its job runs, then runs it as is."""

        def _run_job(self, repository, claimed, outcome, keeper):  # type: ignore[override]
            for capture_id in claimed.capture_ids:
                if repository.latest_privacy_screening(capture_id) is None:
                    with contextlib.suppress(Exception):
                        authorization = authorize_synthetic_capture(
                            repository,
                            capture_id=capture_id,
                            actor=uuid.UUID(int=1),
                            generator_manifest=GENERATOR,
                            authorization_scope={"purpose": "runtime capacity measurement"},
                        )
                        record_synthetic_exemption(
                            repository, authorization_id=authorization.authorization_id
                        )
            return super()._run_job(repository, claimed, outcome, keeper)

    environ = os.environ
    worker = ScreeningWorker(
        Database.from_env(environ),
        LocalContentAddressedStore(resolve_data_dir(environ) / "blobs"),
        parse_workspaces([], environ),
        vision=ScriptedVision(),
        name=args.name,
        poll_seconds=args.poll_seconds,
        lease_seconds=MINIMUM_LEASE_SECONDS,
    )
    stop = threading.Event()
    for received in (signal.SIGINT, signal.SIGTERM):
        signal.signal(received, lambda _n, _f: stop.set())
    worker.start()
    print(
        json.dumps({"event": "worker_started", "name": args.name, "pid": os.getpid()}), flush=True
    )
    while not stop.wait(0.5):
        if not worker.alive:
            print(json.dumps({"event": "worker_died", "error": worker.last_error}), flush=True)
            return 1
    worker.stop(timeout=30)
    return 0


# -- server-side samples ----------------------------------------------------------------------


class Sampler:
    """A thread that reads the server's side every half second while a phase runs."""

    def __init__(self, built: Stack) -> None:
        self.built = built
        self.samples: list[dict[str, Any]] = []
        self.idle: list[float] = []
        self._stop = threading.Event()
        self._threads = [
            threading.Thread(target=self._run, daemon=True),
            threading.Thread(target=self._idle, daemon=True),
        ]

    def __enter__(self) -> Sampler:
        for thread in self._threads:
            thread.start()
        return self

    def __exit__(self, *_exc: object) -> None:
        self._stop.set()
        for thread in self._threads:
            thread.join(20)

    def _idle(self) -> None:
        while not self._stop.is_set():
            value = idle_share(5)
            if value is not None:
                self.idle.append(value)

    def _run(self) -> None:
        import httpx
        import psycopg

        with (
            psycopg.connect(self.built.owner_url, autocommit=True) as owner,
            httpx.Client(timeout=10) as client,
        ):
            last_ready = 0.0
            while not self._stop.is_set():
                started = time.monotonic()
                sample: dict[str, Any] = {"t": time.time()}
                rows = owner.execute(
                    "select usename, count(*) from pg_stat_activity "
                    "where datname = current_database() and backend_type = 'client backend' "
                    "and pid <> pg_backend_pid() group by usename"
                ).fetchall()
                sample["backends"] = {name or "?": int(count) for name, count in rows}
                jobs = owner.execute("select state, count(*) from job group by state").fetchall()
                sample["jobs"] = {state: int(count) for state, count in jobs}
                api = self.built.api
                if api is not None and api.poll() is None:
                    sample["api"] = _process(api.pid)
                health_started = time.monotonic()
                with contextlib.suppress(httpx.HTTPError):
                    health = client.get(self.built.base_url + "/healthz")
                    sample["healthz_ms"] = round((time.monotonic() - health_started) * 1000, 2)
                    sample["healthz_status"] = health.status_code
                if time.monotonic() - last_ready >= 1.0:
                    last_ready = time.monotonic()
                    ready_started = time.monotonic()
                    with contextlib.suppress(httpx.HTTPError, ValueError):
                        client.get(self.built.base_url + "/readyz")
                        sample["readyz_ms"] = round((time.monotonic() - ready_started) * 1000, 2)
                    # The counts are an operator's read, so they are asked for as one: a request
                    # like any other, which a full requests class may refuse (recorded as such).
                    with contextlib.suppress(httpx.HTTPError, ValueError):
                        counts = client.get(
                            self.built.base_url + "/operations/capacity",
                            headers={"Authorization": f"Bearer {self.built.grants[0].token}"},
                        )
                        if counts.status_code == 200:
                            document = counts.json()
                            # This read is itself an admitted request: counted out here.
                            document["classes"]["requests"]["in_flight"] -= 1
                            sample["capacity"] = document
                        else:
                            sample["capacity_refused"] = counts.status_code
                self.samples.append(sample)
                self._stop.wait(max(0.0, SAMPLE_SECONDS - (time.monotonic() - started)))


def _process(pid: int) -> dict[str, Any]:
    """Threads, resident memory and CPU share of one process, from ``ps``.

    ``ps -M`` prints a header and then one line per thread.
    """
    threads = subprocess.run(
        ["ps", "-M", "-p", str(pid)], capture_output=True, text=True
    ).stdout.splitlines()
    usage = subprocess.run(
        ["ps", "-o", "rss=,%cpu=", "-p", str(pid)], capture_output=True, text=True
    ).stdout.split()
    return {
        "threads": max(0, len([line for line in threads if line.strip()]) - 1),
        "rss_kib": int(usage[0]) if usage else None,
        "cpu_percent": float(usage[1]) if len(usage) > 1 else None,
    }


def summarise_samples(samples: list[dict[str, Any]], idle: list[float]) -> dict[str, Any]:
    def peak(path: list[str]) -> Any:
        values = []
        for sample in samples:
            value: Any = sample
            for key in path:
                value = value.get(key) if isinstance(value, dict) else None
            if isinstance(value, int | float):
                values.append(value)
        return max(values) if values else None

    backends = [sum(sample.get("backends", {}).values()) for sample in samples]
    by_role: dict[str, int] = defaultdict(int)
    for sample in samples:
        for role, count in sample.get("backends", {}).items():
            by_role[role] = max(by_role[role], count)
    queued = [sample.get("jobs", {}).get("queued", 0) for sample in samples]
    running = [sample.get("jobs", {}).get("running", 0) for sample in samples]
    healthz = [sample["healthz_ms"] for sample in samples if "healthz_ms" in sample]
    readyz = [sample["readyz_ms"] for sample in samples if "readyz_ms" in sample]
    capacity_peaks: dict[str, int] = {}
    for sample in samples:
        classes = (sample.get("capacity") or {}).get("classes", {})
        for name, counts in classes.items():
            capacity_peaks[name] = max(capacity_peaks.get(name, 0), counts.get("in_flight", 0))
    last_capacity = next(
        (sample["capacity"] for sample in reversed(samples) if sample.get("capacity")), None
    )
    return {
        "samples": len(samples),
        "backends_peak": max(backends) if backends else None,
        "backends_peak_by_role": dict(by_role),
        "api_threads_peak": peak(["api", "threads"]),
        "api_rss_kib_peak": peak(["api", "rss_kib"]),
        "api_cpu_percent_peak": peak(["api", "cpu_percent"]),
        "queued_jobs_peak": max(queued) if queued else None,
        "running_jobs_peak": max(running) if running else None,
        "queued_jobs_last": queued[-1] if queued else None,
        "healthz_ms": spread(healthz),
        "healthz_failures": sum(
            1 for sample in samples if sample.get("healthz_status") not in (200, None)
        )
        + sum(1 for sample in samples if "healthz_ms" not in sample),
        "readyz_ms": spread(readyz),
        "in_flight_peaks": capacity_peaks,
        "capacity_at_end": last_capacity,
        "idle_percent_during": {
            "samples": len(idle),
            "mean": round(statistics.fmean(idle), 1) if idle else None,
            "minimum": min(idle) if idle else None,
        },
    }


def spread(values: list[float]) -> dict[str, Any]:
    """Count, p50, p95, p99 and maximum of exact values, nearest-rank."""
    if not values:
        return {"count": 0}
    ordered = sorted(values)

    def rank(q: float) -> float:
        return round(ordered[min(len(ordered) - 1, max(0, math.ceil(q * len(ordered)) - 1))], 2)

    return {
        "count": len(ordered),
        "p50": rank(0.50),
        "p95": rank(0.95),
        "p99": rank(0.99),
        "max": round(ordered[-1], 2),
    }


# -- the clients ------------------------------------------------------------------------------


@dataclass
class Observed:
    """What the clients saw, kept per request so any later question can be answered from it."""

    reads: list[dict[str, Any]] = field(default_factory=list)
    uploads: list[dict[str, Any]] = field(default_factory=list)
    streams: list[dict[str, Any]] = field(default_factory=list)

    def summary(self) -> dict[str, Any]:
        admitted = [r["ms"] for r in self.reads if r["status"] == 200]
        refused = [r["ms"] for r in self.reads if r["status"] in (429, 503)]
        codes = Counter(f"{r['status']} {r.get('code') or ''}".strip() for r in self.reads)
        upload_codes = Counter(f"{u['status']} {u.get('code') or ''}".strip() for u in self.uploads)
        stream_codes = Counter(
            f"{attempt.get('status')} {attempt.get('code') or ''}".strip()
            for stream in self.streams
            for attempt in stream.get("attempts", [])
        )
        lags = [lag for s in self.streams for lag in s.get("lag_ms", [])]
        watched = [s for s in self.streams if s.get("watch")]
        return {
            "reads": {
                "sent": len(self.reads),
                "admitted_ms": spread(admitted),
                "refused_ms": spread(refused),
                "by_status": dict(sorted(codes.items())),
                "unexpected": sorted(
                    {c for c in codes if c.split()[0] not in ("200", "429", "503")}
                ),
            },
            "uploads": {
                "sent": len(self.uploads),
                "ms": spread([u["ms"] for u in self.uploads if u["status"] == 202]),
                "by_status": dict(sorted(upload_codes.items())),
                "unexpected": sorted(
                    {c for c in upload_codes if c.split()[0] not in ("202", "409", "429", "503")}
                ),
                "photos_accepted": sum(u.get("accepted", 0) for u in self.uploads),
                "parts_busy": sum(u.get("busy", 0) for u in self.uploads),
            },
            "streams": {
                "subscriptions": len(self.streams),
                "attempts_by_status": dict(sorted(stream_codes.items())),
                "event_lag_ms": spread(lags),
                "watched_batches": len(watched),
                "watched_reached_terminal": sum(1 for s in watched if s.get("terminal")),
                "duplicate_event_ids": sum(s.get("duplicates", 0) for s in self.streams),
                "foreign_events": sum(s.get("foreign", 0) for s in self.streams),
            },
        }


def jpeg(width: int, height: int, seed: int) -> bytes:
    """A distinct synthetic photograph: random blocks, so every upload is new bytes."""
    from PIL import Image, ImageDraw

    rng = random.Random(seed)
    image = Image.new("RGB", (width, height), tuple(rng.randrange(256) for _ in range(3)))
    draw = ImageDraw.Draw(image)
    for _ in range(24):
        x, y = rng.randrange(width), rng.randrange(height)
        draw.rectangle(
            [x, y, x + rng.randrange(1, width // 3), y + rng.randrange(1, height // 3)],
            fill=tuple(rng.randrange(256) for _ in range(3)),
        )
    buffer = io.BytesIO()
    image.save(buffer, format="JPEG", quality=85)
    return buffer.getvalue()


class Clients:
    """One ``httpx.AsyncClient`` per workspace, and the behaviours a phase combines."""

    def __init__(self, built: Stack, observed: Observed, photo: dict[str, int]) -> None:
        import httpx

        limits = httpx.Limits(max_connections=None, max_keepalive_connections=64)
        self.built = built
        self.observed = observed
        self.photo = photo
        self.clients = {
            grant.token: httpx.AsyncClient(
                base_url=built.base_url,
                headers={"Authorization": f"Bearer {grant.token}"},
                limits=limits,
                timeout=httpx.Timeout(60.0, connect=10.0),
            )
            for grant in built.grants
        }
        self.batches_of: dict[str, set[str]] = defaultdict(set)

    async def close(self) -> None:
        for client in self.clients.values():
            await client.aclose()

    async def read(self, token: str, path: str, phase: str) -> None:
        import httpx

        started = time.perf_counter()
        entry: dict[str, Any] = {"phase": phase, "path": path, "at": time.time()}
        try:
            response = await self.clients[token].get(path)
            entry["status"] = response.status_code
            if response.status_code != 200:
                with contextlib.suppress(ValueError):
                    entry["code"] = response.json().get("code")
        except httpx.HTTPError as exc:
            entry["status"] = 0
            entry["code"] = type(exc).__name__
        entry["ms"] = round((time.perf_counter() - started) * 1000, 3)
        self.observed.reads.append(entry)

    async def reads_open_loop(self, token: str, rate: float, until: float, phase: str) -> None:
        """Poisson arrivals at ``rate`` per second, each sent without waiting for the last."""
        rng = random.Random(f"{token}:{phase}")
        tasks = []
        paths = ["/formation?limit=20", "/operations/derivative-jobs"]
        index = 0
        while time.monotonic() < until:
            await asyncio.sleep(rng.expovariate(rate))
            tasks.append(asyncio.create_task(self.read(token, paths[index % 2], phase)))
            index += 1
        await asyncio.gather(*tasks)

    async def reads_closed_loop(self, token: str, until: float, phase: str) -> None:
        paths = ["/formation?limit=20", "/operations/derivative-jobs"]
        index = 0
        while time.monotonic() < until:
            await self.read(token, paths[index % 2], phase)
            index += 1

    async def upload(self, token: str, photos: int, phase: str) -> str | None:
        import httpx

        files = []
        for _ in range(photos):
            seed = next(_PHOTO_SEEDS)
            files.append(
                (
                    "files",
                    (
                        f"p{seed}.jpg",
                        jpeg(self.photo["width"], self.photo["height"], seed),
                        "image/jpeg",
                    ),
                )
            )
        started = time.perf_counter()
        entry: dict[str, Any] = {"phase": phase, "at": time.time(), "photos": photos}
        batch = None
        try:
            response = await self.clients[token].post("/intake", files=files)
            entry["status"] = response.status_code
            try:
                body = response.json()
            except ValueError:
                # An answer outside the problem shape (a plain-text 500 ended the first overload
                # attempt) is a result to record, not a reason to stop the phase.
                entry["code"] = "non_json"
                entry["body_head"] = response.text[:200]
            else:
                if response.status_code == 202:
                    batch = body["batch_id"]
                    self.batches_of[token].add(batch)
                    entry["batch_id"] = batch
                    entry["accepted"] = len(body["accepted"])
                    entry["busy"] = sum(1 for part in body["refused"] if part["reason"] == "busy")
                else:
                    entry["code"] = body.get("code")
                    entry["retry_after"] = response.headers.get("retry-after")
        except httpx.HTTPError as exc:
            entry["status"] = 0
            entry["code"] = type(exc).__name__
        entry["ms"] = round((time.perf_counter() - started) * 1000, 3)
        self.observed.uploads.append(entry)
        return batch

    async def uploads_every(
        self, token: str, every: float, photos: int, until: float, phase: str, watchers: list
    ) -> None:
        rng = random.Random(f"{token}:uploads:{phase}")
        await asyncio.sleep(rng.uniform(0, every))
        while time.monotonic() < until:
            batch = await self.upload(token, photos, phase)
            if batch is not None:
                watchers.append(asyncio.create_task(self.stream(token, batch, phase, watch=True)))
            await asyncio.sleep(every)

    async def stream(
        self,
        token: str,
        batch: str,
        phase: str,
        *,
        watch: bool = False,
        until: float | None = None,
        max_seconds: float = 600.0,
    ) -> dict[str, Any]:
        """Subscribe to ``batch`` and resume as a client should until its outcome or ``until``.

        Records every attempt's status, every event id (a repeat on one subscription is a
        duplicate), the lag between an event's server time and its arrival, and any event whose
        batch is not this one.
        """
        import httpx

        record: dict[str, Any] = {
            "phase": phase,
            "batch_id": batch,
            "watch": watch,
            "attempts": [],
            "events": [],
            "lag_ms": [],
            "duplicates": 0,
            "foreign": 0,
            "terminal": None,
        }
        self.observed.streams.append(record)
        seen: set[str] = set()
        token_since: str | None = None
        deadline = time.monotonic() + max_seconds
        wait = 1.0
        while time.monotonic() < deadline and (until is None or time.monotonic() < until):
            params = {"since": token_since} if token_since else None
            attempt: dict[str, Any] = {"at": time.time()}
            record["attempts"].append(attempt)
            try:
                async with self.clients[token].stream(
                    "GET",
                    f"/formation/{batch}",
                    params=params,
                    timeout=httpx.Timeout(None, connect=10.0),
                ) as response:
                    attempt["status"] = response.status_code
                    if response.status_code != 200:
                        body = await response.aread()
                        with contextlib.suppress(ValueError):
                            attempt["code"] = json.loads(body).get("code")
                        retry = response.headers.get("retry-after")
                        if response.status_code in (429, 503):
                            await asyncio.sleep(float(retry) if retry else wait)
                            continue
                        break
                    wait = 1.0
                    async for line in response.aiter_lines():
                        if until is not None and time.monotonic() >= until:
                            break
                        if not line.startswith("data: "):
                            continue
                        event = json.loads(line[len("data: ") :])
                        event_id = event["eventId"]
                        if event_id in seen:
                            record["duplicates"] += 1
                        seen.add(event_id)
                        if event["captureId"] != batch:
                            record["foreign"] += 1
                        record["events"].append(event_id)
                        record["lag_ms"].append(max(0.0, time.time() * 1000 - event["at"]))
                        token_since = event_id
                        if event["stageIndex"] >= 6:
                            record["terminal"] = event_id
                    if record["terminal"] is not None:
                        break
            except httpx.HTTPError as exc:
                attempt["status"] = 0
                attempt["code"] = type(exc).__name__
                await asyncio.sleep(wait)
                wait = min(wait * 2, 15.0)
        record["lag_ms"] = [round(value, 1) for value in record["lag_ms"]]
        return record


# -- seeding ----------------------------------------------------------------------------------


def open_running_batches(built: Stack, per_workspace: int) -> dict[str, list[str]]:
    """Batches that stay running, one per held stream: what a watched upload in progress costs.

    Written directly, labelled, with no job: nothing will close them, so a stream on one stays
    open and polls for the whole phase, which is the cost being measured.
    """
    import psycopg

    held: dict[str, list[str]] = {}
    with psycopg.connect(built.owner_url, autocommit=True) as owner:
        for grant in built.grants:
            held[grant.token] = [
                str(
                    owner.execute(
                        "insert into intake_batch (workspace_id, label) values (%s, %s) "
                        "returning batch_id",
                        (grant.workspace, "runtime capacity: held stream"),
                    ).fetchone()[0]
                )
                for _ in range(per_workspace)
            ]
    return held


def close_held_batches(built: Stack) -> None:
    import psycopg

    with psycopg.connect(built.owner_url, autocommit=True) as owner:
        owner.execute(
            "update intake_batch set status = 'cancelled', ended_at = now() "
            "where label = 'runtime capacity: held stream' and status = 'running'"
        )


# -- phases -----------------------------------------------------------------------------------


async def phase_knee(built: Stack, spec: dict[str, Any]) -> dict[str, Any]:
    """Closed-loop small reads at each concurrency, spread over the workspaces."""
    steps = []
    for concurrency in spec["concurrency"]:
        observed = Observed()
        clients = Clients(built, observed, spec.get("photo", {"width": 64, "height": 48}))
        tokens = [grant.token for grant in built.grants]
        until = time.monotonic() + spec["seconds"]
        with Sampler(built) as sampler:
            await asyncio.gather(
                *(
                    clients.reads_closed_loop(tokens[index % len(tokens)], until, "knee")
                    for index in range(concurrency)
                )
            )
        await clients.close()
        summary = observed.summary()["reads"]
        steps.append(
            {
                "concurrency": concurrency,
                "seconds": spec["seconds"],
                "throughput_per_second": round(
                    sum(1 for r in observed.reads if r["status"] == 200) / spec["seconds"], 1
                ),
                **summary,
                "server": summarise_samples(sampler.samples, sampler.idle),
            }
        )
        print(
            f"knee c={concurrency}: {steps[-1]['throughput_per_second']}/s "
            f"p95={summary['admitted_ms'].get('p95')} refused={summary['refused_ms'].get('count', 0)}",
            flush=True,
        )
    return {"steps": steps}


async def phase_mixed(built: Stack, spec: dict[str, Any], name: str) -> dict[str, Any]:
    """Open-loop reads, held streams, and watched uploads, in every workspace at once."""
    per = spec["per_workspace"]
    held = open_running_batches(built, per.get("held_streams", 0))
    observed = Observed()
    clients = Clients(built, observed, spec["photo"])
    until = time.monotonic() + spec["seconds"]
    watchers: list[asyncio.Task] = []
    tasks = []
    holding: list[asyncio.Task] = []
    for grant in built.grants:
        for batch in held[grant.token]:
            holding.append(
                asyncio.ensure_future(clients.stream(grant.token, batch, name, until=until))
            )
        if per.get("reads_per_second"):
            tasks.append(clients.reads_open_loop(grant.token, per["reads_per_second"], until, name))
        if per.get("uploads_every_seconds"):
            tasks.append(
                clients.uploads_every(
                    grant.token,
                    per["uploads_every_seconds"],
                    per["photos_per_upload"],
                    until,
                    name,
                    watchers,
                )
            )
    with Sampler(built) as sampler:
        await asyncio.gather(*tasks, asyncio.sleep(max(0.0, until - time.monotonic())))
        # A held stream on a batch that never ends sends only heartbeats; it is left here.
        for task in holding:
            task.cancel()
        await asyncio.gather(*holding, return_exceptions=True)
        drain_until = time.monotonic() + spec.get("drain_seconds", 120)
        # The watched uploads finish after the load stops: their outcome is part of the result.
        while watchers and time.monotonic() < drain_until and not all(w.done() for w in watchers):
            await asyncio.sleep(0.5)
        for watcher in watchers:
            if not watcher.done():
                watcher.cancel()
        await asyncio.gather(*watchers, return_exceptions=True)
    close_held_batches(built)
    await clients.close()
    return {
        "seconds": spec["seconds"],
        "per_workspace": per,
        "workspaces": len(built.grants),
        "clients": observed.summary(),
        "server": summarise_samples(sampler.samples, sampler.idle),
    }


def make_towns(built: Stack, spec: dict[str, Any]) -> list[dict[str, Any]]:
    """A generated town with a living society in each of the first ``towns`` workspaces."""
    import httpx

    towns = []
    for grant in built.grants[: spec["towns"]]:
        client = httpx.Client(
            base_url=built.base_url, headers={"Authorization": f"Bearer {grant.token}"}, timeout=300
        )
        started = time.monotonic()
        made = client.post(
            "/worlds/generated", json={"recipe": spec["recipe"], "title": "runtime capacity town"}
        )
        made.raise_for_status()
        entry = made.json()
        scope = {"world_id": entry["world_id"]}
        version = entry["authored_version_id"]
        society = client.post(
            f"/world/versions/{version}/society",
            params=scope,
            json={"region_id": "region:generated", "profile": spec["profile"]},
        )
        society.raise_for_status()
        towns.append(
            {
                "token": grant.token,
                "workspace": str(grant.workspace),
                "version": version,
                "scope": scope,
                "made_seconds": round(time.monotonic() - started, 2),
            }
        )
        client.close()
    return towns


def play_towns(built: Stack, towns: list[dict[str, Any]], speed: int) -> None:
    import httpx

    for town in towns:
        client = httpx.Client(
            base_url=built.base_url,
            headers={"Authorization": f"Bearer {town['token']}"},
            timeout=60,
        )
        control = f"/world/versions/{town['version']}/society/control"
        read = client.get(control, params=town["scope"])
        read.raise_for_status()
        pressed = client.put(
            control,
            params=town["scope"],
            json={"base_revision": read.json()["revision"], "mode": "playing", "speed": speed},
        )
        pressed.raise_for_status()
        client.close()


def town_ticks(built: Stack, towns: list[dict[str, Any]]) -> list[int]:
    import httpx

    ticks = []
    for town in towns:
        read = httpx.get(
            built.base_url + f"/world/versions/{town['version']}/society/control",
            params=town["scope"],
            headers={"Authorization": f"Bearer {town['token']}"},
            timeout=60,
        )
        ticks.append(read.json().get("current_tick", -1) if read.status_code == 200 else -1)
    return ticks


async def traffic_reads(
    clients: Clients, town: dict[str, Any], every: float, until: float, phase: str
) -> None:
    path = (
        f"/world/versions/{town['version']}/traffic?world_id={town['scope']['world_id']}&seconds=60"
    )
    while time.monotonic() < until:
        await clients.read(town["token"], path, phase + ":traffic")
        await asyncio.sleep(every)


async def phase_sharing(built: Stack, spec: dict[str, Any], name: str) -> dict[str, Any]:
    """The supported load again, beside towns the host plays and pages reading their traffic."""
    towns = await asyncio.to_thread(make_towns, built, spec)
    listed = json.dumps([town["workspace"] for town in towns])
    await asyncio.to_thread(built.stop_api)
    await asyncio.to_thread(
        built.start_api,
        EXULANICA_SOCIETY_CONTROL_WORKSPACES=listed,
        EXULANICA_SOCIETY_TICK_INTERVAL_MS=str(spec.get("base_tick_interval_ms", 8000)),
    )
    await asyncio.to_thread(play_towns, built, towns, spec["speed"])
    await asyncio.sleep(spec.get("warmup_seconds", 20))
    ticks_before = await asyncio.to_thread(town_ticks, built, towns)
    started = time.monotonic()
    traffic_observed = Observed()
    traffic_clients = Clients(built, traffic_observed, spec["photo"])
    until = time.monotonic() + spec["seconds"]
    readers = [
        asyncio.ensure_future(
            traffic_reads(traffic_clients, town, spec["traffic_every_seconds"], until, name)
        )
        for town in towns
    ]
    mixed = await phase_mixed(built, spec, name)
    await asyncio.gather(*readers)
    await traffic_clients.close()
    ticks_after = await asyncio.to_thread(town_ticks, built, towns)
    wall = time.monotonic() - started
    traffic = [r for r in traffic_observed.reads]
    return {
        **mixed,
        "towns": {
            "count": len(towns),
            "recipe": spec["recipe"],
            "profile": spec["profile"],
            "speed": spec["speed"],
            "base_tick_interval_ms": spec.get("base_tick_interval_ms", 8000),
            "made_seconds": [town["made_seconds"] for town in towns],
            "ticks_advanced": [
                after - before for before, after in zip(ticks_before, ticks_after, strict=True)
            ],
            "wall_seconds": round(wall, 1),
        },
        "traffic_reads": {
            "sent": len(traffic),
            "ms": spread([r["ms"] for r in traffic if r["status"] == 200]),
            "by_status": dict(
                sorted(
                    Counter(f"{r['status']} {r.get('code') or ''}".strip() for r in traffic).items()
                )
            ),
        },
    }


# -- chaos ------------------------------------------------------------------------------------


def capacity(built: Stack) -> dict[str, Any]:
    import httpx

    return httpx.get(
        built.base_url + "/operations/capacity",
        headers={"Authorization": f"Bearer {built.grants[-1].token}"},
        timeout=10,
    ).json()


def wait_for(condition, timeout: float, step: float = 0.1) -> float | None:
    """Seconds until ``condition()`` holds, or None when it did not within ``timeout``."""
    started = time.monotonic()
    while time.monotonic() - started < timeout:
        with contextlib.suppress(Exception):
            if condition():
                return round(time.monotonic() - started, 3)
        time.sleep(step)
    return None


def in_flight(built: Stack, name: str) -> int:
    """In flight in ``name`` now, not counting the capacity read itself, which is a request."""
    held = capacity(built)["classes"][name]["in_flight"]
    return held - 1 if name == "requests" else held


def hold_main(argv: list[str]) -> int:
    """A client that opens streams and holds them until it is killed."""
    parser = argparse.ArgumentParser(prog="measure_runtime_capacity.py hold")
    parser.add_argument("--port", type=int, required=True)
    parser.add_argument("--stream", action="append", required=True, help="TOKEN:BATCH")
    args = parser.parse_args(argv)
    held = []
    for pair in args.stream:
        token, batch = pair.split(":", 1)
        connection = socket.create_connection(("127.0.0.1", args.port))
        connection.sendall(
            f"GET /formation/{batch} HTTP/1.1\r\nHost: 127.0.0.1\r\n"
            f"Authorization: Bearer {token}\r\nAccept: text/event-stream\r\n\r\n".encode()
        )
        held.append(connection)
    print(json.dumps({"event": "holding", "streams": len(held)}), flush=True)
    while True:
        time.sleep(1)


def raw_request(
    built: Stack, head: str, body: bytes = b"", *, close_after: float | None = None
) -> socket.socket:
    connection = socket.create_connection(("127.0.0.1", int(built.workload["ports"]["api"])))
    connection.sendall(head.encode() + body)
    if close_after is not None:
        time.sleep(close_after)
        connection.close()
    return connection


def chaos(built: Stack, spec: dict[str, Any]) -> dict[str, Any]:
    results: dict[str, Any] = {}
    token = built.grants[0].token
    other = built.grants[1].token

    # 1. A client killed while it holds streams: its slots come back. Streams spread over
    # workspaces, each within its share, so the whole count is admitted.
    share = int(built.workload["settings"].get("EXULANICA_API_WORKSPACE_STREAMS", 8))
    wanted = spec["killed_client_streams"]
    holders = built.grants[: max(1, math.ceil(wanted / share))]
    held_by = open_running_batches(built, share)
    pairs = [f"{grant.token}:{batch}" for grant in holders for batch in held_by[grant.token]][
        :wanted
    ]
    child = subprocess.Popen(
        [
            str(ROOT / ".venv/bin/python"),
            str(ROOT / "scripts/measure_runtime_capacity.py"),
            "hold",
            "--port",
            str(built.workload["ports"]["api"]),
            *[part for pair in pairs for part in ("--stream", pair)],
        ],
        cwd=ROOT,
        stdout=subprocess.PIPE,
        text=True,
        start_new_session=True,
    )
    opened = wait_for(lambda: in_flight(built, "streams") >= len(pairs), 30)
    killed_at = time.monotonic()
    os.kill(child.pid, signal.SIGKILL)
    child.wait()
    released = wait_for(lambda: in_flight(built, "streams") == 0, 30)
    results["killed_client"] = {
        "streams": len(pairs),
        "workspaces": len(holders),
        "all_admitted_after_s": opened,
        "released_after_kill_s": released,
        "kill_to_check_s": round(time.monotonic() - killed_at, 3),
    }
    close_held_batches(built)

    # 2. Requests cancelled mid-body, and a read cancelled before its answer: slots come back.
    upload = raw_request(
        built,
        "POST /intake HTTP/1.1\r\nHost: 127.0.0.1\r\n"
        f"Authorization: Bearer {token}\r\nContent-Type: multipart/form-data; boundary=x\r\n"
        "Content-Length: 10485760\r\n\r\n",
        b'--x\r\nContent-Disposition: form-data; name="files"; filename="a.jpg"\r\n'
        b"Content-Type: image/jpeg\r\n\r\n" + b"0" * 65536,
    )
    upload_held = wait_for(lambda: in_flight(built, "uploads") == 1, 10)
    upload.close()
    upload_released = wait_for(lambda: in_flight(built, "uploads") == 0, 30)
    read = raw_request(
        built,
        "POST /world/versions HTTP/1.1\r\nHost: 127.0.0.1\r\n"
        f"Authorization: Bearer {token}\r\nContent-Type: application/json\r\n"
        "Content-Length: 100000\r\n\r\n",
        b"{",
    )
    read_held = wait_for(lambda: in_flight(built, "requests") == 1, 10)
    read.close()
    read_released = wait_for(lambda: in_flight(built, "requests") == 0, 30)
    results["cancelled"] = {
        "upload_in_flight_after_s": upload_held,
        "upload_released_after_close_s": upload_released,
        "request_in_flight_after_s": read_held,
        "request_released_after_close_s": read_released,
    }

    # 3. Stalled upload bodies hold the uploads class until their idle deadline, then 408.
    stalled = []
    for _ in range(int(built.workload["settings"].get("EXULANICA_API_UPLOADS", 2))):
        stalled.append(
            raw_request(
                built,
                "POST /intake HTTP/1.1\r\nHost: 127.0.0.1\r\n"
                f"Authorization: Bearer {token}\r\nContent-Type: multipart/form-data; boundary=x\r\n"
                "Content-Length: 1048576\r\n\r\n",
                b"--x\r\n",
            )
        )
    full = wait_for(lambda: in_flight(built, "uploads") >= len(stalled), 10)
    import httpx

    refused_upload = httpx.post(
        built.base_url + "/intake",
        headers={"Authorization": f"Bearer {other}"},
        files=[("files", ("x.jpg", jpeg(64, 48, 1), "image/jpeg"))],
        timeout=30,
    )
    started = time.monotonic()
    answers = []
    for connection in stalled:
        connection.settimeout(60)
        with contextlib.suppress(OSError):
            answers.append(connection.recv(4096).split(b"\r\n", 1)[0].decode())
        connection.close()
    results["stalled_bodies"] = {
        "held": len(stalled),
        "class_full_after_s": full,
        "other_upload_meanwhile": [refused_upload.status_code, refused_upload.json().get("code")],
        "answered": answers,
        "answered_after_s": round(time.monotonic() - started, 2),
        "released_after_s": wait_for(lambda: in_flight(built, "uploads") == 0, 30),
    }

    # 4. A held table lock: reads that need it wait, the rest are refused fast, streams carry on.
    results["held_lock"] = asyncio.run(_held_lock(built, spec))

    # 5. The worker killed mid-batch, then restarted: the batch reaches one outcome.
    results["worker_killed"] = asyncio.run(_worker_interrupted(built, spec, pause=False))

    # 6. The worker paused past its lease while another reclaims its job (concurrent writers).
    results["worker_paused"] = asyncio.run(_worker_interrupted(built, spec, pause=True))

    # 7. The API restarted mid-stream: clients resume and reach the same outcome.
    results["api_restarted"] = asyncio.run(_api_restarted(built, spec))
    return results


async def _held_lock(built: Stack, spec: dict[str, Any]) -> dict[str, Any]:
    import psycopg

    observed = Observed()
    clients = Clients(built, observed, {"width": 64, "height": 48})
    held = open_running_batches(built, 4)
    until = time.monotonic() + spec["lock_seconds"] + 20
    holding = [
        asyncio.ensure_future(clients.stream(grant.token, batch, "held_lock", until=until))
        for grant in built.grants[:2]
        for batch in held[grant.token]
    ]
    tasks = [clients.reads_open_loop(grant.token, 5, until, "held_lock") for grant in built.grants]

    def lock() -> None:
        time.sleep(5)
        with psycopg.connect(built.owner_url) as connection, connection.transaction():
            connection.execute("lock table intake_batch in access exclusive mode")
            time.sleep(spec["lock_seconds"])

    locker = threading.Thread(target=lock)
    with Sampler(built) as sampler:
        locker.start()
        await asyncio.gather(*tasks)
        for task in holding:
            task.cancel()
        await asyncio.gather(*holding, return_exceptions=True)
        await asyncio.to_thread(locker.join)
    close_held_batches(built)
    await clients.close()
    released = wait_for(
        lambda: all(c["in_flight"] == 0 for c in capacity(built)["classes"].values()), 60
    )
    return {
        "lock_seconds": spec["lock_seconds"],
        "clients": observed.summary(),
        "server": summarise_samples(sampler.samples, sampler.idle),
        "all_released_after_s": released,
    }


async def _worker_interrupted(built: Stack, spec: dict[str, Any], *, pause: bool) -> dict[str, Any]:
    """Kill (or pause) the worker once a watched batch has started, and follow it to its end."""
    import psycopg

    observed = Observed()
    clients = Clients(built, observed, spec["photo"])
    token = built.grants[2].token
    batch = await clients.upload(token, spec["interrupted_batch_photos"], "interrupted")
    watcher = asyncio.create_task(
        clients.stream(token, batch, "interrupted", watch=True, max_seconds=900)
    )
    worker = built.worker
    started_capture = await asyncio.to_thread(
        wait_for,
        lambda: _ledger_events(built, batch) >= 2,
        120,
    )
    moment = time.monotonic()
    if pause:
        os.kill(worker.pid, signal.SIGSTOP)
    else:
        os.kill(worker.pid, signal.SIGKILL)
        worker.wait()
    replacement = built.start_worker(
        name="capacity-worker-" + ("reclaimer" if pause else "restarted")
    )
    resumed = None
    if pause:
        # Past its lease, the paused worker's job is reclaimed; then it wakes and writes on.
        await asyncio.sleep(75)
        os.kill(worker.pid, signal.SIGCONT)
        resumed = round(time.monotonic() - moment, 1)
    record = await watcher
    with psycopg.connect(built.owner_url, autocommit=True) as owner:
        ledger = [
            str(row[0])
            for row in owner.execute(
                "select pe.event_id from pipeline_event pe join pipeline_run pr on pr.run_id = pe.run_id "
                "where pr.batch_id = %s order by pe.event_id",
                (batch,),
            ).fetchall()
        ]
        batch_row = owner.execute(
            "select status, ended_at from intake_batch where batch_id = %s", (batch,)
        ).fetchone()
        jobs = owner.execute(
            "select state, attempts from job where batch_id = %s", (batch,)
        ).fetchall()
        delivery = [
            {"worker": worker, "event": event, "attempt": attempt, "at": at.isoformat()}
            for worker, event, attempt, at in owner.execute(
                "select e.worker_id, e.event_type, e.attempt, e.occurred_at "
                "from derivative_job_event e join job j on j.job_id = e.job_id "
                "where j.batch_id = %s and e.event_type <> 'lease_renewed' "
                "order by e.occurred_at, e.event_id",
                (batch,),
            ).fetchall()
        ]
    # Every ledger event the projection would stream, against what this subscription received.
    replay = await clients.stream(token, batch, "replay", watch=False)
    await clients.close()
    if not pause:
        built.worker = replacement
        built.extra_workers.remove(replacement)
    streamed = set(record["events"])
    replayed = set(replay["events"])
    return {
        "photos": spec["interrupted_batch_photos"],
        "interrupted_after_ledger_events": started_capture,
        "paused_for_s": resumed,
        "terminal_streamed": record["terminal"],
        "terminal_replayed": replay["terminal"],
        "batch": {"status": batch_row[0], "ended": batch_row[1] is not None},
        "jobs": [{"state": state, "attempts": attempts} for state, attempts in jobs],
        "delivery_events": delivery,
        "subscription_attempts": [a.get("status") for a in record["attempts"]],
        "duplicates": record["duplicates"],
        "foreign": record["foreign"],
        "streamed_events": len(streamed),
        "replayed_events": len(replayed),
        "missed_by_live_stream": sorted(replayed - streamed),
        "ledger_events": len(ledger),
    }


def _ledger_events(built: Stack, batch: str) -> int:
    import psycopg

    with psycopg.connect(built.owner_url, autocommit=True) as owner:
        return int(
            owner.execute(
                "select count(*) from pipeline_event pe join pipeline_run pr on pr.run_id = pe.run_id "
                "where pr.batch_id = %s and pe.stage_key in ('rendition', 'vision')",
                (batch,),
            ).fetchone()[0]
        )


async def _api_restarted(built: Stack, spec: dict[str, Any]) -> dict[str, Any]:
    observed = Observed()
    clients = Clients(built, observed, spec["photo"])
    tokens = [grant.token for grant in built.grants[3:5]]
    batches = [
        await clients.upload(token, spec["interrupted_batch_photos"], "restart") for token in tokens
    ]
    watchers = [
        asyncio.create_task(clients.stream(t, b, "restart", watch=True, max_seconds=600))
        for t, b in zip(tokens, batches, strict=True)
    ]
    await asyncio.sleep(3)
    stopped = await asyncio.to_thread(built.stop_api, signal.SIGKILL)
    down_at = time.monotonic()
    await asyncio.to_thread(built.start_api)
    back = round(time.monotonic() - down_at, 2)
    records = await asyncio.gather(*watchers)
    await clients.close()
    return {
        "stopped_in_s": round(stopped, 2),
        "back_after_s": back,
        "batches": [
            {
                "terminal": record["terminal"],
                "attempts": [a.get("status") for a in record["attempts"]],
                "duplicates": record["duplicates"],
                "foreign": record["foreign"],
            }
            for record in records
        ],
    }


# -- the run ----------------------------------------------------------------------------------


def run_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="measure_runtime_capacity.py run")
    parser.add_argument(
        "--workload", type=Path, default=ROOT / "scripts/runtime_capacity_workload.json"
    )
    parser.add_argument("--phases", default="knee,supported")
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--idle-gate", type=float, default=70.0)
    parser.add_argument("--saturation-approved", action="store_true")
    parser.add_argument(
        "--announce",
        type=Path,
        help="a coordination file the start and end of a saturation phase are appended to",
    )
    args = parser.parse_args(argv)

    workload = json.loads(args.workload.read_text())
    if workload.get("profile") != WORKLOAD_PROFILE:
        raise SystemExit(f"{args.workload} is not a {WORKLOAD_PROFILE} file")
    phases = [name.strip() for name in args.phases.split(",") if name.strip()]
    unknown = [name for name in phases if name not in workload["phases"] and name != "chaos"]
    if unknown:
        raise SystemExit(f"the workload names no phase {unknown}")
    if (
        any(workload["phases"].get(name, {}).get("saturation") for name in phases)
        and not args.saturation_approved
    ):
        raise SystemExit(
            "an overload phase needs root's saturation exception: pass --saturation-approved"
        )

    record: dict[str, Any] = {
        "profile": PROFILE,
        "started_at": dt.datetime.now(dt.UTC).isoformat(timespec="seconds"),
        "tree": _assert_tree(),
        "machine": _machine(),
        "workload": workload,
        "workload_sha256": hashlib.sha256(args.workload.read_bytes()).hexdigest(),
        "phases_requested": phases,
        "nice": os.nice(0),
        "notes": [
            "Measured on one machine with every process local; latency excludes any network.",
            "The derivative worker's vision model is scripted (fixed sleep, fixed answer, no network).",
            "PostgreSQL runs with fsync on, max_connections 100 and shared_buffers 128MB.",
        ],
    }
    timing = any(name != "chaos" for name in phases)
    record["idle_before_percent"] = idle_share()
    record["load_before"] = load_average()
    record["busiest_before"] = other_heavy_processes()
    if timing and (record["idle_before_percent"] or 0) < args.idle_gate:
        record["refused"] = (
            f"idle {record['idle_before_percent']}% is under the {args.idle_gate}% gate"
        )
        args.out.write_text(json.dumps(record, indent=1, sort_keys=True) + "\n")
        print(record["refused"], flush=True)
        return 3
    run_dir = Path(tempfile.mkdtemp(prefix="runtime-capacity-"))
    record["run_dir"] = str(run_dir)
    results: dict[str, Any] = {}
    try:
        with stack(workload, run_dir) as built:
            record["api_module_nice"] = subprocess.run(
                ["ps", "-o", "ni=", "-p", str(built.api.pid)], capture_output=True, text=True
            ).stdout.strip()
            for name in phases:
                print(f"phase {name} at {dt.datetime.now().strftime('%H:%M:%S')}", flush=True)
                saturating = bool(workload["phases"].get(name, {}).get("saturation"))
                if saturating and args.announce:
                    _announce(
                        args.announce,
                        f"saturation window START, phase {name}, load {load_average()}",
                    )
                started = time.monotonic()
                stopped = None
                try:
                    if name == "chaos":
                        results[name] = chaos(built, workload["chaos"])
                    elif workload["phases"][name]["kind"] == "sharing":
                        results[name] = asyncio.run(
                            phase_sharing(built, workload["phases"][name], name)
                        )
                    elif workload["phases"][name]["kind"] == "closed_reads":
                        results[name] = asyncio.run(phase_knee(built, workload["phases"][name]))
                    else:
                        results[name] = asyncio.run(
                            phase_mixed(built, workload["phases"][name], name)
                        )
                except BaseException as exc:
                    stopped = type(exc).__name__
                    raise
                finally:
                    # The window's end is announced however the phase ends, so a phase that
                    # stops early never leaves a saturation window open in the coordination file.
                    wall, load_now = round(time.monotonic() - started, 1), load_average()
                    if saturating and args.announce:
                        how = f"stopped early by {stopped}, " if stopped else ""
                        _announce(
                            args.announce,
                            f"saturation window END, phase {name}, {how}{wall} s, load {load_now}",
                        )
                results[name]["wall_seconds"] = wall
                results[name]["load_after"] = load_now
    finally:
        record["results"] = results
        record["idle_after_percent"] = idle_share()
        record["load_after"] = load_average()
        record["finished_at"] = dt.datetime.now(dt.UTC).isoformat(timespec="seconds")
        args.out.write_text(json.dumps(record, indent=1, sort_keys=True, default=str) + "\n")
        print(f"wrote {args.out}", flush=True)
    return 0


def _announce(path: Path, text: str) -> None:
    stamp = dt.datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %Z")
    with path.open("a") as handle:
        handle.write(f"\nR1 -> ROOT, {stamp}, {text}\n")


def main() -> int:
    if len(sys.argv) < 2 or sys.argv[1] not in ("run", "worker", "hold"):
        print(__doc__)
        return 2
    command, rest = sys.argv[1], sys.argv[2:]
    if command == "worker":
        return worker_main(rest)
    if command == "hold":
        return hold_main(rest)
    return run_main(rest)


if __name__ == "__main__":
    raise SystemExit(main())
