"""Prepare or verify the catalog-driven people family and the combined character catalog.

    uv run python scripts/prepare_character_people.py --blender PATH [--source DIR]
    uv run python scripts/prepare_character_people.py --looks
    uv run python scripts/prepare_character_people.py --verify-only
    uv run python scripts/prepare_character_people.py --import [--apply] [--data-dir DIR]

Building needs the pinned Blender 4.5.9 and the pinned MPFB 2 source and MakeHuman system
assets (see assets/characters/makehuman-parametric-v1/source-lock.json); nothing is fetched.
`--looks` validates the authored designed looks (assets/characters/looks.json) against the
catalog and rewrites their TypeScript module. Verification needs only the repository: every
catalog entry's bytes, digests and import manifests are checked, no container in a catalog
family's folder goes unreferenced, and both TypeScript modules are compared with their JSON.
`--import --apply` publishes every container through the reviewed asset registry, which is how
a deployment serves them at /world/assets/<asset key>/bytes.
"""

import argparse
import hashlib
import json
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(ROOT / "scripts/character_catalog"))

import people  # noqa: E402
from parametric_character.inputs import verify_inputs  # noqa: E402

CATALOG = ROOT / "assets/characters/catalog.json"
TS_CATALOG = ROOT / "web/packages/atlas-react/src/playcanvas/character/catalog-data.ts"
LOOKS = ROOT / "assets/characters/looks.json"
TS_LOOKS = ROOT / "web/packages/atlas-react/src/playcanvas/character/looks-data.ts"
CATALOG_ID = "exulanica-characters"
CATALOG_REVISION = 2
TS_HEADER = """// Generated by scripts/prepare_character_people.py from assets/characters/catalog.json.
// Do not edit: character-catalog-data.test.ts fails when this differs from the JSON.
import { validateCharacterCatalog, type CharacterCatalog } from './catalog.js';

export const CHARACTER_CATALOG_JSON = """
TS_LOOKS_HEADER = """// Generated by scripts/prepare_character_people.py from assets/characters/looks.json.
// Do not edit: character-catalog-data.test.ts fails when this differs from the JSON.
import { CHARACTER_CATALOG } from './catalog-data.js';
import { validateDesignedLooks, type DesignedLooks } from './look.js';

export const DESIGNED_LOOKS_JSON = """


def catalog_document(family, population):
    return {
        "profile": "exulanica.character-catalog/v1",
        "catalogId": CATALOG_ID,
        "revision": CATALOG_REVISION,
        "families": [family],
        "population": [population],
    }


def write_catalog(document):
    text = json.dumps(document, indent=1, sort_keys=True) + "\n"
    CATALOG.write_text(text)
    TS_CATALOG.write_text(
        TS_HEADER
        + json.dumps(json.dumps(document, sort_keys=True, separators=(",", ":")))
        + ";\n\nexport const CHARACTER_CATALOG: CharacterCatalog = validateCharacterCatalog(\n"
        + "  JSON.parse(CHARACTER_CATALOG_JSON) as CharacterCatalog,\n);\n"
    )


def looks_module(looks):
    return (
        TS_LOOKS_HEADER
        + json.dumps(json.dumps(looks, sort_keys=True, separators=(",", ":")))
        + ";\n\nexport const DESIGNED_LOOKS: DesignedLooks = validateDesignedLooks(\n"
        + "  CHARACTER_CATALOG,\n  JSON.parse(DESIGNED_LOOKS_JSON) as DesignedLooks,\n);\n"
    )


def write_looks(document=None):
    """Validate the designed looks against the catalog and rewrite their TypeScript module."""
    from exulanica.world.character_appearance import catalog_recipe_families

    document = document or json.loads(CATALOG.read_text())
    looks = json.loads(LOOKS.read_text())
    catalog_recipe_families(document, looks)
    TS_LOOKS.write_text(looks_module(looks))
    return len(looks["looks"])


def unreferenced_containers(document):
    """Containers inside a catalog family's folder that no catalog entry names."""
    characters = ROOT / "assets/characters"
    named = {asset["file"] for asset in iter_assets(document)}
    folders = {Path(family["licence"]["file"]).parent for family in document["families"]}
    return sorted(
        path.relative_to(characters).as_posix()
        for folder in folders
        for path in (characters / folder).rglob("*.glb")
        if path.relative_to(characters).as_posix() not in named
    )


def iter_assets(document):
    for family in document["families"]:
        for base in family["bases"]:
            yield base["asset"]
            for part in base["parts"]:
                if "asset" in part:
                    yield part["asset"]
        for material in family["materials"]:
            yield material["asset"]


def catalog_imports(document=None):
    """Every catalog container with its reviewed import manifest and licence, each verified."""
    from exulanica.world.asset_import import ReviewedAssetImport, validate_asset_import

    document = document or json.loads(CATALOG.read_text())
    characters = ROOT / "assets/characters"
    imports = {}
    for family in document["families"]:
        licence_path = characters / family["licence"]["file"]
        licence = licence_path.read_bytes()
        if hashlib.sha256(licence).hexdigest() != family["licence"]["sha256"]:
            raise ValueError(f"{family['familyId']} licence digest changed")
        manifest_file = licence_path.parent / "imports.json"
        for manifest in json.loads(manifest_file.read_text()):
            imports[manifest["asset_key"]] = (ReviewedAssetImport.model_validate(manifest), licence)
    verified = []
    for asset in iter_assets(document):
        payload = (characters / asset["file"]).read_bytes()
        if (
            len(payload) != asset["byteSize"]
            or hashlib.sha256(payload).hexdigest() != asset["contentSha256"]
        ):
            raise ValueError(f"{asset['file']} does not match the catalog")
        manifest, licence = imports[asset["assetKey"]]
        validate_asset_import(manifest, payload, licence)
        verified.append((manifest, payload, licence))
    return verified


def import_catalog(connection, store, document=None):
    """Publish every catalog container as a reviewed asset, in the caller's transaction.

    Import is append-only and idempotent: a key already published with the same bytes and
    receipt is left as it is, and a key bound to anything else refuses the whole batch.
    """
    from exulanica.world.asset_import import import_reviewed_asset
    from exulanica.world.asset_kinds import AssetKind

    imports = catalog_imports(document)
    for manifest, payload, licence in imports:
        import_reviewed_asset(
            connection, store, manifest, payload, licence, kind=AssetKind.COMPONENT
        )
    return len(imports)


def verify(document=None):
    """Raise unless every catalog asset matches its bytes and reviewed import manifest."""
    document = document or json.loads(CATALOG.read_text())
    count = len(catalog_imports(document))
    expected = TS_HEADER + json.dumps(json.dumps(document, sort_keys=True, separators=(",", ":")))
    if not TS_CATALOG.read_text().startswith(expected):
        raise ValueError("catalog-data.ts is stale; rerun the preparation")
    unreferenced = unreferenced_containers(document)
    if unreferenced:
        raise ValueError(f"containers no catalog entry names: {', '.join(unreferenced)}")
    from exulanica.world.character_appearance import catalog_recipe_families

    looks = json.loads(LOOKS.read_text())
    catalog_recipe_families(document, looks)
    if TS_LOOKS.read_text() != looks_module(looks):
        raise ValueError("looks-data.ts is stale; rerun with --looks")
    return count


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--blender", type=Path)
    parser.add_argument(
        "--source",
        type=Path,
        default=ROOT / ".exulanica/briefs/parametric-human",
        help="directory holding the pinned mpfb2 checkout and extracted system-assets",
    )
    parser.add_argument("--workdir", type=Path)
    parser.add_argument("--verify-only", action="store_true")
    parser.add_argument("--looks", action="store_true", help="rewrite the designed looks module")
    parser.add_argument(
        "--import",
        dest="publish",
        action="store_true",
        help="publish every catalog container as a reviewed asset (with --apply)",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="with --import: write to EXULANICA_DATABASE_URL and the store; otherwise validate",
    )
    parser.add_argument("--data-dir", type=Path)
    args = parser.parse_args()
    if args.looks:
        print(f"Wrote {write_looks()} designed looks")
        return
    if args.publish:
        if not args.apply:
            print(f"Validated {len(catalog_imports())} character containers for import")
            return
        import psycopg

        from exulanica.env import env_get, resolve_data_dir
        from exulanica.store.local import LocalContentAddressedStore

        url = env_get("DATABASE_URL")
        if not url:
            parser.error("EXULANICA_DATABASE_URL is required for publication")
        store = LocalContentAddressedStore(resolve_data_dir(explicit=args.data_dir) / "blobs")
        with psycopg.connect(url) as connection, connection.transaction():
            print(f"Published {import_catalog(connection, store)} character containers")
        return
    if args.verify_only:
        print(f"Verified {verify()} character assets")
        return
    if not args.blender:
        parser.error("--blender is required to build")
    family_lock = ROOT / "assets/characters/makehuman-parametric-v1"
    inputs = verify_inputs(args.source.resolve(), args.blender.resolve(), family_lock)
    workdir = args.workdir or Path(tempfile.mkdtemp(prefix="people-"))
    family, population, manifests = people.prepare(
        args.source.resolve(), args.blender.resolve(), workdir, inputs=inputs
    )
    document = catalog_document(family, population)
    write_catalog(document)
    write_looks(document)
    print(f"Prepared {len(manifests)} people assets; verified {verify(document)}")


if __name__ == "__main__":
    main()
