"""Prepare or verify the catalog-driven people family and the combined character catalog.

    uv run python scripts/prepare_character_people.py --blender PATH [--source DIR]
    uv run python scripts/prepare_character_people.py --verify-only

Building needs the pinned Blender 4.5.9 and the pinned MPFB 2 source and MakeHuman system
assets (see assets/characters/makehuman-parametric-v1/source-lock.json); nothing is fetched.
Verification needs only the repository: every catalog entry's bytes, digests and import
manifests are checked, and the TypeScript catalog module is compared with catalog.json.
"""

import argparse
import hashlib
import json
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(ROOT / "scripts/character_catalog"))

import people  # noqa: E402
from parametric_character.inputs import verify_inputs  # noqa: E402

CATALOG = ROOT / "assets/characters/catalog.json"
TS_CATALOG = ROOT / "web/packages/atlas-react/src/playcanvas/character/catalog-data.ts"
CATALOG_ID = "exulanica-characters"
CATALOG_REVISION = 1
TS_HEADER = """// Generated by scripts/prepare_character_people.py from assets/characters/catalog.json.
// Do not edit: character-catalog-data.test.ts fails when this differs from the JSON.
import { validateCharacterCatalog, type CharacterCatalog } from './catalog.js';

export const CHARACTER_CATALOG_JSON = """


def catalog_document(family, population):
    return {
        "profile": "exulanica.character-catalog/v1",
        "catalogId": CATALOG_ID,
        "revision": CATALOG_REVISION,
        "families": [family],
        "population": [population],
    }


def write_catalog(document):
    text = json.dumps(document, indent=1, sort_keys=True) + "\n"
    CATALOG.write_text(text)
    TS_CATALOG.write_text(
        TS_HEADER
        + json.dumps(json.dumps(document, sort_keys=True, separators=(",", ":")))
        + ";\n\nexport const CHARACTER_CATALOG: CharacterCatalog = validateCharacterCatalog(\n"
        + "  JSON.parse(CHARACTER_CATALOG_JSON) as CharacterCatalog,\n);\n"
    )


def iter_assets(document):
    for family in document["families"]:
        for base in family["bases"]:
            yield base["asset"]
            for part in base["parts"]:
                if "asset" in part:
                    yield part["asset"]
        for material in family["materials"]:
            yield material["asset"]


def verify(document=None):
    """Raise unless every catalog asset matches its bytes and reviewed import manifest."""
    from exulanica.world.asset_import import ReviewedAssetImport, validate_asset_import

    document = document or json.loads(CATALOG.read_text())
    characters = ROOT / "assets/characters"
    imports = {}
    for family in document["families"]:
        licence_path = characters / family["licence"]["file"]
        licence = licence_path.read_bytes()
        if hashlib.sha256(licence).hexdigest() != family["licence"]["sha256"]:
            raise ValueError(f"{family['familyId']} licence digest changed")
        manifest_file = licence_path.parent / "imports.json"
        for manifest in json.loads(manifest_file.read_text()):
            imports[manifest["asset_key"]] = (ReviewedAssetImport.model_validate(manifest), licence)
    count = 0
    for asset in iter_assets(document):
        payload = (characters / asset["file"]).read_bytes()
        if len(payload) != asset["byteSize"] or hashlib.sha256(payload).hexdigest() != asset["contentSha256"]:
            raise ValueError(f"{asset['file']} does not match the catalog")
        manifest, licence = imports[asset["assetKey"]]
        validate_asset_import(manifest, payload, licence)
        count += 1
    expected = TS_HEADER + json.dumps(json.dumps(document, sort_keys=True, separators=(",", ":")))
    if not TS_CATALOG.read_text().startswith(expected):
        raise ValueError("catalog-data.ts is stale; rerun the preparation")
    return count


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--blender", type=Path)
    parser.add_argument(
        "--source",
        type=Path,
        default=ROOT / ".exulanica/briefs/parametric-human",
        help="directory holding the pinned mpfb2 checkout and extracted system-assets",
    )
    parser.add_argument("--workdir", type=Path)
    parser.add_argument("--verify-only", action="store_true")
    args = parser.parse_args()
    if args.verify_only:
        print(f"Verified {verify()} character assets")
        return
    if not args.blender:
        parser.error("--blender is required to build")
    family_lock = ROOT / "assets/characters/makehuman-parametric-v1"
    inputs = verify_inputs(args.source.resolve(), args.blender.resolve(), family_lock)
    workdir = args.workdir or Path(tempfile.mkdtemp(prefix="people-"))
    family, population, manifests = people.prepare(
        args.source.resolve(), args.blender.resolve(), workdir, inputs=inputs
    )
    document = catalog_document(family, population)
    write_catalog(document)
    print(f"Prepared {len(manifests)} people assets; verified {verify(document)}")


if __name__ == "__main__":
    main()
