"""Protected topology, reviewed styles, immutable versions, and source availability."""

from exulanica.world.assets import (
    CC0_LICENCE_ID,
    CC0_LICENCE_TEXT,
    GLB_MEDIA_TYPE,
    ReviewedAsset,
    reviewed_assets,
    seed_reviewed_assets,
)
from exulanica.world.errors import (
    InvalidatedSourceVersion,
    InvalidInteractionData,
    InvalidInteractionPreviewState,
    InvalidObjectData,
    InvalidObjectState,
    InvalidPreviewState,
    InvalidStructuralData,
    InvalidStructuralPreviewState,
    InvalidStyleData,
    ProtectedTopologyConflict,
    StaleInteractionPolicy,
    StaleObjectBase,
    StaleStructuralBase,
    StaleStyleVersion,
    UnavailableAsset,
    UnknownWorldResource,
    WorldNotConfigured,
)
from exulanica.world.interaction import (
    INTERACTION_POLICY_REGISTRY,
    InteractionPolicyRegistry,
    InteractionPolicyState,
    InteractionPolicyVersion,
    InteractionPreview,
    InteractionProposal,
    InteractionProposalRecord,
    InteractionRecommendation,
)
from exulanica.world.interaction_repository import WorldInteractionPolicyRepository
from exulanica.world.models import (
    DEFAULT_WORLD_ID,
    ProposalOrigin,
    ProposalProvenance,
    SourceMediaState,
    StylePreview,
    StyleProposal,
    StyleProposalRecord,
    StyleReference,
    StyleScope,
    StyleVersion,
    TopologyContract,
    TopologySourceSlot,
    WorldSourceMedia,
)
from exulanica.world.object_repository import ReviewedAssetRow, WorldObjectRepository
from exulanica.world.objects import (
    MAX_SCALE_MILLI,
    MAX_YAW_MICRORADIANS,
    OBJECT_ID_PATTERN,
    AlternateVersion,
    AuthoredObject,
    ElementOverride,
    ObjectBehaviour,
    ObjectOrigin,
    Transform,
    VersionEdit,
    canonical_delta_document,
    delta_sha256,
    object_document,
    override_document,
    validate_behaviour,
)
from exulanica.world.registry import STYLE_REGISTRY, StyleRegistry
from exulanica.world.repository import WorldStyleRepository
from exulanica.world.structure import (
    PlacementMigration,
    SpatialCandidate,
    SpatialDigests,
    SpatialPreview,
    SpatialSnapshot,
)
from exulanica.world.structure_repository import WorldStructureRepository

__all__ = [
    "CC0_LICENCE_ID",
    "CC0_LICENCE_TEXT",
    "DEFAULT_WORLD_ID",
    "GLB_MEDIA_TYPE",
    "INTERACTION_POLICY_REGISTRY",
    "MAX_SCALE_MILLI",
    "MAX_YAW_MICRORADIANS",
    "OBJECT_ID_PATTERN",
    "STYLE_REGISTRY",
    "AlternateVersion",
    "AuthoredObject",
    "ElementOverride",
    "InteractionPolicyRegistry",
    "InteractionPolicyState",
    "InteractionPolicyVersion",
    "InteractionPreview",
    "InteractionProposal",
    "InteractionProposalRecord",
    "InteractionRecommendation",
    "InvalidInteractionData",
    "InvalidInteractionPreviewState",
    "InvalidObjectData",
    "InvalidObjectState",
    "InvalidPreviewState",
    "InvalidStructuralData",
    "InvalidStructuralPreviewState",
    "InvalidStyleData",
    "InvalidatedSourceVersion",
    "ObjectBehaviour",
    "ObjectOrigin",
    "PlacementMigration",
    "ProposalOrigin",
    "ProposalProvenance",
    "ProtectedTopologyConflict",
    "ReviewedAsset",
    "ReviewedAssetRow",
    "SourceMediaState",
    "SpatialCandidate",
    "SpatialDigests",
    "SpatialPreview",
    "SpatialSnapshot",
    "StaleInteractionPolicy",
    "StaleObjectBase",
    "StaleStructuralBase",
    "StaleStyleVersion",
    "StylePreview",
    "StyleProposal",
    "StyleProposalRecord",
    "StyleReference",
    "StyleRegistry",
    "StyleScope",
    "StyleVersion",
    "TopologyContract",
    "TopologySourceSlot",
    "Transform",
    "UnavailableAsset",
    "UnknownWorldResource",
    "VersionEdit",
    "WorldInteractionPolicyRepository",
    "WorldNotConfigured",
    "WorldObjectRepository",
    "WorldSourceMedia",
    "WorldStructureRepository",
    "WorldStyleRepository",
    "canonical_delta_document",
    "delta_sha256",
    "object_document",
    "override_document",
    "reviewed_assets",
    "seed_reviewed_assets",
    "validate_behaviour",
]
