"""Durable personal-world state: protected topology, reviewed styles, immutable versions,
and source availability.

Repositories own the PostgreSQL transactions. Document modules
(:mod:`exulanica.world.objects`, :mod:`exulanica.world.structure`,
:mod:`exulanica.world.environment_instances`, :mod:`exulanica.world.interaction`)
are pure: an independent verifier can reproduce their documents without a database.

This package's public exports are the style, object, structure, environment-instance,
interaction, composition-preview, saved-entry, and shared society-core types. Scene tiles,
character appearance, companion memory, and society stepping live in sibling modules and are
imported by name, not through this package.
"""

from exulanica.world.assets import (
    CC0_LICENCE_ID,
    CC0_LICENCE_TEXT,
    GLB_MEDIA_TYPE,
    ReviewedAsset,
    reviewed_assets,
    seed_reviewed_assets,
)
from exulanica.world.composition_preview import (
    CompositionBlocked,
    CompositionPlacement,
    CompositionPreview,
    CompositionRequest,
    EnvironmentAdmissionSource,
    PhotoPointMapSource,
    ReviewedAssetSource,
    SourceAttachmentSource,
    apply_composition,
    preview_composition,
)
from exulanica.world.environment_instances import (
    ENVIRONMENT_INSTANCE_ID_PATTERN,
    EnvironmentInstance,
    EnvironmentPlacement,
    EnvironmentSelection,
    EnvironmentSourceBinding,
    SourceAnchor,
    environment_instance_document,
    validate_environment_instance,
)
from exulanica.world.errors import (
    EnvironmentBindingDrift,
    EnvironmentCompositionDenied,
    EnvironmentSourceWithdrawn,
    InvalidatedSourceVersion,
    InvalidEnvironmentData,
    InvalidEnvironmentState,
    InvalidInteractionData,
    InvalidInteractionPreviewState,
    InvalidObjectData,
    InvalidObjectState,
    InvalidPreviewState,
    InvalidStructuralData,
    InvalidStructuralPreviewState,
    InvalidStyleData,
    ProtectedTopologyConflict,
    StaleInteractionPolicy,
    StaleObjectBase,
    StaleStructuralBase,
    StaleStyleVersion,
    UnavailableAsset,
    UnknownWorldResource,
    WorldNotConfigured,
)
from exulanica.world.interaction import (
    INTERACTION_POLICY_REGISTRY,
    InteractionPolicyRegistry,
    InteractionPolicyState,
    InteractionPolicyVersion,
    InteractionPreview,
    InteractionProposal,
    InteractionProposalRecord,
    InteractionRecommendation,
)
from exulanica.world.interaction_repository import WorldInteractionPolicyRepository
from exulanica.world.models import (
    DEFAULT_WORLD_ID,
    ProposalOrigin,
    ProposalProvenance,
    SourceMediaState,
    StylePreview,
    StyleProposal,
    StyleProposalRecord,
    StyleReference,
    StyleScope,
    StyleVersion,
    TopologyContract,
    TopologySourceSlot,
    WorldSourceMedia,
)
from exulanica.world.object_repository import ReviewedAssetRow, WorldObjectRepository
from exulanica.world.objects import (
    MAX_SCALE_MILLI,
    MAX_YAW_MICRORADIANS,
    OBJECT_ID_PATTERN,
    AlternateVersion,
    AuthoredObject,
    ElementOverride,
    ObjectBehaviour,
    ObjectOrigin,
    Transform,
    VersionEdit,
    canonical_delta_document,
    delta_sha256,
    object_document,
    override_document,
    validate_behaviour,
)
from exulanica.world.photo_point_maps import (
    POINT_MAP_INSTANCE_ID_PATTERN,
    PointMapInstance,
    PointMapModel,
    PointMapPlacement,
    PointMapSourceBinding,
    coverage_statement,
    point_map_instance_document,
    scale_statement,
    truth_statement,
    validate_point_map_instance,
)
from exulanica.world.registry import STYLE_REGISTRY, StyleRegistry
from exulanica.world.repository import WorldStyleRepository
from exulanica.world.saved_entries import (
    SavedWorldCandidate,
    SavedWorldEntry,
    SavedWorldEntryRepository,
    SavedWorldSourceAttachment,
    SourceAttachmentOperationConflict,
    SourceAttachmentSelection,
    StaleSavedWorldEntry,
)
from exulanica.world.society import (
    SOCIETY_ENGINE_VERSION,
    SOCIETY_POPULATION,
    StaleSocietyState,
    UnknownSociety,
)
from exulanica.world.society_repository import SocietyRepository
from exulanica.world.structure import (
    PlacementMigration,
    SpatialCandidate,
    SpatialDigests,
    SpatialPreview,
    SpatialSnapshot,
)
from exulanica.world.structure_repository import WorldStructureRepository
from exulanica.world.style_structure import (
    AuthoredVersionRef,
    CompatibilityIntent,
    ComposedTopologyRef,
    SourceAttachmentRef,
    StructuralSnapshotRef,
    StructureStyleCompatibility,
    StyleStructureFacts,
    StyleVersionRef,
    classify_structure_style_compatibility,
    raise_for_incompatible_structure_style,
)

__all__ = [
    "CC0_LICENCE_ID",
    "CC0_LICENCE_TEXT",
    "DEFAULT_WORLD_ID",
    "ENVIRONMENT_INSTANCE_ID_PATTERN",
    "GLB_MEDIA_TYPE",
    "INTERACTION_POLICY_REGISTRY",
    "MAX_SCALE_MILLI",
    "MAX_YAW_MICRORADIANS",
    "OBJECT_ID_PATTERN",
    "POINT_MAP_INSTANCE_ID_PATTERN",
    "SOCIETY_ENGINE_VERSION",
    "SOCIETY_POPULATION",
    "STYLE_REGISTRY",
    "AlternateVersion",
    "AuthoredObject",
    "AuthoredVersionRef",
    "CompatibilityIntent",
    "ComposedTopologyRef",
    "CompositionBlocked",
    "CompositionPlacement",
    "CompositionPreview",
    "CompositionRequest",
    "ElementOverride",
    "EnvironmentAdmissionSource",
    "EnvironmentBindingDrift",
    "EnvironmentCompositionDenied",
    "EnvironmentInstance",
    "EnvironmentPlacement",
    "EnvironmentSelection",
    "EnvironmentSourceBinding",
    "EnvironmentSourceWithdrawn",
    "InteractionPolicyRegistry",
    "InteractionPolicyState",
    "InteractionPolicyVersion",
    "InteractionPreview",
    "InteractionProposal",
    "InteractionProposalRecord",
    "InteractionRecommendation",
    "InvalidEnvironmentData",
    "InvalidEnvironmentState",
    "InvalidInteractionData",
    "InvalidInteractionPreviewState",
    "InvalidObjectData",
    "InvalidObjectState",
    "InvalidPreviewState",
    "InvalidStructuralData",
    "InvalidStructuralPreviewState",
    "InvalidStyleData",
    "InvalidatedSourceVersion",
    "ObjectBehaviour",
    "ObjectOrigin",
    "PhotoPointMapSource",
    "PlacementMigration",
    "PointMapInstance",
    "PointMapModel",
    "PointMapPlacement",
    "PointMapSourceBinding",
    "ProposalOrigin",
    "ProposalProvenance",
    "ProtectedTopologyConflict",
    "ReviewedAsset",
    "ReviewedAssetRow",
    "ReviewedAssetSource",
    "SavedWorldCandidate",
    "SavedWorldEntry",
    "SavedWorldEntryRepository",
    "SavedWorldSourceAttachment",
    "SocietyRepository",
    "SourceAnchor",
    "SourceAttachmentOperationConflict",
    "SourceAttachmentRef",
    "SourceAttachmentSelection",
    "SourceAttachmentSource",
    "SourceMediaState",
    "SpatialCandidate",
    "SpatialDigests",
    "SpatialPreview",
    "SpatialSnapshot",
    "StaleInteractionPolicy",
    "StaleObjectBase",
    "StaleSavedWorldEntry",
    "StaleSocietyState",
    "StaleStructuralBase",
    "StaleStyleVersion",
    "StructuralSnapshotRef",
    "StructureStyleCompatibility",
    "StylePreview",
    "StyleProposal",
    "StyleProposalRecord",
    "StyleReference",
    "StyleRegistry",
    "StyleScope",
    "StyleStructureFacts",
    "StyleVersion",
    "StyleVersionRef",
    "TopologyContract",
    "TopologySourceSlot",
    "Transform",
    "UnavailableAsset",
    "UnknownSociety",
    "UnknownWorldResource",
    "VersionEdit",
    "WorldInteractionPolicyRepository",
    "WorldNotConfigured",
    "WorldObjectRepository",
    "WorldSourceMedia",
    "WorldStructureRepository",
    "WorldStyleRepository",
    "apply_composition",
    "canonical_delta_document",
    "classify_structure_style_compatibility",
    "coverage_statement",
    "delta_sha256",
    "environment_instance_document",
    "object_document",
    "override_document",
    "point_map_instance_document",
    "preview_composition",
    "raise_for_incompatible_structure_style",
    "reviewed_assets",
    "scale_statement",
    "seed_reviewed_assets",
    "truth_statement",
    "validate_behaviour",
    "validate_environment_instance",
    "validate_point_map_instance",
]
