"""A workspace's own things: the recipes, plans, kinds and looks it made or admitted (0159).

Here, above the pure ``exulanica.things`` package, because it holds a connection and a store.

Every piece is read by its own reader before it is kept, and again when it is read back:
- a body recipe by ``read_body_recipe``;
- a body plan by ``read_body_plan``;
- a thing kind by ``read_thing_kind``;
- a look by ``read_look``, with its container read by its profile's reader: the product's static
  glTF inspection, or the skinned reader against the plan's own tree.

A version is appended once and never changed. An edit is a new version, and a look is withdrawn by
a row of its own: every read passes a withdrawn look by unless it asks for one, as a kind naming
the look does, so the kind still reads while its look is no longer served. Rows stay inside their
workspace by row-level security. A key the product ships is never a row here: a shipped kind, plan
or look resolves first, so a row shadowing one would never be reached.

A look's container is held by digest in the workspace's own ``looks`` namespace of the
content-addressed store (:data:`exulanica.store.namespaces.LOOK_NAMESPACE`). An intake checks
everything before it writes anything: the documents and the container first, then, under the
workspace's lock, the caps and the versions held. Holding the container's own lock, which the
purger also takes, it then records the container and commits, writes the bytes, and writes the
rows naming them in a transaction that asks the workspace's lock, the caps and the versions again,
so a row never names bytes the store lacks and the store never holds bytes its inventory lacks.

The intake paths:
- :meth:`ThingStore.keep_creature`: a creature drafted from words, its recipe, plan, sketch and
  kind, whose rows are written in one transaction.
- :meth:`ThingStore.admit_look`: a look made elsewhere, generated by route C or imported (a
  traveller's own look from an outside game, built at a deployment), read by
  :func:`read_admission` and then by its intake's own ``admit`` check.
  - Its label and its origin's words are held to the line rule.
  - A share-alike licence is kept only with the credit it asks: the attribution, the authors and
    the licence's address, which the table requires as well.

Each container is recorded in the workspace's inventory of its looks namespace (``look_object``)
before its bytes are written, and that record outlives the look, so the workspace's own erasure
reaches every object the namespace holds. A keep refused after its record (a cap another keep
reached first, or the workspace's erasure) leaves the container recorded and unreferenced until the
workspace is erased.

:meth:`ThingStore.erase_creature` erases a creature drafted from a person's words, whole: a
creature tombstone, and one row naming its kind by digest and that tombstone, whose trigger deletes
the kind, its plan and recipe and every look drawn on that plan, at once (migration 0172), and
enqueues those looks' containers on the tombstone for ``exulanica-purge`` to destroy.

:func:`admitted_look` and :func:`admitted_look_by_digest` are the reads a world's look choice asks:
a look this workspace holds at exactly the reference or digest it names, read again and not
withdrawn, or None. This module reaches the content store only through the store's interface and
imports no evidence module, so the door may ask them for a crossing's look within its import
contract.
"""

from __future__ import annotations

import hashlib
import uuid
from collections.abc import Callable, Iterator, Mapping
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Any, Final

import psycopg
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb

from exulanica.store.base import ContentAddressedStore
from exulanica.store.namespaces import look_lock_key
from exulanica.things.catalogs import BodyPlan, BodyPlanRefused, ThingCatalogs, read_body_plan
from exulanica.things.catalogs import thing_catalogs as shipped_thing_catalogs
from exulanica.things.creatures import Creature
from exulanica.things.kinds import ThingKind, ThingKindRefused, read_thing_kind, shipped_thing_kinds
from exulanica.things.lines import LineRefused, check_line
from exulanica.things.looks import Look, LookRefused, read_look
from exulanica.world.thing_library import shipped_looks
from exulanica.world.workspace_lock import lock_workspace

__all__ = [
    "KINDS_PER_WORKSPACE",
    "LOOKS_PER_WORKSPACE",
    "STORE_CODES",
    "KeptLook",
    "LookAdmission",
    "ThingStore",
    "ThingStoreRefused",
    "admitted_look",
    "admitted_look_by_digest",
    "read_admission",
    "read_withdrawal_reason",
]

#: The most kind versions one workspace keeps: a drafted creature is one, so this bounds what one
#: workspace can draft, as the world kind store bounds its kinds.
KINDS_PER_WORKSPACE: Final = 128
#: The most look versions one workspace keeps: a sketch for every kind, and a sculpted or imported
#: look beside many of them.
LOOKS_PER_WORKSPACE: Final = 256

#: Every refusal the store gives, by code, with the sentence a person reads.
STORE_CODES: Final = {
    "thing_key_shipped": "the product ships a thing of that name",
    "thing_version_exists": "this workspace already holds that version, or the same document",
    "thing_cap_reached": "this workspace keeps as many of these as it may",
    "look_refused": "the look is not one this product reads",
    "look_without_container": "this store keeps a look with the file it is drawn from, and this "
    "look draws none",
    "look_container_mismatch": "the container is not the one the look names",
    "look_container_refused": "the container is not one this look's kind can be drawn from",
    "look_text_refused": "the look's label or its origin's words are not plain lines",
    "look_credit_missing": "a share-alike look is kept only with its attribution, its authors and "
    "its licence's address",
    "look_not_admitted": "the look was not admitted by the check its intake asks",
    "look_unknown": "this workspace holds no such look",
    "withdrawal_reason_refused": "a withdrawal's reason is one plain line",
    "kind_unknown": "this workspace holds no such kind",
    "kind_not_yours": "a creature is erased by the person who drafted it or by an owner of its "
    "workspace",
    "kind_changed": "the creature changed while it was being erased; ask again",
    "restore_sealed": "this installation is sealed for a restore and erases nothing until the "
    "restore's replay ends",
    "workspace_erased": "this workspace is being erased, and keeps nothing more",
    "keep_in_transaction": "a keep commits its container's record before it writes the bytes, so "
    "it is asked only on an autocommit connection outside any transaction",
    "look_plan_gone": "the creature this look is drawn for was erased while the look was kept",
}
_STATIC: Final = "exulanica.static-glb/v1"
_SKINNED: Final = "exulanica.skinned-glb/v1"
#: The bound the line rule is asked with for a look's words. The look's and the origin's readers
#: hold each field to its own bound, none longer than this; the line rule adds normal form C and
#: the characters no line holds, such as direction overrides and zero-width characters.
_TEXT_CHARACTERS: Final = 400
#: The longest reason a withdrawal states, as the table bounds it.
_REASON_CHARACTERS: Final = 400
#: The reason a creature tombstone states, which the purge hands the store with its bytes: the
#: erasure's own, never anything the person wrote.
_ERASURE_REASON: Final = "a creature drafted from a person's words was erased"


class ThingStoreRefused(ValueError):
    """A piece the store will not keep, or a look it does not hold, by code."""

    def __init__(self, code: str, detail: str) -> None:
        super().__init__(f"{code}: {detail}")
        self.code = code
        self.detail = detail


def _refuse(code: str, detail: str | None = None) -> ThingStoreRefused:
    return ThingStoreRefused(code, detail or STORE_CODES[code])


@dataclass(frozen=True, slots=True)
class KeptLook:
    """A look this workspace holds, as read again, and its container's place."""

    look: Look
    container_sha256: str
    container_bytes: int
    container_profile: str
    withdrawn: bool


@dataclass(frozen=True, slots=True)
class LookAdmission:
    """A look made elsewhere as read for keeping: the look, the profile its container was read by,
    and what that profile's reader measured."""

    look: Look
    container_profile: str
    report: Mapping[str, Any]


def _plan_key(name: str) -> tuple[str, int] | None:
    key, _, version = name.partition("/v")
    return (key, int(version)) if version.isdigit() else None


def _shipped_look_keys() -> frozenset[str]:
    return frozenset(key for key, _version in shipped_looks())


def _look_texts(document: Mapping[str, Any]) -> Iterator[tuple[str, object]]:
    """Every free text a look states that a person may read, by where it is: the label a card
    shows and its origin's words. A field the origin states as none is given as None."""
    yield "label", document["label"]
    origin = document["origin"]
    yield "origin.licence.attribution", origin["licence"]["attribution"]
    yield "origin.licence.licence_url", origin["licence"]["licence_url"]
    for index, author in enumerate(origin["authors"]):
        yield f"origin.authors[{index}]", author
    for index, source in enumerate(origin["sources"]):
        yield f"origin.sources[{index}].reference", source["reference"]
        yield f"origin.sources[{index}].revision", source["revision"]
    by = origin["by"]
    for field in ("provider", "model_id", "prompt_version", "bridge"):
        yield f"origin.by.{field}", by.get(field)


def read_admission(
    document: Mapping[str, Any],
    container: bytes,
    *,
    catalogs: ThingCatalogs | None = None,
    plan_of: Callable[[str], BodyPlan | None] | None = None,
) -> LookAdmission:
    """A look made elsewhere and its container, read with every check the store makes of them that
    needs no database, or :class:`ThingStoreRefused` by name, in this order: a look the reader
    refuses, a shipped key, a look that draws no file, a container that is not the one the look
    names, a label or origin words that are not plain lines, a share-alike licence without its
    credit, and a container its profile's reader refuses.

    ``plan_of`` resolves a body plan the catalogs do not state (a workspace's drafted plan); without
    it, only a look of a shipped plan is read. :meth:`ThingStore.admit_look` asks this before its
    intake's own check, and an operator's dry run asks the same."""
    catalogs = catalogs or shipped_thing_catalogs()
    try:
        look = read_look(dict(document), catalogs=catalogs, plan_of=plan_of)
    except LookRefused as exc:
        raise _refuse("look_refused", str(exc)) from exc
    if look.look in _shipped_look_keys():
        raise _refuse("thing_key_shipped")
    _check_container(container, look.document["container"])
    for where, text in _look_texts(look.document):
        if text is None:
            continue
        try:
            check_line(text, maximum=_TEXT_CHARACTERS)
        except LineRefused as exc:
            raise _refuse("look_text_refused", f"{where}: {exc}") from exc
    origin = look.document["origin"]
    licence = origin["licence"]
    if licence["share_alike"] and not (
        licence["attribution"] and origin["authors"] and licence["licence_url"]
    ):
        raise _refuse("look_credit_missing")
    plan = catalogs.plan(look.body_plan)
    if plan is None and plan_of is not None:
        plan = plan_of(look.body_plan)
    profile, report = _read_container(look, container, plan)
    return LookAdmission(look=look, container_profile=profile, report=report)


class ThingStore:
    """Keep and read a workspace's things through one workspace-scoped connection.

    ``looks`` is the workspace's own namespace of the content-addressed store, where keeping a look
    writes its container; a store opened without one only reads. Nothing here reads a container
    back: the routes serve one from the namespace, by the digest a held look names."""

    def __init__(
        self,
        connection: psycopg.Connection,
        workspace_id: uuid.UUID,
        looks: ContentAddressedStore | None,
        *,
        catalogs: ThingCatalogs | None = None,
    ) -> None:
        self.connection = connection
        self.workspace_id = workspace_id
        self.looks = looks
        self.catalogs = catalogs or shipped_thing_catalogs()

    # -- reading ---------------------------------------------------------------------------------

    def plan(self, name: str) -> BodyPlan | None:
        """A drafted plan this workspace holds, by its name (``key/vN``), read again."""
        found = _plan_key(name)
        if found is None:
            return None
        with self.connection.cursor(row_factory=dict_row) as cursor:
            row = cursor.execute(
                "select document, sha256 from body_plan_version where workspace_id=%s and key=%s "
                "and version=%s",
                (self.workspace_id, *found),
            ).fetchone()
        if row is None:
            return None
        try:
            plan = read_body_plan(row["document"], catalogs=self.catalogs)
        except BodyPlanRefused:
            return None
        return plan if plan.sha256 == row["sha256"] else None

    def _plan_of(self, name: str) -> BodyPlan | None:
        return self.catalogs.plan(name) or self.plan(name)

    def plan_document_by_digest(self, sha256: str) -> Mapping[str, Any] | None:
        """The document of a drafted plan this workspace holds, by its digest, once its reader
        reads it again at that digest; None otherwise. A page draws a held kind's figure on it."""
        with self.connection.cursor(row_factory=dict_row) as cursor:
            row = cursor.execute(
                "select document from body_plan_version where workspace_id=%s and sha256=%s",
                (self.workspace_id, sha256),
            ).fetchone()
        if row is None:
            return None
        try:
            plan = read_body_plan(row["document"], catalogs=self.catalogs)
        except BodyPlanRefused:
            return None
        return row["document"] if plan.sha256 == sha256 else None

    def look(self, key: str, version: int, *, include_withdrawn: bool = False) -> KeptLook | None:
        """A look this workspace holds by key and version, read again, or None: no such row, a
        document the reader now refuses, or a withdrawn look unless ``include_withdrawn``."""
        with self.connection.cursor(row_factory=dict_row) as cursor:
            row = cursor.execute(
                "select l.document, l.sha256, l.container_sha256, l.container_bytes, "
                "l.container_profile, (w.key is not null) as withdrawn from look_version l "
                "left join look_withdrawal w on w.workspace_id=l.workspace_id and w.key=l.key "
                "and w.version=l.version where l.workspace_id=%s and l.key=%s and l.version=%s",
                (self.workspace_id, key, version),
            ).fetchone()
        if row is None or (row["withdrawn"] and not include_withdrawn):
            return None
        try:
            look = read_look(row["document"], catalogs=self.catalogs, plan_of=self._plan_of)
        except LookRefused:
            return None
        if look.sha256 != row["sha256"]:
            return None
        return KeptLook(
            look=look,
            container_sha256=row["container_sha256"],
            container_bytes=row["container_bytes"],
            container_profile=row["container_profile"],
            withdrawn=row["withdrawn"],
        )

    def look_by_digest(self, sha256: str, *, include_withdrawn: bool = False) -> KeptLook | None:
        """A look this workspace holds by its document's digest, read again, or None as
        :meth:`look` answers."""
        with self.connection.cursor(row_factory=dict_row) as cursor:
            row = cursor.execute(
                "select key, version from look_version where workspace_id=%s and sha256=%s",
                (self.workspace_id, sha256),
            ).fetchone()
        if row is None:
            return None
        return self.look(row["key"], row["version"], include_withdrawn=include_withdrawn)

    def looks_held(self) -> list[Look]:
        """Every look this workspace holds and has not withdrawn, read again, in key and version
        order: a document the reader now refuses is left out, as :meth:`look` leaves it."""
        with self.connection.cursor(row_factory=dict_row) as cursor:
            rows = cursor.execute(
                "select l.key, l.version from look_version l "
                "left join look_withdrawal w on w.workspace_id=l.workspace_id and w.key=l.key "
                "and w.version=l.version where l.workspace_id=%s and w.key is null "
                "order by l.key, l.version",
                (self.workspace_id,),
            ).fetchall()
        found = [self.look(row["key"], row["version"]) for row in rows]
        return [kept.look for kept in found if kept is not None]

    def kind(self, key: str, version: int) -> ThingKind | None:
        """A kind this workspace holds by key and version, read again with its looks and its plan
        resolved here, or None: no such row, or a document the reader now refuses.

        A look the workspace withdrew still resolves for its kind: the kind stays what it is and
        only the look is no longer served, so a creature whose one look was withdrawn reads with
        no look to draw."""
        with self.connection.cursor(row_factory=dict_row) as cursor:
            row = cursor.execute(
                "select document, sha256 from thing_kind_version where workspace_id=%s and key=%s "
                "and version=%s",
                (self.workspace_id, key, version),
            ).fetchone()
        if row is None:
            return None

        def look_of(reference: Mapping[str, Any]) -> Look | None:
            kept = self.look(
                str(reference["look"]), int(reference["version"]), include_withdrawn=True
            )
            if kept is None or kept.look.sha256 != reference.get("sha256"):
                return None
            return kept.look

        try:
            kind = read_thing_kind(
                row["document"], catalogs=self.catalogs, look_of=look_of, plan_of=self._plan_of
            )
        except ThingKindRefused:
            return None
        return kind if kind.sha256 == row["sha256"] else None

    def kind_by_digest(self, sha256: str) -> ThingKind | None:
        """A kind this workspace holds by its document's digest, read again."""
        with self.connection.cursor(row_factory=dict_row) as cursor:
            row = cursor.execute(
                "select key, version from thing_kind_version where workspace_id=%s and sha256=%s",
                (self.workspace_id, sha256),
            ).fetchone()
        return None if row is None else self.kind(row["key"], row["version"])

    def _store(self) -> ContentAddressedStore:
        if self.looks is None:
            raise RuntimeError("this store was opened to read documents, never to keep a look")
        return self.looks

    # -- keeping ---------------------------------------------------------------------------------

    def _count(self, table: str) -> int:
        with self.connection.cursor(row_factory=dict_row) as cursor:
            row = cursor.execute(
                f"select count(*) as n from {table} where workspace_id=%s",
                (self.workspace_id,),
            ).fetchone()
        return 0 if row is None else int(row["n"])

    def _holds(self, table: str, key: str, version: int, sha256: str) -> bool:
        """Whether this workspace holds ``key`` at ``version``, or the same document under any
        name, in ``table``."""
        with self.connection.cursor(row_factory=dict_row) as cursor:
            row = cursor.execute(
                f"select exists (select 1 from {table} where workspace_id=%s and "
                "((key=%s and version=%s) or sha256=%s)) as held",
                (self.workspace_id, key, version, sha256),
            ).fetchone()
        return bool(row and row["held"])

    def _erased(self) -> bool:
        """Whether this workspace's own tombstone is effective: nothing more is kept in it."""
        with self.connection.cursor(row_factory=dict_row) as cursor:
            row = cursor.execute(
                "select exists (select 1 from tombstone where workspace_id=%s "
                "and scope='workspace' and effective_at <= clock_timestamp()) as erased",
                (self.workspace_id,),
            ).fetchone()
        return bool(row and row["erased"])

    def _record_object(self, container: bytes) -> None:
        """Record a container in the looks namespace's inventory before its bytes are written,
        unless a live record holds it already; the table refuses it once a workspace tombstone is
        effective."""
        self.connection.execute(
            "insert into look_object (workspace_id, content_sha256, byte_size) values (%s,%s,%s) "
            "on conflict (workspace_id, content_sha256) where purged_at is null do nothing",
            (self.workspace_id, hashlib.sha256(container).hexdigest(), len(container)),
        )

    @contextmanager
    def _holding(self, container: bytes) -> Iterator[None]:
        """The container's session lock (``look_lock_key``), which the purger takes before it
        destroys one, held from recording the container until the rows naming it commit.

        The asset queue holds its objects the same way; its helper is not borrowed because its
        module reads evidence, which the door, a reader of this one, may not reach."""
        key = look_lock_key(self.workspace_id, hashlib.sha256(container).hexdigest())
        self.connection.execute("select pg_advisory_lock(hashtextextended(%s, 0))", (key,))
        released = False
        try:
            yield
        finally:
            with self.connection.cursor(row_factory=dict_row) as cursor:
                row = cursor.execute(
                    "select pg_advisory_unlock(hashtextextended(%s, 0)) as released", (key,)
                ).fetchone()
            released = bool(row and row["released"])
        if not released:
            raise RuntimeError("the container's lock was not held when the keep released it")

    def _keep(self, container: bytes, check: Callable[[], None], write: Callable[[], None]) -> None:
        """Record ``container``, write its bytes, then ``write`` the rows naming it.

        Holding the container's lock throughout: the record commits first, under the workspace's
        lock and after ``check``, so the workspace's erasure reaches every byte the namespace
        holds; then the bytes; then the rows, in a transaction that takes the workspace's lock and
        asks ``check`` and whether the workspace is being erased again, so a row never names bytes
        the store lacks. Refused by name: ``check``'s refusals, ``thing_version_exists`` for a
        version another keep wrote first, ``workspace_erased``, and ``keep_in_transaction`` when
        the connection is not in autocommit or is inside an open transaction, before anything is
        recorded."""

        def checked() -> None:
            lock_workspace(self.connection, self.workspace_id)
            if self._erased():
                raise _refuse("workspace_erased")
            check()

        # Inside an open transaction each block below would be a savepoint, so the record would
        # commit only with the rows, after the bytes; without autocommit the lock's own statement
        # would open that transaction. Nothing is recorded or written then.
        if (
            not self.connection.autocommit
            or self.connection.info.transaction_status != psycopg.pq.TransactionStatus.IDLE
        ):
            raise _refuse("keep_in_transaction")
        try:
            with self._holding(container):
                with self.connection.transaction():
                    checked()
                    self._record_object(container)
                self._store().put_bytes(container)
                with self.connection.transaction():
                    checked()
                    write()
        except psycopg.errors.UniqueViolation as exc:
            raise _refuse("thing_version_exists") from exc
        except psycopg.errors.IntegrityConstraintViolation as exc:
            if _tombstoned(exc):
                raise _refuse("workspace_erased") from exc
            raise

    def keep_creature(self, creature: Creature, *, created_by: uuid.UUID) -> None:
        """Keep a creature's recipe, plan, sketch and kind, each as assembled and read, the four
        rows in one transaction after the sketch's container is recorded and written. Refused by
        name before anything is written: a shipped key, a sketch container that is not the one the
        sketch names or that the static reader refuses, a reached cap, or a version or document
        this workspace holds."""
        if (
            creature.kind.kind
            in {key for key, _version in shipped_thing_kinds(catalogs=self.catalogs)}
            or creature.plan.key in {plan.key for plan in self.catalogs.plans.values()}
            or creature.sketch.look in _shipped_look_keys()
        ):
            raise _refuse("thing_key_shipped")
        _check_container(creature.sketch_container, creature.sketch.document["container"])
        admission = _static_admission(creature.sketch_container)

        def check() -> None:
            if self._count("thing_kind_version") >= KINDS_PER_WORKSPACE or (
                self._count("look_version") >= LOOKS_PER_WORKSPACE
            ):
                raise _refuse("thing_cap_reached")
            if (
                self._holds(
                    "body_plan_version",
                    creature.plan.key,
                    creature.plan.version,
                    creature.plan.sha256,
                )
                or self._holds(
                    "look_version",
                    creature.sketch.look,
                    creature.sketch.version,
                    creature.sketch.sha256,
                )
                or self._holds(
                    "thing_kind_version",
                    creature.kind.kind,
                    creature.kind.version,
                    creature.kind.sha256,
                )
            ):
                raise _refuse("thing_version_exists")

        def write() -> None:
            # A recipe two creatures share is one row; it holds figures, colours and the
            # appearance, and the digest of the words sits only in the plan's and the kind's
            # origin, which an erasure deletes.
            self.connection.execute(
                "insert into body_recipe_version (workspace_id,sha256,document,created_by) "
                "values (%s,%s,%s,%s) on conflict do nothing",
                (
                    self.workspace_id,
                    creature.recipe_sha256,
                    Jsonb(dict(creature.recipe)),
                    created_by,
                ),
            )
            self.connection.execute(
                "insert into body_plan_version (workspace_id,key,version,sha256,document,"
                "recipe_sha256,created_by) values (%s,%s,%s,%s,%s,%s,%s)",
                (
                    self.workspace_id,
                    creature.plan.key,
                    creature.plan.version,
                    creature.plan.sha256,
                    Jsonb(dict(creature.plan_document)),
                    creature.recipe_sha256,
                    created_by,
                ),
            )
            self.connection.execute(
                "insert into look_version (workspace_id,key,version,sha256,document,"
                "plan_sha256,container_profile,admission,created_by) "
                "values (%s,%s,%s,%s,%s,%s,%s,%s,%s)",
                (
                    self.workspace_id,
                    creature.sketch.look,
                    creature.sketch.version,
                    creature.sketch.sha256,
                    Jsonb(dict(creature.sketch.document)),
                    creature.plan.sha256,
                    _STATIC,
                    Jsonb(admission),
                    created_by,
                ),
            )
            self.connection.execute(
                "insert into thing_kind_version (workspace_id,key,version,sha256,document,"
                "plan,plan_sha256,created_by) values (%s,%s,%s,%s,%s,%s,%s,%s)",
                (
                    self.workspace_id,
                    creature.kind.kind,
                    creature.kind.version,
                    creature.kind.sha256,
                    Jsonb(dict(creature.kind.document)),
                    creature.plan.name,
                    creature.plan.sha256,
                    created_by,
                ),
            )

        self._keep(creature.sketch_container, check, write)

    def admit_look(
        self,
        document: Mapping[str, Any],
        container: bytes,
        *,
        created_by: uuid.UUID,
        admit: Callable[[Look], None],
    ) -> KeptLook:
        """Keep a look made elsewhere (generated, imported or uploaded) with its container.

        Read by :func:`read_admission`, then by ``admit``, the intake's own check, which raises
        :class:`ThingStoreRefused` to refuse; then refused by name under the workspace's lock when
        the library is full or already holds that version or document. Nothing is written until
        every check has passed; the container is then recorded and written before the look's row,
        as :meth:`keep_creature` does."""
        admission = read_admission(document, container, catalogs=self.catalogs, plan_of=self.plan)
        look = admission.look
        admit(look)
        plan = self.plan(look.body_plan)

        def check() -> None:
            if self._count("look_version") >= LOOKS_PER_WORKSPACE:
                raise _refuse("thing_cap_reached")
            if self._holds("look_version", look.look, look.version, look.sha256):
                raise _refuse("thing_version_exists")
            # A drafted plan read before the lock may have been erased since: read it again under
            # the lock, so the look's row never names a plan the workspace no longer holds.
            if plan is not None:
                again = self.plan(look.body_plan)
                if again is None or again.sha256 != plan.sha256:
                    raise _refuse("look_plan_gone")

        def write() -> None:
            self.connection.execute(
                "insert into look_version (workspace_id,key,version,sha256,document,"
                "plan_sha256,container_profile,admission,created_by) "
                "values (%s,%s,%s,%s,%s,%s,%s,%s,%s)",
                (
                    self.workspace_id,
                    look.look,
                    look.version,
                    look.sha256,
                    Jsonb(dict(look.document)),
                    None if plan is None else plan.sha256,
                    admission.container_profile,
                    Jsonb(dict(admission.report)),
                    created_by,
                ),
            )

        self._keep(container, check, write)
        found = self.look(look.look, look.version)
        if found is None:
            raise RuntimeError("a look this store kept does not read back")
        return found

    def erase_creature(
        self, kind_sha256: str, *, erased_by: uuid.UUID, by_owner: bool = False
    ) -> uuid.UUID:
        """Erase a creature this workspace drafted, whole, and answer the erasure's id.

        Under the workspace's lock, a creature tombstone, then one row naming the kind by its
        document's digest and that tombstone; the row's trigger deletes, at once and as the definer
        owner, the kind, and when no other kind names its drafted plan, the looks drawn on that
        plan with their withdrawals, the plan and its recipe (migration 0172), and enqueues those
        looks' containers on the tombstone, which the purge destroys. A restore carries both.
        Asked by the person who drafted the creature (``erased_by`` is the kind's ``created_by``)
        or, with ``by_owner``, by an owner of the workspace. Refused by name: a kind this
        workspace does not hold (``kind_unknown``), anyone else's ask (``kind_not_yours``), a row
        the database refuses (``kind_changed``) and an installation sealed for a restore
        (``restore_sealed``, migration 0107)."""
        try:
            with (
                self.connection.transaction(),
                self.connection.cursor(row_factory=dict_row) as cursor,
            ):
                lock_workspace(self.connection, self.workspace_id)
                held = cursor.execute(
                    "select created_by from thing_kind_version where workspace_id=%s and sha256=%s",
                    (self.workspace_id, kind_sha256),
                ).fetchone()
                if held is None:
                    raise _refuse("kind_unknown")
                if held["created_by"] != erased_by and not by_owner:
                    raise _refuse("kind_not_yours")
                tombstone = cursor.execute(
                    "insert into tombstone (workspace_id, scope, requested_by, reason) "
                    "values (%s, 'creature', %s, %s) returning tombstone_id",
                    (self.workspace_id, erased_by, _ERASURE_REASON),
                ).fetchone()
                assert tombstone is not None
                row = cursor.execute(
                    "insert into thing_erasure (workspace_id, sha256, tombstone_id, erased_by) "
                    "values (%s,%s,%s,%s) returning erasure_id",
                    (self.workspace_id, kind_sha256, tombstone["tombstone_id"], erased_by),
                ).fetchone()
        except psycopg.errors.ObjectNotInPrerequisiteState as exc:
            raise _refuse("restore_sealed") from exc
        except psycopg.IntegrityError as exc:
            raise _refuse("kind_changed") from exc
        assert row is not None
        return row["erasure_id"]

    def withdraw_look(
        self, key: str, version: int, reason: str, *, withdrawn_by: uuid.UUID
    ) -> None:
        """Withdraw a look this workspace holds, once: a choice naming it then finds none, and its
        container is no longer served. The row is what is withdrawn, so a look whose document the
        reader now refuses can still be withdrawn; asking again changes nothing."""
        read_withdrawal_reason(reason)
        with self.connection.transaction():
            with self.connection.cursor(row_factory=dict_row) as cursor:
                row = cursor.execute(
                    "select sha256 from look_version where workspace_id=%s and key=%s "
                    "and version=%s",
                    (self.workspace_id, key, version),
                ).fetchone()
            if row is None:
                raise _refuse("look_unknown")
            self.connection.execute(
                "insert into look_withdrawal (workspace_id,key,version,sha256,reason,"
                "withdrawn_by) values (%s,%s,%s,%s,%s,%s) on conflict do nothing",
                (self.workspace_id, key, version, row["sha256"], reason, withdrawn_by),
            )


def _tombstoned(exc: psycopg.errors.IntegrityConstraintViolation) -> bool:
    """Whether the schema refused a write because a tombstone covers it (``tombstone_refuse``)."""
    return (exc.diag.message_primary or "").startswith("tombstoned: write refused")


def read_withdrawal_reason(reason: object) -> str:
    """``reason`` as a withdrawal states it, one plain line the table holds, or
    :class:`ThingStoreRefused` (``withdrawal_reason_refused``)."""
    try:
        return check_line(reason, maximum=_REASON_CHARACTERS)
    except LineRefused as exc:
        raise _refuse("withdrawal_reason_refused", str(exc)) from exc


def _check_container(container: bytes, held: Mapping[str, Any] | None) -> None:
    """Refuse a look that names no container, and bytes that are not the container a look names,
    by digest and length."""
    if held is None:
        raise _refuse("look_without_container")
    if hashlib.sha256(container).hexdigest() != held["sha256"] or len(container) != held["bytes"]:
        raise _refuse("look_container_mismatch")


def _read_container(
    look: Look, container: bytes, plan: BodyPlan | None
) -> tuple[str, dict[str, Any]]:
    """The container's profile and what its reader measured, or a refusal by name: a skinned look
    is read against its plan's own tree, and any other by the static glTF inspection."""
    if look.look_kind == "skinned":
        from exulanica_pieces.canonical import Refused
        from exulanica_pieces.skinned import read_skinned_glb

        if plan is None:
            raise _refuse("look_container_refused", "its body plan is not one this reads")
        bones = dict(look.document["rig"]["bones"])
        parents = {bone.name: bone.parent for bone in plan.bones}
        try:
            read = read_skinned_glb(container, bones=bones, plan_parents=parents)
        except Refused as exc:
            raise _refuse("look_container_refused", str(exc)) from exc
        return _SKINNED, {
            "joints": len(read.joints),
            "reader": "exulanica_pieces.skinned.read_skinned_glb",
            "triangles": read.triangles,
        }
    return _STATIC, _static_admission(container)


def _static_admission(container: bytes) -> dict[str, Any]:
    """What the static container profile's admission measured, or a refusal by name."""
    from exulanica.world.static_glb import StaticGlbRefused, inspect_static_glb

    try:
        inspected = inspect_static_glb(container)
    except StaticGlbRefused as exc:
        raise _refuse("look_container_refused", f"{exc.reason}: {exc}") from exc
    return {
        "counts": {key: int(value) for key, value in sorted(inspected.counts.items())},
        "reader": "exulanica.world.static_glb.inspect_static_glb",
    }


def admitted_look(
    connection: psycopg.Connection,
    workspace_id: uuid.UUID,
    reference: Mapping[str, Any],
) -> Look | None:
    """The look this workspace holds at exactly ``reference`` (``{look, version, sha256}``),
    read again on the caller's connection and transaction, or None: no such row, another digest,
    withdrawn, or a document the reader now refuses. Never another workspace's.

    It takes no lock and only reads, within the caller's transaction, so a society's minute may
    call it under its own lock order."""
    kept = ThingStore(connection, workspace_id, None).look(
        str(reference["look"]), int(reference["version"])
    )
    if kept is None or kept.look.sha256 != reference["sha256"]:
        return None
    return kept.look


def admitted_look_by_digest(
    connection: psycopg.Connection, workspace_id: uuid.UUID, sha256: str
) -> Look | None:
    """The look this workspace holds whose document's digest is ``sha256``, read again on the
    caller's connection and transaction, or None: no such row, withdrawn, or a document the reader
    now refuses. Never another workspace's. A world names a workspace's own look by this digest
    alone, never by a key a person's words made.

    Like :func:`admitted_look`, it takes no lock and only reads."""
    kept = ThingStore(connection, workspace_id, None).look_by_digest(sha256)
    return None if kept is None else kept.look
